/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiAuthProfile200,
  GetApiAuthProfile400,
  GetApiAuthProfile401,
  GetApiAuthProfile500,
  PostApiAuthConfirmEmail200,
  PostApiAuthConfirmEmail400,
  PostApiAuthConfirmEmail401,
  PostApiAuthConfirmEmail500,
  PostApiAuthConfirmEmailBody,
  PostApiAuthLogin200,
  PostApiAuthLogin400,
  PostApiAuthLogin401,
  PostApiAuthLogin500,
  PostApiAuthLoginBody,
  PostApiAuthRecoveryPassword200,
  PostApiAuthRecoveryPassword400,
  PostApiAuthRecoveryPassword401,
  PostApiAuthRecoveryPassword500,
  PostApiAuthRecoveryPasswordBody,
  PostApiAuthRegister200,
  PostApiAuthRegister400,
  PostApiAuthRegister401,
  PostApiAuthRegister500,
  PostApiAuthRegisterBody,
  PostApiAuthResendEmail200,
  PostApiAuthResendEmail400,
  PostApiAuthResendEmail401,
  PostApiAuthResendEmail500,
  PostApiAuthResendEmailBody
} from '../../domain/models';

import { apiClient } from '../../../lib/api-client/api-client';
import type { ErrorType , BodyType } from '../../../lib/api-client/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Login user
 */
export const postApiAuthLogin = (
    postApiAuthLoginBody: BodyType<PostApiAuthLoginBody>,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<PostApiAuthLogin200>(
      {url: `/api/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAuthLoginBody, signal
    },
      options);
    }
  


export const getPostApiAuthLoginMutationOptions = <TError = ErrorType<PostApiAuthLogin400 | PostApiAuthLogin401 | PostApiAuthLogin500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data: BodyType<PostApiAuthLoginBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data: BodyType<PostApiAuthLoginBody>}, TContext> => {

const mutationKey = ['postApiAuthLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthLogin>>, {data: BodyType<PostApiAuthLoginBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthLogin(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthLogin>>>
    export type PostApiAuthLoginMutationBody = BodyType<PostApiAuthLoginBody>
    export type PostApiAuthLoginMutationError = ErrorType<PostApiAuthLogin400 | PostApiAuthLogin401 | PostApiAuthLogin500>

    export const usePostApiAuthLogin = <TError = ErrorType<PostApiAuthLogin400 | PostApiAuthLogin401 | PostApiAuthLogin500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthLogin>>, TError,{data: BodyType<PostApiAuthLoginBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthLogin>>,
        TError,
        {data: BodyType<PostApiAuthLoginBody>},
        TContext
      > => {

      const mutationOptions = getPostApiAuthLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Register user
 */
export const postApiAuthRegister = (
    postApiAuthRegisterBody: BodyType<PostApiAuthRegisterBody>,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<PostApiAuthRegister200>(
      {url: `/api/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAuthRegisterBody, signal
    },
      options);
    }
  


export const getPostApiAuthRegisterMutationOptions = <TError = ErrorType<PostApiAuthRegister400 | PostApiAuthRegister401 | PostApiAuthRegister500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegister>>, TError,{data: BodyType<PostApiAuthRegisterBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegister>>, TError,{data: BodyType<PostApiAuthRegisterBody>}, TContext> => {

const mutationKey = ['postApiAuthRegister'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRegister>>, {data: BodyType<PostApiAuthRegisterBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthRegister(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRegister>>>
    export type PostApiAuthRegisterMutationBody = BodyType<PostApiAuthRegisterBody>
    export type PostApiAuthRegisterMutationError = ErrorType<PostApiAuthRegister400 | PostApiAuthRegister401 | PostApiAuthRegister500>

    export const usePostApiAuthRegister = <TError = ErrorType<PostApiAuthRegister400 | PostApiAuthRegister401 | PostApiAuthRegister500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRegister>>, TError,{data: BodyType<PostApiAuthRegisterBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthRegister>>,
        TError,
        {data: BodyType<PostApiAuthRegisterBody>},
        TContext
      > => {

      const mutationOptions = getPostApiAuthRegisterMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Confirm email
 */
export const postApiAuthConfirmEmail = (
    postApiAuthConfirmEmailBody: BodyType<PostApiAuthConfirmEmailBody>,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<PostApiAuthConfirmEmail200>(
      {url: `/api/auth/confirm-email`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAuthConfirmEmailBody, signal
    },
      options);
    }
  


export const getPostApiAuthConfirmEmailMutationOptions = <TError = ErrorType<PostApiAuthConfirmEmail400 | PostApiAuthConfirmEmail401 | PostApiAuthConfirmEmail500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthConfirmEmail>>, TError,{data: BodyType<PostApiAuthConfirmEmailBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthConfirmEmail>>, TError,{data: BodyType<PostApiAuthConfirmEmailBody>}, TContext> => {

const mutationKey = ['postApiAuthConfirmEmail'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthConfirmEmail>>, {data: BodyType<PostApiAuthConfirmEmailBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthConfirmEmail(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthConfirmEmailMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthConfirmEmail>>>
    export type PostApiAuthConfirmEmailMutationBody = BodyType<PostApiAuthConfirmEmailBody>
    export type PostApiAuthConfirmEmailMutationError = ErrorType<PostApiAuthConfirmEmail400 | PostApiAuthConfirmEmail401 | PostApiAuthConfirmEmail500>

    export const usePostApiAuthConfirmEmail = <TError = ErrorType<PostApiAuthConfirmEmail400 | PostApiAuthConfirmEmail401 | PostApiAuthConfirmEmail500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthConfirmEmail>>, TError,{data: BodyType<PostApiAuthConfirmEmailBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthConfirmEmail>>,
        TError,
        {data: BodyType<PostApiAuthConfirmEmailBody>},
        TContext
      > => {

      const mutationOptions = getPostApiAuthConfirmEmailMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Resend email to confirm email
 */
export const postApiAuthResendEmail = (
    postApiAuthResendEmailBody: BodyType<PostApiAuthResendEmailBody>,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<PostApiAuthResendEmail200>(
      {url: `/api/auth/resend-email`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAuthResendEmailBody, signal
    },
      options);
    }
  


export const getPostApiAuthResendEmailMutationOptions = <TError = ErrorType<PostApiAuthResendEmail400 | PostApiAuthResendEmail401 | PostApiAuthResendEmail500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthResendEmail>>, TError,{data: BodyType<PostApiAuthResendEmailBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthResendEmail>>, TError,{data: BodyType<PostApiAuthResendEmailBody>}, TContext> => {

const mutationKey = ['postApiAuthResendEmail'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthResendEmail>>, {data: BodyType<PostApiAuthResendEmailBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthResendEmail(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthResendEmailMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthResendEmail>>>
    export type PostApiAuthResendEmailMutationBody = BodyType<PostApiAuthResendEmailBody>
    export type PostApiAuthResendEmailMutationError = ErrorType<PostApiAuthResendEmail400 | PostApiAuthResendEmail401 | PostApiAuthResendEmail500>

    export const usePostApiAuthResendEmail = <TError = ErrorType<PostApiAuthResendEmail400 | PostApiAuthResendEmail401 | PostApiAuthResendEmail500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthResendEmail>>, TError,{data: BodyType<PostApiAuthResendEmailBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthResendEmail>>,
        TError,
        {data: BodyType<PostApiAuthResendEmailBody>},
        TContext
      > => {

      const mutationOptions = getPostApiAuthResendEmailMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Recovery password
 */
export const postApiAuthRecoveryPassword = (
    postApiAuthRecoveryPasswordBody: BodyType<PostApiAuthRecoveryPasswordBody>,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<PostApiAuthRecoveryPassword200>(
      {url: `/api/auth/recovery-password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAuthRecoveryPasswordBody, signal
    },
      options);
    }
  


export const getPostApiAuthRecoveryPasswordMutationOptions = <TError = ErrorType<PostApiAuthRecoveryPassword400 | PostApiAuthRecoveryPassword401 | PostApiAuthRecoveryPassword500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRecoveryPassword>>, TError,{data: BodyType<PostApiAuthRecoveryPasswordBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRecoveryPassword>>, TError,{data: BodyType<PostApiAuthRecoveryPasswordBody>}, TContext> => {

const mutationKey = ['postApiAuthRecoveryPassword'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuthRecoveryPassword>>, {data: BodyType<PostApiAuthRecoveryPasswordBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiAuthRecoveryPassword(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthRecoveryPasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuthRecoveryPassword>>>
    export type PostApiAuthRecoveryPasswordMutationBody = BodyType<PostApiAuthRecoveryPasswordBody>
    export type PostApiAuthRecoveryPasswordMutationError = ErrorType<PostApiAuthRecoveryPassword400 | PostApiAuthRecoveryPassword401 | PostApiAuthRecoveryPassword500>

    export const usePostApiAuthRecoveryPassword = <TError = ErrorType<PostApiAuthRecoveryPassword400 | PostApiAuthRecoveryPassword401 | PostApiAuthRecoveryPassword500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuthRecoveryPassword>>, TError,{data: BodyType<PostApiAuthRecoveryPasswordBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuthRecoveryPassword>>,
        TError,
        {data: BodyType<PostApiAuthRecoveryPasswordBody>},
        TContext
      > => {

      const mutationOptions = getPostApiAuthRecoveryPasswordMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Obtener detalles del perfil del usuario autenticado
 */
export const getApiAuthProfile = (
    
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<GetApiAuthProfile200>(
      {url: `/api/auth/profile`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiAuthProfileQueryKey = () => {
    return [
    `/api/auth/profile`
    ] as const;
    }

    
export const getGetApiAuthProfileQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuthProfile>>, TError = ErrorType<GetApiAuthProfile400 | GetApiAuthProfile401 | GetApiAuthProfile500>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthProfile>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAuthProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthProfile>>> = ({ signal }) => getApiAuthProfile(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAuthProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAuthProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthProfile>>>
export type GetApiAuthProfileQueryError = ErrorType<GetApiAuthProfile400 | GetApiAuthProfile401 | GetApiAuthProfile500>


export function useGetApiAuthProfile<TData = Awaited<ReturnType<typeof getApiAuthProfile>>, TError = ErrorType<GetApiAuthProfile400 | GetApiAuthProfile401 | GetApiAuthProfile500>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthProfile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthProfile>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthProfile<TData = Awaited<ReturnType<typeof getApiAuthProfile>>, TError = ErrorType<GetApiAuthProfile400 | GetApiAuthProfile401 | GetApiAuthProfile500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthProfile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuthProfile>>,
          TError,
          Awaited<ReturnType<typeof getApiAuthProfile>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthProfile<TData = Awaited<ReturnType<typeof getApiAuthProfile>>, TError = ErrorType<GetApiAuthProfile400 | GetApiAuthProfile401 | GetApiAuthProfile500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthProfile>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAuthProfile<TData = Awaited<ReturnType<typeof getApiAuthProfile>>, TError = ErrorType<GetApiAuthProfile400 | GetApiAuthProfile401 | GetApiAuthProfile500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuthProfile>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAuthProfileQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetApiAuthProfileSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuthProfile>>, TError = ErrorType<GetApiAuthProfile400 | GetApiAuthProfile401 | GetApiAuthProfile500>>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAuthProfile>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAuthProfileQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuthProfile>>> = ({ signal }) => getApiAuthProfile(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAuthProfile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAuthProfileSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuthProfile>>>
export type GetApiAuthProfileSuspenseQueryError = ErrorType<GetApiAuthProfile400 | GetApiAuthProfile401 | GetApiAuthProfile500>


export function useGetApiAuthProfileSuspense<TData = Awaited<ReturnType<typeof getApiAuthProfile>>, TError = ErrorType<GetApiAuthProfile400 | GetApiAuthProfile401 | GetApiAuthProfile500>>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAuthProfile>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthProfileSuspense<TData = Awaited<ReturnType<typeof getApiAuthProfile>>, TError = ErrorType<GetApiAuthProfile400 | GetApiAuthProfile401 | GetApiAuthProfile500>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAuthProfile>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthProfileSuspense<TData = Awaited<ReturnType<typeof getApiAuthProfile>>, TError = ErrorType<GetApiAuthProfile400 | GetApiAuthProfile401 | GetApiAuthProfile500>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAuthProfile>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAuthProfileSuspense<TData = Awaited<ReturnType<typeof getApiAuthProfile>>, TError = ErrorType<GetApiAuthProfile400 | GetApiAuthProfile401 | GetApiAuthProfile500>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAuthProfile>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAuthProfileSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




