/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiAccountTypesId200,
  DeleteApiAccountTypesId400,
  DeleteApiAccountTypesId401,
  DeleteApiAccountTypesId500,
  GetApiAccountTypes200,
  GetApiAccountTypes400,
  GetApiAccountTypes401,
  GetApiAccountTypes500,
  GetApiAccountTypesId200,
  GetApiAccountTypesId400,
  GetApiAccountTypesId401,
  GetApiAccountTypesId500,
  GetApiAccountTypesParams,
  PostApiAccountTypes200,
  PostApiAccountTypes400,
  PostApiAccountTypes401,
  PostApiAccountTypes500,
  PostApiAccountTypesBody,
  PutApiAccountTypesId200,
  PutApiAccountTypesId400,
  PutApiAccountTypesId401,
  PutApiAccountTypesId500,
  PutApiAccountTypesIdBody
} from '../../domain/models';

import { apiClient } from '../../../lib/api-client/api-client';
import type { ErrorType , BodyType } from '../../../lib/api-client/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Listar todos los tipos de cuenta con paginación
 */
export type getApiAccountTypesResponse200 = {
  data: GetApiAccountTypes200
  status: 200
}

export type getApiAccountTypesResponse400 = {
  data: GetApiAccountTypes400
  status: 400
}

export type getApiAccountTypesResponse401 = {
  data: GetApiAccountTypes401
  status: 401
}

export type getApiAccountTypesResponse500 = {
  data: GetApiAccountTypes500
  status: 500
}

export type getApiAccountTypesResponseSuccess = (getApiAccountTypesResponse200) & {
  headers: Headers;
};
export type getApiAccountTypesResponseError = (getApiAccountTypesResponse400 | getApiAccountTypesResponse401 | getApiAccountTypesResponse500) & {
  headers: Headers;
};

export type getApiAccountTypesResponse = (getApiAccountTypesResponseSuccess | getApiAccountTypesResponseError)

export const getGetApiAccountTypesUrl = (params?: GetApiAccountTypesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/accountTypes/?${stringifiedParams}` : `/api/accountTypes/`
}

export const getApiAccountTypes = async (params?: GetApiAccountTypesParams, options?: RequestInit): Promise<getApiAccountTypesResponse> => {

  return apiClient<getApiAccountTypesResponse>(getGetApiAccountTypesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAccountTypesQueryKey = (params?: GetApiAccountTypesParams,) => {
    return [
    `/api/accountTypes/`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiAccountTypesQueryOptions = <TData = Awaited<ReturnType<typeof getApiAccountTypes>>, TError = ErrorType<GetApiAccountTypes400 | GetApiAccountTypes401 | GetApiAccountTypes500>>(params?: GetApiAccountTypesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypes>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAccountTypesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAccountTypes>>> = ({ signal }) => getApiAccountTypes(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAccountTypesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAccountTypes>>>
export type GetApiAccountTypesQueryError = ErrorType<GetApiAccountTypes400 | GetApiAccountTypes401 | GetApiAccountTypes500>


export function useGetApiAccountTypes<TData = Awaited<ReturnType<typeof getApiAccountTypes>>, TError = ErrorType<GetApiAccountTypes400 | GetApiAccountTypes401 | GetApiAccountTypes500>>(
 params: undefined |  GetApiAccountTypesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccountTypes>>,
          TError,
          Awaited<ReturnType<typeof getApiAccountTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountTypes<TData = Awaited<ReturnType<typeof getApiAccountTypes>>, TError = ErrorType<GetApiAccountTypes400 | GetApiAccountTypes401 | GetApiAccountTypes500>>(
 params?: GetApiAccountTypesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccountTypes>>,
          TError,
          Awaited<ReturnType<typeof getApiAccountTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountTypes<TData = Awaited<ReturnType<typeof getApiAccountTypes>>, TError = ErrorType<GetApiAccountTypes400 | GetApiAccountTypes401 | GetApiAccountTypes500>>(
 params?: GetApiAccountTypesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypes>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAccountTypes<TData = Awaited<ReturnType<typeof getApiAccountTypes>>, TError = ErrorType<GetApiAccountTypes400 | GetApiAccountTypes401 | GetApiAccountTypes500>>(
 params?: GetApiAccountTypesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypes>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAccountTypesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetApiAccountTypesSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiAccountTypes>>, TError = ErrorType<GetApiAccountTypes400 | GetApiAccountTypes401 | GetApiAccountTypes500>>(params?: GetApiAccountTypesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypes>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAccountTypesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAccountTypes>>> = ({ signal }) => getApiAccountTypes(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAccountTypesSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAccountTypes>>>
export type GetApiAccountTypesSuspenseQueryError = ErrorType<GetApiAccountTypes400 | GetApiAccountTypes401 | GetApiAccountTypes500>


export function useGetApiAccountTypesSuspense<TData = Awaited<ReturnType<typeof getApiAccountTypes>>, TError = ErrorType<GetApiAccountTypes400 | GetApiAccountTypes401 | GetApiAccountTypes500>>(
 params: undefined |  GetApiAccountTypesParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypes>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountTypesSuspense<TData = Awaited<ReturnType<typeof getApiAccountTypes>>, TError = ErrorType<GetApiAccountTypes400 | GetApiAccountTypes401 | GetApiAccountTypes500>>(
 params?: GetApiAccountTypesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypes>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountTypesSuspense<TData = Awaited<ReturnType<typeof getApiAccountTypes>>, TError = ErrorType<GetApiAccountTypes400 | GetApiAccountTypes401 | GetApiAccountTypes500>>(
 params?: GetApiAccountTypesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypes>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAccountTypesSuspense<TData = Awaited<ReturnType<typeof getApiAccountTypes>>, TError = ErrorType<GetApiAccountTypes400 | GetApiAccountTypes401 | GetApiAccountTypes500>>(
 params?: GetApiAccountTypesParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypes>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAccountTypesSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Crear un nuevo tipo de cuenta
 */
export type postApiAccountTypesResponse200 = {
  data: PostApiAccountTypes200
  status: 200
}

export type postApiAccountTypesResponse400 = {
  data: PostApiAccountTypes400
  status: 400
}

export type postApiAccountTypesResponse401 = {
  data: PostApiAccountTypes401
  status: 401
}

export type postApiAccountTypesResponse500 = {
  data: PostApiAccountTypes500
  status: 500
}

export type postApiAccountTypesResponseSuccess = (postApiAccountTypesResponse200) & {
  headers: Headers;
};
export type postApiAccountTypesResponseError = (postApiAccountTypesResponse400 | postApiAccountTypesResponse401 | postApiAccountTypesResponse500) & {
  headers: Headers;
};

export type postApiAccountTypesResponse = (postApiAccountTypesResponseSuccess | postApiAccountTypesResponseError)

export const getPostApiAccountTypesUrl = () => {




  return `/api/accountTypes/`
}

export const postApiAccountTypes = async (postApiAccountTypesBody: PostApiAccountTypesBody, options?: RequestInit): Promise<postApiAccountTypesResponse> => {

  return apiClient<postApiAccountTypesResponse>(getPostApiAccountTypesUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiAccountTypesBody,)
  }
);}




export const getPostApiAccountTypesMutationOptions = <TError = ErrorType<PostApiAccountTypes400 | PostApiAccountTypes401 | PostApiAccountTypes500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountTypes>>, TError,{data: BodyType<PostApiAccountTypesBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAccountTypes>>, TError,{data: BodyType<PostApiAccountTypesBody>}, TContext> => {

const mutationKey = ['postApiAccountTypes'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAccountTypes>>, {data: BodyType<PostApiAccountTypesBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiAccountTypes(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAccountTypesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAccountTypes>>>
    export type PostApiAccountTypesMutationBody = BodyType<PostApiAccountTypesBody>
    export type PostApiAccountTypesMutationError = ErrorType<PostApiAccountTypes400 | PostApiAccountTypes401 | PostApiAccountTypes500>

    export const usePostApiAccountTypes = <TError = ErrorType<PostApiAccountTypes400 | PostApiAccountTypes401 | PostApiAccountTypes500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountTypes>>, TError,{data: BodyType<PostApiAccountTypesBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAccountTypes>>,
        TError,
        {data: BodyType<PostApiAccountTypesBody>},
        TContext
      > => {
      return useMutation(getPostApiAccountTypesMutationOptions(options), queryClient);
    }
    /**
 * Obtener detalles de un tipo de cuenta por ID
 */
export type getApiAccountTypesIdResponse200 = {
  data: GetApiAccountTypesId200
  status: 200
}

export type getApiAccountTypesIdResponse400 = {
  data: GetApiAccountTypesId400
  status: 400
}

export type getApiAccountTypesIdResponse401 = {
  data: GetApiAccountTypesId401
  status: 401
}

export type getApiAccountTypesIdResponse500 = {
  data: GetApiAccountTypesId500
  status: 500
}

export type getApiAccountTypesIdResponseSuccess = (getApiAccountTypesIdResponse200) & {
  headers: Headers;
};
export type getApiAccountTypesIdResponseError = (getApiAccountTypesIdResponse400 | getApiAccountTypesIdResponse401 | getApiAccountTypesIdResponse500) & {
  headers: Headers;
};

export type getApiAccountTypesIdResponse = (getApiAccountTypesIdResponseSuccess | getApiAccountTypesIdResponseError)

export const getGetApiAccountTypesIdUrl = (id: string,) => {




  return `/api/accountTypes/${id}`
}

export const getApiAccountTypesId = async (id: string, options?: RequestInit): Promise<getApiAccountTypesIdResponse> => {

  return apiClient<getApiAccountTypesIdResponse>(getGetApiAccountTypesIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAccountTypesIdQueryKey = (id: string,) => {
    return [
    `/api/accountTypes/${id}`
    ] as const;
    }


export const getGetApiAccountTypesIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiAccountTypesId>>, TError = ErrorType<GetApiAccountTypesId400 | GetApiAccountTypesId401 | GetApiAccountTypesId500>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAccountTypesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAccountTypesId>>> = ({ signal }) => getApiAccountTypesId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAccountTypesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAccountTypesId>>>
export type GetApiAccountTypesIdQueryError = ErrorType<GetApiAccountTypesId400 | GetApiAccountTypesId401 | GetApiAccountTypesId500>


export function useGetApiAccountTypesId<TData = Awaited<ReturnType<typeof getApiAccountTypesId>>, TError = ErrorType<GetApiAccountTypesId400 | GetApiAccountTypesId401 | GetApiAccountTypesId500>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccountTypesId>>,
          TError,
          Awaited<ReturnType<typeof getApiAccountTypesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountTypesId<TData = Awaited<ReturnType<typeof getApiAccountTypesId>>, TError = ErrorType<GetApiAccountTypesId400 | GetApiAccountTypesId401 | GetApiAccountTypesId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccountTypesId>>,
          TError,
          Awaited<ReturnType<typeof getApiAccountTypesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountTypesId<TData = Awaited<ReturnType<typeof getApiAccountTypesId>>, TError = ErrorType<GetApiAccountTypesId400 | GetApiAccountTypesId401 | GetApiAccountTypesId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAccountTypesId<TData = Awaited<ReturnType<typeof getApiAccountTypesId>>, TError = ErrorType<GetApiAccountTypesId400 | GetApiAccountTypesId401 | GetApiAccountTypesId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAccountTypesIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetApiAccountTypesIdSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiAccountTypesId>>, TError = ErrorType<GetApiAccountTypesId400 | GetApiAccountTypesId401 | GetApiAccountTypesId500>>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAccountTypesIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAccountTypesId>>> = ({ signal }) => getApiAccountTypesId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAccountTypesIdSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAccountTypesId>>>
export type GetApiAccountTypesIdSuspenseQueryError = ErrorType<GetApiAccountTypesId400 | GetApiAccountTypesId401 | GetApiAccountTypesId500>


export function useGetApiAccountTypesIdSuspense<TData = Awaited<ReturnType<typeof getApiAccountTypesId>>, TError = ErrorType<GetApiAccountTypesId400 | GetApiAccountTypesId401 | GetApiAccountTypesId500>>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountTypesIdSuspense<TData = Awaited<ReturnType<typeof getApiAccountTypesId>>, TError = ErrorType<GetApiAccountTypesId400 | GetApiAccountTypesId401 | GetApiAccountTypesId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountTypesIdSuspense<TData = Awaited<ReturnType<typeof getApiAccountTypesId>>, TError = ErrorType<GetApiAccountTypesId400 | GetApiAccountTypesId401 | GetApiAccountTypesId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAccountTypesIdSuspense<TData = Awaited<ReturnType<typeof getApiAccountTypesId>>, TError = ErrorType<GetApiAccountTypesId400 | GetApiAccountTypesId401 | GetApiAccountTypesId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccountTypesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAccountTypesIdSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Actualizar un tipo de cuenta existente por ID
 */
export type putApiAccountTypesIdResponse200 = {
  data: PutApiAccountTypesId200
  status: 200
}

export type putApiAccountTypesIdResponse400 = {
  data: PutApiAccountTypesId400
  status: 400
}

export type putApiAccountTypesIdResponse401 = {
  data: PutApiAccountTypesId401
  status: 401
}

export type putApiAccountTypesIdResponse500 = {
  data: PutApiAccountTypesId500
  status: 500
}

export type putApiAccountTypesIdResponseSuccess = (putApiAccountTypesIdResponse200) & {
  headers: Headers;
};
export type putApiAccountTypesIdResponseError = (putApiAccountTypesIdResponse400 | putApiAccountTypesIdResponse401 | putApiAccountTypesIdResponse500) & {
  headers: Headers;
};

export type putApiAccountTypesIdResponse = (putApiAccountTypesIdResponseSuccess | putApiAccountTypesIdResponseError)

export const getPutApiAccountTypesIdUrl = (id: string,) => {




  return `/api/accountTypes/${id}`
}

export const putApiAccountTypesId = async (id: string,
    putApiAccountTypesIdBody: PutApiAccountTypesIdBody, options?: RequestInit): Promise<putApiAccountTypesIdResponse> => {

  return apiClient<putApiAccountTypesIdResponse>(getPutApiAccountTypesIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putApiAccountTypesIdBody,)
  }
);}




export const getPutApiAccountTypesIdMutationOptions = <TError = ErrorType<PutApiAccountTypesId400 | PutApiAccountTypesId401 | PutApiAccountTypesId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAccountTypesId>>, TError,{id: string;data: BodyType<PutApiAccountTypesIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiAccountTypesId>>, TError,{id: string;data: BodyType<PutApiAccountTypesIdBody>}, TContext> => {

const mutationKey = ['putApiAccountTypesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiAccountTypesId>>, {id: string;data: BodyType<PutApiAccountTypesIdBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiAccountTypesId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiAccountTypesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiAccountTypesId>>>
    export type PutApiAccountTypesIdMutationBody = BodyType<PutApiAccountTypesIdBody>
    export type PutApiAccountTypesIdMutationError = ErrorType<PutApiAccountTypesId400 | PutApiAccountTypesId401 | PutApiAccountTypesId500>

    export const usePutApiAccountTypesId = <TError = ErrorType<PutApiAccountTypesId400 | PutApiAccountTypesId401 | PutApiAccountTypesId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAccountTypesId>>, TError,{id: string;data: BodyType<PutApiAccountTypesIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiAccountTypesId>>,
        TError,
        {id: string;data: BodyType<PutApiAccountTypesIdBody>},
        TContext
      > => {
      return useMutation(getPutApiAccountTypesIdMutationOptions(options), queryClient);
    }
    /**
 * Eliminar un tipo de cuenta por ID
 */
export type deleteApiAccountTypesIdResponse200 = {
  data: DeleteApiAccountTypesId200
  status: 200
}

export type deleteApiAccountTypesIdResponse400 = {
  data: DeleteApiAccountTypesId400
  status: 400
}

export type deleteApiAccountTypesIdResponse401 = {
  data: DeleteApiAccountTypesId401
  status: 401
}

export type deleteApiAccountTypesIdResponse500 = {
  data: DeleteApiAccountTypesId500
  status: 500
}

export type deleteApiAccountTypesIdResponseSuccess = (deleteApiAccountTypesIdResponse200) & {
  headers: Headers;
};
export type deleteApiAccountTypesIdResponseError = (deleteApiAccountTypesIdResponse400 | deleteApiAccountTypesIdResponse401 | deleteApiAccountTypesIdResponse500) & {
  headers: Headers;
};

export type deleteApiAccountTypesIdResponse = (deleteApiAccountTypesIdResponseSuccess | deleteApiAccountTypesIdResponseError)

export const getDeleteApiAccountTypesIdUrl = (id: string,) => {




  return `/api/accountTypes/${id}`
}

export const deleteApiAccountTypesId = async (id: string, options?: RequestInit): Promise<deleteApiAccountTypesIdResponse> => {

  return apiClient<deleteApiAccountTypesIdResponse>(getDeleteApiAccountTypesIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteApiAccountTypesIdMutationOptions = <TError = ErrorType<DeleteApiAccountTypesId400 | DeleteApiAccountTypesId401 | DeleteApiAccountTypesId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAccountTypesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiAccountTypesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiAccountTypesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiAccountTypesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiAccountTypesId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiAccountTypesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiAccountTypesId>>>

    export type DeleteApiAccountTypesIdMutationError = ErrorType<DeleteApiAccountTypesId400 | DeleteApiAccountTypesId401 | DeleteApiAccountTypesId500>

    export const useDeleteApiAccountTypesId = <TError = ErrorType<DeleteApiAccountTypesId400 | DeleteApiAccountTypesId401 | DeleteApiAccountTypesId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAccountTypesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiAccountTypesId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiAccountTypesIdMutationOptions(options), queryClient);
    }
