/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiPeriodsId200,
  DeleteApiPeriodsId400,
  DeleteApiPeriodsId401,
  DeleteApiPeriodsId500,
  GetApiPeriods200,
  GetApiPeriods400,
  GetApiPeriods401,
  GetApiPeriods500,
  GetApiPeriodsId200,
  GetApiPeriodsId400,
  GetApiPeriodsId401,
  GetApiPeriodsId500,
  PostApiPeriods200,
  PostApiPeriods400,
  PostApiPeriods401,
  PostApiPeriods500,
  PostApiPeriodsBody,
  PutApiPeriodsId200,
  PutApiPeriodsId400,
  PutApiPeriodsId401,
  PutApiPeriodsId500,
  PutApiPeriodsIdBody
} from '../../domain/models';

import { apiClient } from '../../../lib/api-client/api-client';
import type { ErrorType , BodyType } from '../../../lib/api-client/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Listar todos los períodos con paginación
 */
export const getApiPeriods = (
    
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<GetApiPeriods200>(
      {url: `/api/periods/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiPeriodsQueryKey = () => {
    return [
    `/api/periods/`
    ] as const;
    }

    
export const getGetApiPeriodsQueryOptions = <TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPeriodsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPeriods>>> = ({ signal }) => getApiPeriods(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPeriodsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPeriods>>>
export type GetApiPeriodsQueryError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>


export function useGetApiPeriods<TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPeriods>>,
          TError,
          Awaited<ReturnType<typeof getApiPeriods>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPeriods<TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPeriods>>,
          TError,
          Awaited<ReturnType<typeof getApiPeriods>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPeriods<TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPeriods<TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPeriodsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetApiPeriodsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPeriodsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPeriods>>> = ({ signal }) => getApiPeriods(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPeriodsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPeriods>>>
export type GetApiPeriodsSuspenseQueryError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>


export function useGetApiPeriodsSuspense<TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPeriodsSuspense<TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPeriodsSuspense<TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPeriodsSuspense<TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPeriodsSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Crear un nuevo período
 */
export const postApiPeriods = (
    postApiPeriodsBody: BodyType<PostApiPeriodsBody>,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<PostApiPeriods200>(
      {url: `/api/periods/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiPeriodsBody, signal
    },
      options);
    }
  


export const getPostApiPeriodsMutationOptions = <TError = ErrorType<PostApiPeriods400 | PostApiPeriods401 | PostApiPeriods500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPeriods>>, TError,{data: BodyType<PostApiPeriodsBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiPeriods>>, TError,{data: BodyType<PostApiPeriodsBody>}, TContext> => {

const mutationKey = ['postApiPeriods'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiPeriods>>, {data: BodyType<PostApiPeriodsBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiPeriods(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiPeriodsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiPeriods>>>
    export type PostApiPeriodsMutationBody = BodyType<PostApiPeriodsBody>
    export type PostApiPeriodsMutationError = ErrorType<PostApiPeriods400 | PostApiPeriods401 | PostApiPeriods500>

    export const usePostApiPeriods = <TError = ErrorType<PostApiPeriods400 | PostApiPeriods401 | PostApiPeriods500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPeriods>>, TError,{data: BodyType<PostApiPeriodsBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiPeriods>>,
        TError,
        {data: BodyType<PostApiPeriodsBody>},
        TContext
      > => {

      const mutationOptions = getPostApiPeriodsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Obtener detalles de un período por ID
 */
export const getApiPeriodsId = (
    id: string,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<GetApiPeriodsId200>(
      {url: `/api/periods/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiPeriodsIdQueryKey = (id?: string,) => {
    return [
    `/api/periods/${id}`
    ] as const;
    }

    
export const getGetApiPeriodsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPeriodsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPeriodsId>>> = ({ signal }) => getApiPeriodsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPeriodsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPeriodsId>>>
export type GetApiPeriodsIdQueryError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>


export function useGetApiPeriodsId<TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPeriodsId>>,
          TError,
          Awaited<ReturnType<typeof getApiPeriodsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPeriodsId<TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPeriodsId>>,
          TError,
          Awaited<ReturnType<typeof getApiPeriodsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPeriodsId<TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPeriodsId<TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPeriodsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetApiPeriodsIdSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPeriodsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPeriodsId>>> = ({ signal }) => getApiPeriodsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPeriodsIdSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPeriodsId>>>
export type GetApiPeriodsIdSuspenseQueryError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>


export function useGetApiPeriodsIdSuspense<TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPeriodsIdSuspense<TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPeriodsIdSuspense<TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPeriodsIdSuspense<TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPeriodsIdSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Actualizar un período existente por ID
 */
export const putApiPeriodsId = (
    id: string,
    putApiPeriodsIdBody: BodyType<PutApiPeriodsIdBody>,
 options?: SecondParameter<typeof apiClient>,) => {
      
      
      return apiClient<PutApiPeriodsId200>(
      {url: `/api/periods/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putApiPeriodsIdBody
    },
      options);
    }
  


export const getPutApiPeriodsIdMutationOptions = <TError = ErrorType<PutApiPeriodsId400 | PutApiPeriodsId401 | PutApiPeriodsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiPeriodsId>>, TError,{id: string;data: BodyType<PutApiPeriodsIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiPeriodsId>>, TError,{id: string;data: BodyType<PutApiPeriodsIdBody>}, TContext> => {

const mutationKey = ['putApiPeriodsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiPeriodsId>>, {id: string;data: BodyType<PutApiPeriodsIdBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiPeriodsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiPeriodsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiPeriodsId>>>
    export type PutApiPeriodsIdMutationBody = BodyType<PutApiPeriodsIdBody>
    export type PutApiPeriodsIdMutationError = ErrorType<PutApiPeriodsId400 | PutApiPeriodsId401 | PutApiPeriodsId500>

    export const usePutApiPeriodsId = <TError = ErrorType<PutApiPeriodsId400 | PutApiPeriodsId401 | PutApiPeriodsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiPeriodsId>>, TError,{id: string;data: BodyType<PutApiPeriodsIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiPeriodsId>>,
        TError,
        {id: string;data: BodyType<PutApiPeriodsIdBody>},
        TContext
      > => {

      const mutationOptions = getPutApiPeriodsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Eliminar un período por ID
 */
export const deleteApiPeriodsId = (
    id: string,
 options?: SecondParameter<typeof apiClient>,) => {
      
      
      return apiClient<DeleteApiPeriodsId200>(
      {url: `/api/periods/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiPeriodsIdMutationOptions = <TError = ErrorType<DeleteApiPeriodsId400 | DeleteApiPeriodsId401 | DeleteApiPeriodsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiPeriodsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiPeriodsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiPeriodsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiPeriodsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiPeriodsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiPeriodsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiPeriodsId>>>
    
    export type DeleteApiPeriodsIdMutationError = ErrorType<DeleteApiPeriodsId400 | DeleteApiPeriodsId401 | DeleteApiPeriodsId500>

    export const useDeleteApiPeriodsId = <TError = ErrorType<DeleteApiPeriodsId400 | DeleteApiPeriodsId401 | DeleteApiPeriodsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiPeriodsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiPeriodsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiPeriodsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    