/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiPeriodsId200,
  DeleteApiPeriodsId400,
  DeleteApiPeriodsId401,
  DeleteApiPeriodsId500,
  GetApiPeriods200,
  GetApiPeriods400,
  GetApiPeriods401,
  GetApiPeriods500,
  GetApiPeriodsId200,
  GetApiPeriodsId400,
  GetApiPeriodsId401,
  GetApiPeriodsId500,
  GetApiPeriodsParams,
  PostApiPeriods200,
  PostApiPeriods400,
  PostApiPeriods401,
  PostApiPeriods500,
  PostApiPeriodsBody,
  PutApiPeriodsId200,
  PutApiPeriodsId400,
  PutApiPeriodsId401,
  PutApiPeriodsId500,
  PutApiPeriodsIdBody
} from '../../domain/models';

import { apiClient } from '../../../lib/api-client/api-client';
import type { ErrorType , BodyType } from '../../../lib/api-client/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Listar todos los períodos con paginación
 */
export type getApiPeriodsResponse200 = {
  data: GetApiPeriods200
  status: 200
}

export type getApiPeriodsResponse400 = {
  data: GetApiPeriods400
  status: 400
}

export type getApiPeriodsResponse401 = {
  data: GetApiPeriods401
  status: 401
}

export type getApiPeriodsResponse500 = {
  data: GetApiPeriods500
  status: 500
}

export type getApiPeriodsResponseSuccess = (getApiPeriodsResponse200) & {
  headers: Headers;
};
export type getApiPeriodsResponseError = (getApiPeriodsResponse400 | getApiPeriodsResponse401 | getApiPeriodsResponse500) & {
  headers: Headers;
};

export type getApiPeriodsResponse = (getApiPeriodsResponseSuccess | getApiPeriodsResponseError)

export const getGetApiPeriodsUrl = (params?: GetApiPeriodsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/periods/?${stringifiedParams}` : `/api/periods/`
}

export const getApiPeriods = async (params?: GetApiPeriodsParams, options?: RequestInit): Promise<getApiPeriodsResponse> => {

  return apiClient<getApiPeriodsResponse>(getGetApiPeriodsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiPeriodsQueryKey = (params?: GetApiPeriodsParams,) => {
    return [
    `/api/periods/`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiPeriodsQueryOptions = <TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>(params?: GetApiPeriodsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPeriodsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPeriods>>> = ({ signal }) => getApiPeriods(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPeriodsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPeriods>>>
export type GetApiPeriodsQueryError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>


export function useGetApiPeriods<TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>(
 params: undefined |  GetApiPeriodsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPeriods>>,
          TError,
          Awaited<ReturnType<typeof getApiPeriods>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPeriods<TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>(
 params?: GetApiPeriodsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPeriods>>,
          TError,
          Awaited<ReturnType<typeof getApiPeriods>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPeriods<TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>(
 params?: GetApiPeriodsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPeriods<TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>(
 params?: GetApiPeriodsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPeriodsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetApiPeriodsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>(params?: GetApiPeriodsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPeriodsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPeriods>>> = ({ signal }) => getApiPeriods(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPeriodsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPeriods>>>
export type GetApiPeriodsSuspenseQueryError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>


export function useGetApiPeriodsSuspense<TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>(
 params: undefined |  GetApiPeriodsParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPeriodsSuspense<TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>(
 params?: GetApiPeriodsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPeriodsSuspense<TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>(
 params?: GetApiPeriodsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPeriodsSuspense<TData = Awaited<ReturnType<typeof getApiPeriods>>, TError = ErrorType<GetApiPeriods400 | GetApiPeriods401 | GetApiPeriods500>>(
 params?: GetApiPeriodsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriods>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPeriodsSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Crear un nuevo período
 */
export type postApiPeriodsResponse200 = {
  data: PostApiPeriods200
  status: 200
}

export type postApiPeriodsResponse400 = {
  data: PostApiPeriods400
  status: 400
}

export type postApiPeriodsResponse401 = {
  data: PostApiPeriods401
  status: 401
}

export type postApiPeriodsResponse500 = {
  data: PostApiPeriods500
  status: 500
}

export type postApiPeriodsResponseSuccess = (postApiPeriodsResponse200) & {
  headers: Headers;
};
export type postApiPeriodsResponseError = (postApiPeriodsResponse400 | postApiPeriodsResponse401 | postApiPeriodsResponse500) & {
  headers: Headers;
};

export type postApiPeriodsResponse = (postApiPeriodsResponseSuccess | postApiPeriodsResponseError)

export const getPostApiPeriodsUrl = () => {




  return `/api/periods/`
}

export const postApiPeriods = async (postApiPeriodsBody: PostApiPeriodsBody, options?: RequestInit): Promise<postApiPeriodsResponse> => {

  return apiClient<postApiPeriodsResponse>(getPostApiPeriodsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiPeriodsBody,)
  }
);}




export const getPostApiPeriodsMutationOptions = <TError = ErrorType<PostApiPeriods400 | PostApiPeriods401 | PostApiPeriods500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPeriods>>, TError,{data: BodyType<PostApiPeriodsBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiPeriods>>, TError,{data: BodyType<PostApiPeriodsBody>}, TContext> => {

const mutationKey = ['postApiPeriods'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiPeriods>>, {data: BodyType<PostApiPeriodsBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiPeriods(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiPeriodsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiPeriods>>>
    export type PostApiPeriodsMutationBody = BodyType<PostApiPeriodsBody>
    export type PostApiPeriodsMutationError = ErrorType<PostApiPeriods400 | PostApiPeriods401 | PostApiPeriods500>

    export const usePostApiPeriods = <TError = ErrorType<PostApiPeriods400 | PostApiPeriods401 | PostApiPeriods500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPeriods>>, TError,{data: BodyType<PostApiPeriodsBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiPeriods>>,
        TError,
        {data: BodyType<PostApiPeriodsBody>},
        TContext
      > => {
      return useMutation(getPostApiPeriodsMutationOptions(options), queryClient);
    }
    /**
 * Obtener detalles de un período por ID
 */
export type getApiPeriodsIdResponse200 = {
  data: GetApiPeriodsId200
  status: 200
}

export type getApiPeriodsIdResponse400 = {
  data: GetApiPeriodsId400
  status: 400
}

export type getApiPeriodsIdResponse401 = {
  data: GetApiPeriodsId401
  status: 401
}

export type getApiPeriodsIdResponse500 = {
  data: GetApiPeriodsId500
  status: 500
}

export type getApiPeriodsIdResponseSuccess = (getApiPeriodsIdResponse200) & {
  headers: Headers;
};
export type getApiPeriodsIdResponseError = (getApiPeriodsIdResponse400 | getApiPeriodsIdResponse401 | getApiPeriodsIdResponse500) & {
  headers: Headers;
};

export type getApiPeriodsIdResponse = (getApiPeriodsIdResponseSuccess | getApiPeriodsIdResponseError)

export const getGetApiPeriodsIdUrl = (id: string,) => {




  return `/api/periods/${id}`
}

export const getApiPeriodsId = async (id: string, options?: RequestInit): Promise<getApiPeriodsIdResponse> => {

  return apiClient<getApiPeriodsIdResponse>(getGetApiPeriodsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiPeriodsIdQueryKey = (id: string,) => {
    return [
    `/api/periods/${id}`
    ] as const;
    }


export const getGetApiPeriodsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPeriodsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPeriodsId>>> = ({ signal }) => getApiPeriodsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPeriodsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPeriodsId>>>
export type GetApiPeriodsIdQueryError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>


export function useGetApiPeriodsId<TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPeriodsId>>,
          TError,
          Awaited<ReturnType<typeof getApiPeriodsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPeriodsId<TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPeriodsId>>,
          TError,
          Awaited<ReturnType<typeof getApiPeriodsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPeriodsId<TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPeriodsId<TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPeriodsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetApiPeriodsIdSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPeriodsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPeriodsId>>> = ({ signal }) => getApiPeriodsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPeriodsIdSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPeriodsId>>>
export type GetApiPeriodsIdSuspenseQueryError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>


export function useGetApiPeriodsIdSuspense<TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPeriodsIdSuspense<TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPeriodsIdSuspense<TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPeriodsIdSuspense<TData = Awaited<ReturnType<typeof getApiPeriodsId>>, TError = ErrorType<GetApiPeriodsId400 | GetApiPeriodsId401 | GetApiPeriodsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPeriodsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPeriodsIdSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Actualizar un período existente por ID
 */
export type putApiPeriodsIdResponse200 = {
  data: PutApiPeriodsId200
  status: 200
}

export type putApiPeriodsIdResponse400 = {
  data: PutApiPeriodsId400
  status: 400
}

export type putApiPeriodsIdResponse401 = {
  data: PutApiPeriodsId401
  status: 401
}

export type putApiPeriodsIdResponse500 = {
  data: PutApiPeriodsId500
  status: 500
}

export type putApiPeriodsIdResponseSuccess = (putApiPeriodsIdResponse200) & {
  headers: Headers;
};
export type putApiPeriodsIdResponseError = (putApiPeriodsIdResponse400 | putApiPeriodsIdResponse401 | putApiPeriodsIdResponse500) & {
  headers: Headers;
};

export type putApiPeriodsIdResponse = (putApiPeriodsIdResponseSuccess | putApiPeriodsIdResponseError)

export const getPutApiPeriodsIdUrl = (id: string,) => {




  return `/api/periods/${id}`
}

export const putApiPeriodsId = async (id: string,
    putApiPeriodsIdBody: PutApiPeriodsIdBody, options?: RequestInit): Promise<putApiPeriodsIdResponse> => {

  return apiClient<putApiPeriodsIdResponse>(getPutApiPeriodsIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putApiPeriodsIdBody,)
  }
);}




export const getPutApiPeriodsIdMutationOptions = <TError = ErrorType<PutApiPeriodsId400 | PutApiPeriodsId401 | PutApiPeriodsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiPeriodsId>>, TError,{id: string;data: BodyType<PutApiPeriodsIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiPeriodsId>>, TError,{id: string;data: BodyType<PutApiPeriodsIdBody>}, TContext> => {

const mutationKey = ['putApiPeriodsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiPeriodsId>>, {id: string;data: BodyType<PutApiPeriodsIdBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiPeriodsId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiPeriodsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiPeriodsId>>>
    export type PutApiPeriodsIdMutationBody = BodyType<PutApiPeriodsIdBody>
    export type PutApiPeriodsIdMutationError = ErrorType<PutApiPeriodsId400 | PutApiPeriodsId401 | PutApiPeriodsId500>

    export const usePutApiPeriodsId = <TError = ErrorType<PutApiPeriodsId400 | PutApiPeriodsId401 | PutApiPeriodsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiPeriodsId>>, TError,{id: string;data: BodyType<PutApiPeriodsIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiPeriodsId>>,
        TError,
        {id: string;data: BodyType<PutApiPeriodsIdBody>},
        TContext
      > => {
      return useMutation(getPutApiPeriodsIdMutationOptions(options), queryClient);
    }
    /**
 * Eliminar un período por ID
 */
export type deleteApiPeriodsIdResponse200 = {
  data: DeleteApiPeriodsId200
  status: 200
}

export type deleteApiPeriodsIdResponse400 = {
  data: DeleteApiPeriodsId400
  status: 400
}

export type deleteApiPeriodsIdResponse401 = {
  data: DeleteApiPeriodsId401
  status: 401
}

export type deleteApiPeriodsIdResponse500 = {
  data: DeleteApiPeriodsId500
  status: 500
}

export type deleteApiPeriodsIdResponseSuccess = (deleteApiPeriodsIdResponse200) & {
  headers: Headers;
};
export type deleteApiPeriodsIdResponseError = (deleteApiPeriodsIdResponse400 | deleteApiPeriodsIdResponse401 | deleteApiPeriodsIdResponse500) & {
  headers: Headers;
};

export type deleteApiPeriodsIdResponse = (deleteApiPeriodsIdResponseSuccess | deleteApiPeriodsIdResponseError)

export const getDeleteApiPeriodsIdUrl = (id: string,) => {




  return `/api/periods/${id}`
}

export const deleteApiPeriodsId = async (id: string, options?: RequestInit): Promise<deleteApiPeriodsIdResponse> => {

  return apiClient<deleteApiPeriodsIdResponse>(getDeleteApiPeriodsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteApiPeriodsIdMutationOptions = <TError = ErrorType<DeleteApiPeriodsId400 | DeleteApiPeriodsId401 | DeleteApiPeriodsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiPeriodsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiPeriodsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiPeriodsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiPeriodsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiPeriodsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiPeriodsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiPeriodsId>>>

    export type DeleteApiPeriodsIdMutationError = ErrorType<DeleteApiPeriodsId400 | DeleteApiPeriodsId401 | DeleteApiPeriodsId500>

    export const useDeleteApiPeriodsId = <TError = ErrorType<DeleteApiPeriodsId400 | DeleteApiPeriodsId401 | DeleteApiPeriodsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiPeriodsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiPeriodsId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiPeriodsIdMutationOptions(options), queryClient);
    }
