/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiAccountsId200,
  DeleteApiAccountsId400,
  DeleteApiAccountsId401,
  DeleteApiAccountsId500,
  GetApiAccounts200,
  GetApiAccounts400,
  GetApiAccounts401,
  GetApiAccounts500,
  GetApiAccountsId200,
  GetApiAccountsId400,
  GetApiAccountsId401,
  GetApiAccountsId500,
  PatchApiAccountsIdDesactivate200,
  PatchApiAccountsIdDesactivate400,
  PatchApiAccountsIdDesactivate401,
  PatchApiAccountsIdDesactivate500,
  PatchApiAccountsIdRestore200,
  PatchApiAccountsIdRestore400,
  PatchApiAccountsIdRestore401,
  PatchApiAccountsIdRestore500,
  PostApiAccounts200,
  PostApiAccounts400,
  PostApiAccounts401,
  PostApiAccounts500,
  PostApiAccountsBody,
  PutApiAccountsId200,
  PutApiAccountsId400,
  PutApiAccountsId401,
  PutApiAccountsId500,
  PutApiAccountsIdBody
} from '../../domain/models';

import { apiClient } from '../../../lib/api-client/api-client';
import type { ErrorType , BodyType } from '../../../lib/api-client/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Listar todas las cuentas con paginación
 */
export const getApiAccounts = (
    
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<GetApiAccounts200>(
      {url: `/api/accounts/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiAccountsQueryKey = () => {
    return [
    `/api/accounts/`
    ] as const;
    }

    
export const getGetApiAccountsQueryOptions = <TData = Awaited<ReturnType<typeof getApiAccounts>>, TError = ErrorType<GetApiAccounts400 | GetApiAccounts401 | GetApiAccounts500>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccounts>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAccountsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAccounts>>> = ({ signal }) => getApiAccounts(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAccounts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAccountsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAccounts>>>
export type GetApiAccountsQueryError = ErrorType<GetApiAccounts400 | GetApiAccounts401 | GetApiAccounts500>


export function useGetApiAccounts<TData = Awaited<ReturnType<typeof getApiAccounts>>, TError = ErrorType<GetApiAccounts400 | GetApiAccounts401 | GetApiAccounts500>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccounts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccounts>>,
          TError,
          Awaited<ReturnType<typeof getApiAccounts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccounts<TData = Awaited<ReturnType<typeof getApiAccounts>>, TError = ErrorType<GetApiAccounts400 | GetApiAccounts401 | GetApiAccounts500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccounts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccounts>>,
          TError,
          Awaited<ReturnType<typeof getApiAccounts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccounts<TData = Awaited<ReturnType<typeof getApiAccounts>>, TError = ErrorType<GetApiAccounts400 | GetApiAccounts401 | GetApiAccounts500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccounts>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAccounts<TData = Awaited<ReturnType<typeof getApiAccounts>>, TError = ErrorType<GetApiAccounts400 | GetApiAccounts401 | GetApiAccounts500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccounts>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAccountsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetApiAccountsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiAccounts>>, TError = ErrorType<GetApiAccounts400 | GetApiAccounts401 | GetApiAccounts500>>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccounts>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAccountsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAccounts>>> = ({ signal }) => getApiAccounts(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccounts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAccountsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAccounts>>>
export type GetApiAccountsSuspenseQueryError = ErrorType<GetApiAccounts400 | GetApiAccounts401 | GetApiAccounts500>


export function useGetApiAccountsSuspense<TData = Awaited<ReturnType<typeof getApiAccounts>>, TError = ErrorType<GetApiAccounts400 | GetApiAccounts401 | GetApiAccounts500>>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccounts>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountsSuspense<TData = Awaited<ReturnType<typeof getApiAccounts>>, TError = ErrorType<GetApiAccounts400 | GetApiAccounts401 | GetApiAccounts500>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccounts>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountsSuspense<TData = Awaited<ReturnType<typeof getApiAccounts>>, TError = ErrorType<GetApiAccounts400 | GetApiAccounts401 | GetApiAccounts500>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccounts>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAccountsSuspense<TData = Awaited<ReturnType<typeof getApiAccounts>>, TError = ErrorType<GetApiAccounts400 | GetApiAccounts401 | GetApiAccounts500>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccounts>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAccountsSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Crear una nueva cuenta
 */
export const postApiAccounts = (
    postApiAccountsBody: BodyType<PostApiAccountsBody>,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<PostApiAccounts200>(
      {url: `/api/accounts/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiAccountsBody, signal
    },
      options);
    }
  


export const getPostApiAccountsMutationOptions = <TError = ErrorType<PostApiAccounts400 | PostApiAccounts401 | PostApiAccounts500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccounts>>, TError,{data: BodyType<PostApiAccountsBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAccounts>>, TError,{data: BodyType<PostApiAccountsBody>}, TContext> => {

const mutationKey = ['postApiAccounts'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAccounts>>, {data: BodyType<PostApiAccountsBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiAccounts(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiAccountsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAccounts>>>
    export type PostApiAccountsMutationBody = BodyType<PostApiAccountsBody>
    export type PostApiAccountsMutationError = ErrorType<PostApiAccounts400 | PostApiAccounts401 | PostApiAccounts500>

    export const usePostApiAccounts = <TError = ErrorType<PostApiAccounts400 | PostApiAccounts401 | PostApiAccounts500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccounts>>, TError,{data: BodyType<PostApiAccountsBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAccounts>>,
        TError,
        {data: BodyType<PostApiAccountsBody>},
        TContext
      > => {

      const mutationOptions = getPostApiAccountsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Obtener detalles de una cuenta por ID
 */
export const getApiAccountsId = (
    id: string,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<GetApiAccountsId200>(
      {url: `/api/accounts/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiAccountsIdQueryKey = (id?: string,) => {
    return [
    `/api/accounts/${id}`
    ] as const;
    }

    
export const getGetApiAccountsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiAccountsId>>, TError = ErrorType<GetApiAccountsId400 | GetApiAccountsId401 | GetApiAccountsId500>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAccountsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAccountsId>>> = ({ signal }) => getApiAccountsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAccountsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAccountsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAccountsId>>>
export type GetApiAccountsIdQueryError = ErrorType<GetApiAccountsId400 | GetApiAccountsId401 | GetApiAccountsId500>


export function useGetApiAccountsId<TData = Awaited<ReturnType<typeof getApiAccountsId>>, TError = ErrorType<GetApiAccountsId400 | GetApiAccountsId401 | GetApiAccountsId500>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccountsId>>,
          TError,
          Awaited<ReturnType<typeof getApiAccountsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountsId<TData = Awaited<ReturnType<typeof getApiAccountsId>>, TError = ErrorType<GetApiAccountsId400 | GetApiAccountsId401 | GetApiAccountsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAccountsId>>,
          TError,
          Awaited<ReturnType<typeof getApiAccountsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountsId<TData = Awaited<ReturnType<typeof getApiAccountsId>>, TError = ErrorType<GetApiAccountsId400 | GetApiAccountsId401 | GetApiAccountsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAccountsId<TData = Awaited<ReturnType<typeof getApiAccountsId>>, TError = ErrorType<GetApiAccountsId400 | GetApiAccountsId401 | GetApiAccountsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAccountsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAccountsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetApiAccountsIdSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiAccountsId>>, TError = ErrorType<GetApiAccountsId400 | GetApiAccountsId401 | GetApiAccountsId500>>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccountsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAccountsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAccountsId>>> = ({ signal }) => getApiAccountsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccountsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAccountsIdSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAccountsId>>>
export type GetApiAccountsIdSuspenseQueryError = ErrorType<GetApiAccountsId400 | GetApiAccountsId401 | GetApiAccountsId500>


export function useGetApiAccountsIdSuspense<TData = Awaited<ReturnType<typeof getApiAccountsId>>, TError = ErrorType<GetApiAccountsId400 | GetApiAccountsId401 | GetApiAccountsId500>>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccountsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountsIdSuspense<TData = Awaited<ReturnType<typeof getApiAccountsId>>, TError = ErrorType<GetApiAccountsId400 | GetApiAccountsId401 | GetApiAccountsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccountsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAccountsIdSuspense<TData = Awaited<ReturnType<typeof getApiAccountsId>>, TError = ErrorType<GetApiAccountsId400 | GetApiAccountsId401 | GetApiAccountsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccountsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAccountsIdSuspense<TData = Awaited<ReturnType<typeof getApiAccountsId>>, TError = ErrorType<GetApiAccountsId400 | GetApiAccountsId401 | GetApiAccountsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAccountsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAccountsIdSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Actualizar una cuenta existente por ID
 */
export const putApiAccountsId = (
    id: string,
    putApiAccountsIdBody: BodyType<PutApiAccountsIdBody>,
 options?: SecondParameter<typeof apiClient>,) => {
      
      
      return apiClient<PutApiAccountsId200>(
      {url: `/api/accounts/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putApiAccountsIdBody
    },
      options);
    }
  


export const getPutApiAccountsIdMutationOptions = <TError = ErrorType<PutApiAccountsId400 | PutApiAccountsId401 | PutApiAccountsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAccountsId>>, TError,{id: string;data: BodyType<PutApiAccountsIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiAccountsId>>, TError,{id: string;data: BodyType<PutApiAccountsIdBody>}, TContext> => {

const mutationKey = ['putApiAccountsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiAccountsId>>, {id: string;data: BodyType<PutApiAccountsIdBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiAccountsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiAccountsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiAccountsId>>>
    export type PutApiAccountsIdMutationBody = BodyType<PutApiAccountsIdBody>
    export type PutApiAccountsIdMutationError = ErrorType<PutApiAccountsId400 | PutApiAccountsId401 | PutApiAccountsId500>

    export const usePutApiAccountsId = <TError = ErrorType<PutApiAccountsId400 | PutApiAccountsId401 | PutApiAccountsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAccountsId>>, TError,{id: string;data: BodyType<PutApiAccountsIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiAccountsId>>,
        TError,
        {id: string;data: BodyType<PutApiAccountsIdBody>},
        TContext
      > => {

      const mutationOptions = getPutApiAccountsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Eliminar una cuenta por ID
 */
export const deleteApiAccountsId = (
    id: string,
 options?: SecondParameter<typeof apiClient>,) => {
      
      
      return apiClient<DeleteApiAccountsId200>(
      {url: `/api/accounts/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiAccountsIdMutationOptions = <TError = ErrorType<DeleteApiAccountsId400 | DeleteApiAccountsId401 | DeleteApiAccountsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAccountsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiAccountsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiAccountsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiAccountsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiAccountsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiAccountsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiAccountsId>>>
    
    export type DeleteApiAccountsIdMutationError = ErrorType<DeleteApiAccountsId400 | DeleteApiAccountsId401 | DeleteApiAccountsId500>

    export const useDeleteApiAccountsId = <TError = ErrorType<DeleteApiAccountsId400 | DeleteApiAccountsId401 | DeleteApiAccountsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAccountsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiAccountsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiAccountsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Eliminar una cuenta por ID
 */
export const patchApiAccountsIdDesactivate = (
    id: string,
 options?: SecondParameter<typeof apiClient>,) => {
      
      
      return apiClient<PatchApiAccountsIdDesactivate200>(
      {url: `/api/accounts/${id}/desactivate`, method: 'PATCH'
    },
      options);
    }
  


export const getPatchApiAccountsIdDesactivateMutationOptions = <TError = ErrorType<PatchApiAccountsIdDesactivate400 | PatchApiAccountsIdDesactivate401 | PatchApiAccountsIdDesactivate500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiAccountsIdDesactivate>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiAccountsIdDesactivate>>, TError,{id: string}, TContext> => {

const mutationKey = ['patchApiAccountsIdDesactivate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiAccountsIdDesactivate>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  patchApiAccountsIdDesactivate(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiAccountsIdDesactivateMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiAccountsIdDesactivate>>>
    
    export type PatchApiAccountsIdDesactivateMutationError = ErrorType<PatchApiAccountsIdDesactivate400 | PatchApiAccountsIdDesactivate401 | PatchApiAccountsIdDesactivate500>

    export const usePatchApiAccountsIdDesactivate = <TError = ErrorType<PatchApiAccountsIdDesactivate400 | PatchApiAccountsIdDesactivate401 | PatchApiAccountsIdDesactivate500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiAccountsIdDesactivate>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiAccountsIdDesactivate>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPatchApiAccountsIdDesactivateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Eliminar una cuenta por ID
 */
export const patchApiAccountsIdRestore = (
    id: string,
 options?: SecondParameter<typeof apiClient>,) => {
      
      
      return apiClient<PatchApiAccountsIdRestore200>(
      {url: `/api/accounts/${id}/restore`, method: 'PATCH'
    },
      options);
    }
  


export const getPatchApiAccountsIdRestoreMutationOptions = <TError = ErrorType<PatchApiAccountsIdRestore400 | PatchApiAccountsIdRestore401 | PatchApiAccountsIdRestore500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiAccountsIdRestore>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiAccountsIdRestore>>, TError,{id: string}, TContext> => {

const mutationKey = ['patchApiAccountsIdRestore'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiAccountsIdRestore>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  patchApiAccountsIdRestore(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PatchApiAccountsIdRestoreMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiAccountsIdRestore>>>
    
    export type PatchApiAccountsIdRestoreMutationError = ErrorType<PatchApiAccountsIdRestore400 | PatchApiAccountsIdRestore401 | PatchApiAccountsIdRestore500>

    export const usePatchApiAccountsIdRestore = <TError = ErrorType<PatchApiAccountsIdRestore400 | PatchApiAccountsIdRestore401 | PatchApiAccountsIdRestore500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiAccountsIdRestore>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiAccountsIdRestore>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPatchApiAccountsIdRestoreMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    