/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiV2CategoriesId200Description } from './deleteApiV2CategoriesId200Description';
import type { DeleteApiV2CategoriesId200GroupId } from './deleteApiV2CategoriesId200GroupId';
import type { DeleteApiV2CategoriesId200DeletedAt } from './deleteApiV2CategoriesId200DeletedAt';

export type DeleteApiV2CategoriesId200 = {
  id: string;
  name: string;
  color: string;
  icon: string;
  description?: DeleteApiV2CategoriesId200Description;
  groupId?: DeleteApiV2CategoriesId200GroupId;
  createdAt: string;
  updatedAt: string;
  deletedAt?: DeleteApiV2CategoriesId200DeletedAt;
};
