/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiV2AppreciationsId200Type } from './deleteApiV2AppreciationsId200Type';
import type { DeleteApiV2AppreciationsId200Badge } from './deleteApiV2AppreciationsId200Badge';

export type DeleteApiV2AppreciationsId200 = {
  id: string;
  name: string;
  type: DeleteApiV2AppreciationsId200Type;
  badge: DeleteApiV2AppreciationsId200Badge;
  balance: number;
  initAmount: number;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
};
