/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiMovementsId200InvestmentBadge } from './deleteApiMovementsId200InvestmentBadge';

export type DeleteApiMovementsId200Investment = {
  id?: string;
  name?: string;
  initAmount?: number;
  endAmount?: number;
  dateInvestment?: string;
  badge?: DeleteApiMovementsId200InvestmentBadge;
  totalReturns?: number;
  totalWithdrawal?: number;
  valorization?: string;
  totalRate?: string;
  createdAt?: string;
  updatedAt?: string;
};
