/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiPlannedPaymentsId200Account } from './deleteApiPlannedPaymentsId200Account';
import type { DeleteApiPlannedPaymentsId200Category } from './deleteApiPlannedPaymentsId200Category';

export type DeleteApiPlannedPaymentsId200 = {
  id: string;
  amount: number;
  startDate: string;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  description?: string | null;
  specificDay: number;
  account: DeleteApiPlannedPaymentsId200Account;
  category: DeleteApiPlannedPaymentsId200Category;
  userId: string;
  createdAt: string;
  updatedAt: string;
};
