/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiPlannedPaymentsId200CategoryDescription } from './deleteApiPlannedPaymentsId200CategoryDescription';
import type { DeleteApiPlannedPaymentsId200CategoryGroupId } from './deleteApiPlannedPaymentsId200CategoryGroupId';
import type { DeleteApiPlannedPaymentsId200CategoryDeletedAt } from './deleteApiPlannedPaymentsId200CategoryDeletedAt';

export type DeleteApiPlannedPaymentsId200Category = {
  id?: string;
  name?: string;
  color?: string;
  icon?: string;
  description?: DeleteApiPlannedPaymentsId200CategoryDescription;
  groupId?: DeleteApiPlannedPaymentsId200CategoryGroupId;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: DeleteApiPlannedPaymentsId200CategoryDeletedAt;
};
