/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiCategoriesId200Description } from './deleteApiCategoriesId200Description';
import type { DeleteApiCategoriesId200GroupId } from './deleteApiCategoriesId200GroupId';
import type { DeleteApiCategoriesId200DeletedAt } from './deleteApiCategoriesId200DeletedAt';

export type DeleteApiCategoriesId200 = {
  id: string;
  name: string;
  color: string;
  icon: string;
  description?: DeleteApiCategoriesId200Description;
  groupId?: DeleteApiCategoriesId200GroupId;
  createdAt: string;
  updatedAt: string;
  deletedAt?: DeleteApiCategoriesId200DeletedAt;
};
