/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiV2AccountsId200Type } from './deleteApiV2AccountsId200Type';
import type { DeleteApiV2AccountsId200Badge } from './deleteApiV2AccountsId200Badge';

export type DeleteApiV2AccountsId200 = {
  id: string;
  name: string;
  type: DeleteApiV2AccountsId200Type;
  badge: DeleteApiV2AccountsId200Badge;
  balance: number;
  initAmount: number;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
};
