/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiPlannedPaymentsId200AccountBadge } from './deleteApiPlannedPaymentsId200AccountBadge';
import type { DeleteApiPlannedPaymentsId200AccountType } from './deleteApiPlannedPaymentsId200AccountType';

export type DeleteApiPlannedPaymentsId200Account = {
  id?: string;
  name?: string;
  description?: string;
  type?: DeleteApiPlannedPaymentsId200AccountType;
  badge?: DeleteApiPlannedPaymentsId200AccountBadge;
  balance?: number;
  initAmount?: number;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: string;
};
