/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiMovementsId200AccountType } from './deleteApiMovementsId200AccountType';
import type { DeleteApiMovementsId200AccountBadge } from './deleteApiMovementsId200AccountBadge';

export type DeleteApiMovementsId200Account = {
  id?: string;
  name?: string;
  description?: string;
  type?: DeleteApiMovementsId200AccountType;
  badge?: DeleteApiMovementsId200AccountBadge;
  balance?: number;
  initAmount?: number;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: string;
};
