/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { DeleteApiAccountsId200Type } from './deleteApiAccountsId200Type';
import type { DeleteApiAccountsId200Badge } from './deleteApiAccountsId200Badge';

export type DeleteApiAccountsId200 = {
  id: string;
  name: string;
  description: string;
  type: DeleteApiAccountsId200Type;
  badge: DeleteApiAccountsId200Badge;
  initAmount: number;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
};
