/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */

export type GetApiBudgetsListYear200ItemYearsItemBadge = {
  id: string;
  name: string;
  code: string;
  symbol: string;
  flag: string;
};
