/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiEventsId200MovementsItemAccount } from './getApiEventsId200MovementsItemAccount';
import type { GetApiEventsId200MovementsItemCategory } from './getApiEventsId200MovementsItemCategory';

export type GetApiEventsId200MovementsItem = {
  amount?: number;
  description?: string;
  datePurchase?: string;
  category?: GetApiEventsId200MovementsItemCategory;
  account?: GetApiEventsId200MovementsItemAccount;
};
