/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */

export type GetApiReportsTypePeriod200Item = {
  categoryId: string;
  category: string;
  amount: number;
  participation: number;
  color: string;
  icon: string;
  symbol: string;
  flag: string;
};
