/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */

export type GetApiEventsId200MovementsItemCategory = {
  name?: string;
  color?: string;
  icon?: string;
};
