/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiCategories200MetaPreviousPage } from './getApiCategories200MetaPreviousPage';
import type { GetApiCategories200MetaNextPage } from './getApiCategories200MetaNextPage';

export type GetApiCategories200Meta = {
  isFirstPage: boolean;
  isLastPage: boolean;
  currentPage: number;
  previousPage: GetApiCategories200MetaPreviousPage;
  nextPage: GetApiCategories200MetaNextPage;
  pageCount: number;
  totalCount: number;
};
