/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV2GroupCategories200MetaPreviousPage } from './getApiV2GroupCategories200MetaPreviousPage';
import type { GetApiV2GroupCategories200MetaNextPage } from './getApiV2GroupCategories200MetaNextPage';

export type GetApiV2GroupCategories200Meta = {
  isFirstPage: boolean;
  isLastPage: boolean;
  currentPage: number;
  previousPage: GetApiV2GroupCategories200MetaPreviousPage;
  nextPage: GetApiV2GroupCategories200MetaNextPage;
  pageCount: number;
  totalCount: number;
};
