/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPeriods200ContentItem } from './getApiPeriods200ContentItem';
import type { GetApiPeriods200Meta } from './getApiPeriods200Meta';

export type GetApiPeriods200 = {
  content: GetApiPeriods200ContentItem[];
  meta: GetApiPeriods200Meta;
};
