/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiPlannedPaymentsId200Account } from './getApiPlannedPaymentsId200Account';
import type { GetApiPlannedPaymentsId200Category } from './getApiPlannedPaymentsId200Category';

export type GetApiPlannedPaymentsId200 = {
  id: string;
  amount: number;
  startDate: string;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  description?: string | null;
  specificDay: number;
  account: GetApiPlannedPaymentsId200Account;
  category: GetApiPlannedPaymentsId200Category;
  userId: string;
  createdAt: string;
  updatedAt: string;
};
