/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMovementsId200CategoryDescription } from './getApiMovementsId200CategoryDescription';
import type { GetApiMovementsId200CategoryGroupId } from './getApiMovementsId200CategoryGroupId';
import type { GetApiMovementsId200CategoryDeletedAt } from './getApiMovementsId200CategoryDeletedAt';

export type GetApiMovementsId200Category = {
  id?: string;
  name?: string;
  color?: string;
  icon?: string;
  description?: GetApiMovementsId200CategoryDescription;
  groupId?: GetApiMovementsId200CategoryGroupId;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: GetApiMovementsId200CategoryDeletedAt;
};
