/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV2Heritages200ContentItem } from './getApiV2Heritages200ContentItem';
import type { GetApiV2Heritages200BalancesItem } from './getApiV2Heritages200BalancesItem';

export type GetApiV2Heritages200 = {
  content: GetApiV2Heritages200ContentItem[];
  balances: GetApiV2Heritages200BalancesItem[];
};
