/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiAccounts200ContentItemType } from './getApiAccounts200ContentItemType';
import type { GetApiAccounts200ContentItemBadge } from './getApiAccounts200ContentItemBadge';

export type GetApiAccounts200ContentItem = {
  id: string;
  name: string;
  description: string;
  type: GetApiAccounts200ContentItemType;
  badge: GetApiAccounts200ContentItemBadge;
  balance: number;
  initAmount: number;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
};
