/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiAccountTypes200ContentItem } from './getApiAccountTypes200ContentItem';
import type { GetApiAccountTypes200Meta } from './getApiAccountTypes200Meta';

export type GetApiAccountTypes200 = {
  content: GetApiAccountTypes200ContentItem[];
  meta: GetApiAccountTypes200Meta;
};
