/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */

export type GetApiReportsHistory200PreviousPeriodItem = {
  code?: string;
  symbol?: string;
  flag?: string;
  date?: string;
  dailyAmount?: number;
  cumulativeBalance?: number;
};
