/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV2Accounts200ContentItemType } from './getApiV2Accounts200ContentItemType';
import type { GetApiV2Accounts200ContentItemBadge } from './getApiV2Accounts200ContentItemBadge';

export type GetApiV2Accounts200ContentItem = {
  id: string;
  name: string;
  description: string;
  type: GetApiV2Accounts200ContentItemType;
  badge: GetApiV2Accounts200ContentItemBadge;
  balance: number;
  initAmount: number;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
};
