/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiEvents200ContentItemBalancesItem } from './getApiEvents200ContentItemBalancesItem';

export type GetApiEvents200ContentItem = {
  id: string;
  name: string;
  endEvent: string;
  type: string;
  createdAt: string;
  updatedAt: string;
  balances: GetApiEvents200ContentItemBalancesItem[];
};
