/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV2AccountTypes200ContentItem } from './getApiV2AccountTypes200ContentItem';
import type { GetApiV2AccountTypes200Meta } from './getApiV2AccountTypes200Meta';

export type GetApiV2AccountTypes200 = {
  content: GetApiV2AccountTypes200ContentItem[];
  meta: GetApiV2AccountTypes200Meta;
};
