/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiAccounts200ContentItem } from './getApiAccounts200ContentItem';
import type { GetApiAccounts200Meta } from './getApiAccounts200Meta';

export type GetApiAccounts200 = {
  content: GetApiAccounts200ContentItem[];
  meta: GetApiAccounts200Meta;
};
