/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiBadges200ContentItem } from './getApiBadges200ContentItem';
import type { GetApiBadges200Meta } from './getApiBadges200Meta';

export type GetApiBadges200 = {
  content: GetApiBadges200ContentItem[];
  meta: GetApiBadges200Meta;
};
