/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV2PlannedPaymentsId200AccountType } from './getApiV2PlannedPaymentsId200AccountType';
import type { GetApiV2PlannedPaymentsId200AccountBadge } from './getApiV2PlannedPaymentsId200AccountBadge';

export type GetApiV2PlannedPaymentsId200Account = {
  id?: string;
  name?: string;
  description?: string;
  type?: GetApiV2PlannedPaymentsId200AccountType;
  badge?: GetApiV2PlannedPaymentsId200AccountBadge;
  balance?: number;
  initAmount?: number;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: string;
};
