/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiAccountsId200Type } from './getApiAccountsId200Type';
import type { GetApiAccountsId200Badge } from './getApiAccountsId200Badge';

export type GetApiAccountsId200 = {
  id: string;
  name: string;
  description: string;
  type: GetApiAccountsId200Type;
  badge: GetApiAccountsId200Badge;
  balance: number;
  initAmount: number;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
};
