/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiHeritages200BalancesItem } from './getApiHeritages200BalancesItem';
import type { GetApiHeritages200ContentItem } from './getApiHeritages200ContentItem';
import type { GetApiHeritages200InvestmentsItem } from './getApiHeritages200InvestmentsItem';

export type GetApiHeritages200 = {
  content: GetApiHeritages200ContentItem[];
  balances: GetApiHeritages200BalancesItem[];
  investments: GetApiHeritages200InvestmentsItem[];
};
