/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMovementsId200TransferOutAccount } from './getApiMovementsId200TransferOutAccount';

export type GetApiMovementsId200TransferOut = {
  id?: string;
  account?: GetApiMovementsId200TransferOutAccount;
  amount?: number;
};
