/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV2ReportsHistory200PreviousPeriodItem = {
  code?: string;
  symbol?: string;
  flag?: string;
  date?: string;
  dailyAmount?: number;
  cumulativeBalance?: number;
};
