/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV2GroupCategories200ContentItem } from './getApiV2GroupCategories200ContentItem';
import type { GetApiV2GroupCategories200Meta } from './getApiV2GroupCategories200Meta';

export type GetApiV2GroupCategories200 = {
  content: GetApiV2GroupCategories200ContentItem[];
  meta: GetApiV2GroupCategories200Meta;
};
