/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMovementsId200Category } from './getApiMovementsId200Category';
import type { GetApiMovementsId200Account } from './getApiMovementsId200Account';
import type { GetApiMovementsId200Event } from './getApiMovementsId200Event';
import type { GetApiMovementsId200Investment } from './getApiMovementsId200Investment';
import type { GetApiMovementsId200TransferOut } from './getApiMovementsId200TransferOut';
import type { GetApiMovementsId200TransferIn } from './getApiMovementsId200TransferIn';

export type GetApiMovementsId200 = {
  id: string;
  description: string;
  amount: number;
  datePurchase: string;
  category: GetApiMovementsId200Category;
  account: GetApiMovementsId200Account;
  event: GetApiMovementsId200Event;
  addWithdrawal: boolean;
  investment: GetApiMovementsId200Investment;
  userId: string;
  createdAt: string;
  updatedAt: string;
  transferOut: GetApiMovementsId200TransferOut;
  transferIn: GetApiMovementsId200TransferIn;
};
