/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiHeritages200ContentItemBadge } from './getApiHeritages200ContentItemBadge';

export type GetApiHeritages200ContentItem = {
  id: string;
  name: string;
  comercialAmount: number;
  legalAmount: number;
  badge: GetApiHeritages200ContentItemBadge;
  year: number;
  createdAt: string;
  updatedAt: string;
};
