/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV2MovementsId200AccountType } from './getApiV2MovementsId200AccountType';
import type { GetApiV2MovementsId200AccountBadge } from './getApiV2MovementsId200AccountBadge';

export type GetApiV2MovementsId200Account = {
  id?: string;
  name?: string;
  description?: string;
  type?: GetApiV2MovementsId200AccountType;
  badge?: GetApiV2MovementsId200AccountBadge;
  balance?: number;
  initAmount?: number;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: string;
};
