/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */

export type GetApiV2HeritagesYear200 = {
  year: number;
  code: string;
  flag: string;
  symbol: string;
  amount: string;
};
