/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV2Heritages200MetaPreviousPage } from './getApiV2Heritages200MetaPreviousPage';
import type { GetApiV2Heritages200MetaNextPage } from './getApiV2Heritages200MetaNextPage';

export type GetApiV2Heritages200Meta = {
  isFirstPage: boolean;
  isLastPage: boolean;
  currentPage: number;
  previousPage: GetApiV2Heritages200MetaPreviousPage;
  nextPage: GetApiV2Heritages200MetaNextPage;
  pageCount: number;
  totalCount: number;
};
