/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV2PlannedPayments200ContentItemEndDate } from './getApiV2PlannedPayments200ContentItemEndDate';
import type { GetApiV2PlannedPayments200ContentItemDescription } from './getApiV2PlannedPayments200ContentItemDescription';
import type { GetApiV2PlannedPayments200ContentItemAccount } from './getApiV2PlannedPayments200ContentItemAccount';
import type { GetApiV2PlannedPayments200ContentItemCategory } from './getApiV2PlannedPayments200ContentItemCategory';

export type GetApiV2PlannedPayments200ContentItem = {
  id: string;
  amount: number;
  startDate: string;
  endDate?: GetApiV2PlannedPayments200ContentItemEndDate;
  description?: GetApiV2PlannedPayments200ContentItemDescription;
  specificDay: number;
  account: GetApiV2PlannedPayments200ContentItemAccount;
  category: GetApiV2PlannedPayments200ContentItemCategory;
  userId: string;
  createdAt: string;
  updatedAt: string;
};
