/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV2Movements200ContentItemCategory } from './getApiV2Movements200ContentItemCategory';
import type { GetApiV2Movements200ContentItemAccount } from './getApiV2Movements200ContentItemAccount';
import type { GetApiV2Movements200ContentItemEvent } from './getApiV2Movements200ContentItemEvent';
import type { GetApiV2Movements200ContentItemInvestment } from './getApiV2Movements200ContentItemInvestment';

export type GetApiV2Movements200ContentItem = {
  id: string;
  description: string;
  amount: number;
  datePurchase: string;
  category: GetApiV2Movements200ContentItemCategory;
  account: GetApiV2Movements200ContentItemAccount;
  event: GetApiV2Movements200ContentItemEvent;
  addWithdrawal: boolean;
  investment: GetApiV2Movements200ContentItemInvestment;
  userId: string;
  createdAt: string;
  updatedAt: string;
};
