/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiAuthProfile200Phone } from './getApiAuthProfile200Phone';
import type { GetApiAuthProfile200PhoneCode } from './getApiAuthProfile200PhoneCode';
import type { GetApiAuthProfile200ConfirmedEmailAt } from './getApiAuthProfile200ConfirmedEmailAt';

export type GetApiAuthProfile200 = {
  email: string;
  name: string;
  phone?: GetApiAuthProfile200Phone;
  phoneCode?: GetApiAuthProfile200PhoneCode;
  confirmedEmailAt?: GetApiAuthProfile200ConfirmedEmailAt;
  badgeId: string;
};
