/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV2EventsId200CategoriesItemCategoriesItem } from './getApiV2EventsId200CategoriesItemCategoriesItem';

export type GetApiV2EventsId200CategoriesItem = {
  badge?: string;
  categories?: GetApiV2EventsId200CategoriesItemCategoriesItem[];
};
