/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV2BudgetsListYear200ItemYearsItem } from './getApiV2BudgetsListYear200ItemYearsItem';

export type GetApiV2BudgetsListYear200Item = {
  years: GetApiV2BudgetsListYear200ItemYearsItem[];
  badge: string;
};
