/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV2Periods200ContentItem } from './getApiV2Periods200ContentItem';
import type { GetApiV2Periods200Meta } from './getApiV2Periods200Meta';

export type GetApiV2Periods200 = {
  content: GetApiV2Periods200ContentItem[];
  meta: GetApiV2Periods200Meta;
};
