/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV2Events200MetaPreviousPage } from './getApiV2Events200MetaPreviousPage';
import type { GetApiV2Events200MetaNextPage } from './getApiV2Events200MetaNextPage';

export type GetApiV2Events200Meta = {
  isFirstPage: boolean;
  isLastPage: boolean;
  currentPage: number;
  previousPage: GetApiV2Events200MetaPreviousPage;
  nextPage: GetApiV2Events200MetaNextPage;
  pageCount: number;
  totalCount: number;
};
