/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */

export type GetApiInvestmentsId200Badge = {
  id?: string;
  code?: string;
  name?: string;
  flag?: string;
  symbol?: string;
  createdAt?: string;
  updatedAt?: string;
};
