/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV2Movements200ContentItemAccountType } from './getApiV2Movements200ContentItemAccountType';
import type { GetApiV2Movements200ContentItemAccountBadge } from './getApiV2Movements200ContentItemAccountBadge';

export type GetApiV2Movements200ContentItemAccount = {
  id?: string;
  name?: string;
  type?: GetApiV2Movements200ContentItemAccountType;
  badge?: GetApiV2Movements200ContentItemAccountBadge;
  balance?: number;
  initAmount?: number;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: string;
};
