/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiMovements200ContentItemCategory } from './getApiMovements200ContentItemCategory';
import type { GetApiMovements200ContentItemAccount } from './getApiMovements200ContentItemAccount';
import type { GetApiMovements200ContentItemEvent } from './getApiMovements200ContentItemEvent';
import type { GetApiMovements200ContentItemInvestment } from './getApiMovements200ContentItemInvestment';

export type GetApiMovements200ContentItem = {
  id: string;
  description: string;
  amount: number;
  datePurchase: string;
  category: GetApiMovements200ContentItemCategory;
  account: GetApiMovements200ContentItemAccount;
  event: GetApiMovements200ContentItemEvent;
  addWithdrawal: boolean;
  investment: GetApiMovements200ContentItemInvestment;
  userId: string;
  createdAt: string;
  updatedAt: string;
};
