/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV2PlannedPayments200ContentItem } from './getApiV2PlannedPayments200ContentItem';
import type { GetApiV2PlannedPayments200Meta } from './getApiV2PlannedPayments200Meta';

export type GetApiV2PlannedPayments200 = {
  content: GetApiV2PlannedPayments200ContentItem[];
  meta: GetApiV2PlannedPayments200Meta;
};
