/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiAccounts200MetaPreviousPage } from './getApiAccounts200MetaPreviousPage';
import type { GetApiAccounts200MetaNextPage } from './getApiAccounts200MetaNextPage';

export type GetApiAccounts200Meta = {
  isFirstPage: boolean;
  isLastPage: boolean;
  currentPage: number;
  previousPage: GetApiAccounts200MetaPreviousPage;
  nextPage: GetApiAccounts200MetaNextPage;
  pageCount: number;
  totalCount: number;
};
