/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { GetApiV2ReportsHistory200CurrentItem } from './getApiV2ReportsHistory200CurrentItem';
import type { GetApiV2ReportsHistory200LastYearItem } from './getApiV2ReportsHistory200LastYearItem';
import type { GetApiV2ReportsHistory200PreviousPeriodItem } from './getApiV2ReportsHistory200PreviousPeriodItem';

export type GetApiV2ReportsHistory200 = {
  current: GetApiV2ReportsHistory200CurrentItem[];
  lastYear: GetApiV2ReportsHistory200LastYearItem[];
  previousPeriod: GetApiV2ReportsHistory200PreviousPeriodItem[];
};
