/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */

export type PostApiEvents200 = {
  id: string;
  name: string;
  endEvent: string;
  type: string;
  createdAt: string;
  updatedAt: string;
};
