/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiBudgets200Badge } from './postApiBudgets200Badge';
import type { PostApiBudgets200Category } from './postApiBudgets200Category';

export type PostApiBudgets200 = {
  id: string;
  year: number;
  badgeId: string;
  amount: number;
  periodId: string;
  categoryId: string;
  badge: PostApiBudgets200Badge;
  category: PostApiBudgets200Category;
  createdAt: string;
  updatedAt: string;
};
