/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV2CategoriesBodyDescription } from './postApiV2CategoriesBodyDescription';
import type { PostApiV2CategoriesBodyGroupId } from './postApiV2CategoriesBodyGroupId';

export type PostApiV2CategoriesBody = {
  name?: string;
  color?: string;
  icon?: string;
  description?: PostApiV2CategoriesBodyDescription;
  groupId?: PostApiV2CategoriesBodyGroupId;
};
