/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiMovements200CategoryDescription } from './postApiMovements200CategoryDescription';
import type { PostApiMovements200CategoryGroupId } from './postApiMovements200CategoryGroupId';
import type { PostApiMovements200CategoryDeletedAt } from './postApiMovements200CategoryDeletedAt';

export type PostApiMovements200Category = {
  id?: string;
  name?: string;
  color?: string;
  icon?: string;
  description?: PostApiMovements200CategoryDescription;
  groupId?: PostApiMovements200CategoryGroupId;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: PostApiMovements200CategoryDeletedAt;
};
