/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiPlannedPayments200AccountBadge } from './postApiPlannedPayments200AccountBadge';
import type { PostApiPlannedPayments200AccountType } from './postApiPlannedPayments200AccountType';

export type PostApiPlannedPayments200Account = {
  id?: string;
  name?: string;
  description?: string;
  type?: PostApiPlannedPayments200AccountType;
  badge?: PostApiPlannedPayments200AccountBadge;
  balance?: number;
  initAmount?: number;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: string;
};
