/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiAuthLogin200AccountsTypeItem } from './postApiAuthLogin200AccountsTypeItem';
import type { PostApiAuthLogin200BadgesItem } from './postApiAuthLogin200BadgesItem';
import type { PostApiAuthLogin200Data } from './postApiAuthLogin200Data';
import type { PostApiAuthLogin200GroupsCategoryItem } from './postApiAuthLogin200GroupsCategoryItem';
import type { PostApiAuthLogin200PeriodsItem } from './postApiAuthLogin200PeriodsItem';

export type PostApiAuthLogin200 = {
  data: PostApiAuthLogin200Data;
  token: string;
  accountsType: PostApiAuthLogin200AccountsTypeItem[];
  periods: PostApiAuthLogin200PeriodsItem[];
  badges: PostApiAuthLogin200BadgesItem[];
  groupsCategory: PostApiAuthLogin200GroupsCategoryItem[];
};
