/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */

export type PostApiInvestmentsBody = {
  name?: string;
  initAmount?: number;
  endAmount?: number;
  dateInvestment?: string;
  badgeId?: string;
  userId?: string;
};
