/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiInvestments200Badge } from './postApiInvestments200Badge';

export type PostApiInvestments200 = {
  id: string;
  name: string;
  initAmount: number;
  endAmount: number;
  dateInvestment: string;
  badge: PostApiInvestments200Badge;
  totalReturns: number;
  totalWithdrawal: number;
  valorization: string;
  totalRate: string;
  createdAt: string;
  updatedAt: string;
};
