/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV2Investments200Badge } from './postApiV2Investments200Badge';

export type PostApiV2Investments200 = {
  id: string;
  name: string;
  initAmount: number;
  endAmount: number;
  dateInvestment: string;
  badge: PostApiV2Investments200Badge;
  totalReturns: number;
  totalWithdrawal: number;
  valorization: string;
  totalRate: string;
  createdAt: string;
  updatedAt: string;
};
