/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV2Movements200CategoryDescription } from './postApiV2Movements200CategoryDescription';
import type { PostApiV2Movements200CategoryGroupId } from './postApiV2Movements200CategoryGroupId';
import type { PostApiV2Movements200CategoryDeletedAt } from './postApiV2Movements200CategoryDeletedAt';

export type PostApiV2Movements200Category = {
  id?: string;
  name?: string;
  color?: string;
  icon?: string;
  description?: PostApiV2Movements200CategoryDescription;
  groupId?: PostApiV2Movements200CategoryGroupId;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: PostApiV2Movements200CategoryDeletedAt;
};
