/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiMovementsBodyEventId } from './postApiMovementsBodyEventId';
import type { PostApiMovementsBodyInvestmentId } from './postApiMovementsBodyInvestmentId';

export type PostApiMovementsBody = {
  description?: string;
  amount?: number;
  type?: string;
  datePurchase?: string;
  categoryId?: string;
  accountId?: string;
  eventId?: PostApiMovementsBodyEventId;
  investmentId?: PostApiMovementsBodyInvestmentId;
  addWithdrawal?: boolean;
  userId?: string;
};
