/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV2Categories200Description } from './postApiV2Categories200Description';
import type { PostApiV2Categories200GroupId } from './postApiV2Categories200GroupId';
import type { PostApiV2Categories200DeletedAt } from './postApiV2Categories200DeletedAt';

export type PostApiV2Categories200 = {
  id: string;
  name: string;
  color: string;
  icon: string;
  description?: PostApiV2Categories200Description;
  groupId?: PostApiV2Categories200GroupId;
  createdAt: string;
  updatedAt: string;
  deletedAt?: PostApiV2Categories200DeletedAt;
};
