/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiPlannedPayments200Account } from './postApiPlannedPayments200Account';
import type { PostApiPlannedPayments200Category } from './postApiPlannedPayments200Category';

export type PostApiPlannedPayments200 = {
  id: string;
  amount: number;
  startDate: string;
  /** @nullable */
  endDate?: string | null;
  /** @nullable */
  description?: string | null;
  specificDay: number;
  account: PostApiPlannedPayments200Account;
  category: PostApiPlannedPayments200Category;
  userId: string;
  createdAt: string;
  updatedAt: string;
};
