/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiCategoriesBodyDescription } from './postApiCategoriesBodyDescription';
import type { PostApiCategoriesBodyGroupId } from './postApiCategoriesBodyGroupId';

export type PostApiCategoriesBody = {
  name?: string;
  color?: string;
  icon?: string;
  description?: PostApiCategoriesBodyDescription;
  groupId?: PostApiCategoriesBodyGroupId;
};
