/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiAuthConfirmEmail200Phone } from './postApiAuthConfirmEmail200Phone';
import type { PostApiAuthConfirmEmail200PhoneCode } from './postApiAuthConfirmEmail200PhoneCode';
import type { PostApiAuthConfirmEmail200ConfirmedEmailAt } from './postApiAuthConfirmEmail200ConfirmedEmailAt';

export type PostApiAuthConfirmEmail200 = {
  email: string;
  name: string;
  phone?: PostApiAuthConfirmEmail200Phone;
  phoneCode?: PostApiAuthConfirmEmail200PhoneCode;
  confirmedEmailAt?: PostApiAuthConfirmEmail200ConfirmedEmailAt;
  transferId: string;
  badgeId: string;
};
