/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PostApiV2Movements200InvestmentBadge } from './postApiV2Movements200InvestmentBadge';

export type PostApiV2Movements200Investment = {
  id?: string;
  name?: string;
  initAmount?: number;
  endAmount?: number;
  badge?: PostApiV2Movements200InvestmentBadge;
  totalReturns?: number;
  totalWithdrawal?: number;
  valorization?: string;
  totalRate?: string;
  createdAt?: string;
  updatedAt?: string;
};
