/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiV2MovementsId200InvestmentBadge } from './putApiV2MovementsId200InvestmentBadge';

export type PutApiV2MovementsId200Investment = {
  id?: string;
  name?: string;
  initAmount?: number;
  endAmount?: number;
  badge?: PutApiV2MovementsId200InvestmentBadge;
  totalReturns?: number;
  totalWithdrawal?: number;
  valorization?: string;
  totalRate?: string;
  createdAt?: string;
  updatedAt?: string;
};
