/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiV2InvestmentsId200Badge } from './putApiV2InvestmentsId200Badge';

export type PutApiV2InvestmentsId200 = {
  id: string;
  name: string;
  initAmount: number;
  endAmount: number;
  dateInvestment: string;
  badge: PutApiV2InvestmentsId200Badge;
  totalReturns: number;
  totalWithdrawal: number;
  valorization: string;
  totalRate: string;
  createdAt: string;
  updatedAt: string;
};
