/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiPlannedPaymentsId200EndDate } from './putApiPlannedPaymentsId200EndDate';
import type { PutApiPlannedPaymentsId200Description } from './putApiPlannedPaymentsId200Description';
import type { PutApiPlannedPaymentsId200Account } from './putApiPlannedPaymentsId200Account';
import type { PutApiPlannedPaymentsId200Category } from './putApiPlannedPaymentsId200Category';

export type PutApiPlannedPaymentsId200 = {
  id: string;
  amount: number;
  startDate: string;
  endDate?: PutApiPlannedPaymentsId200EndDate;
  description?: PutApiPlannedPaymentsId200Description;
  specificDay: number;
  account: PutApiPlannedPaymentsId200Account;
  category: PutApiPlannedPaymentsId200Category;
  userId: string;
  createdAt: string;
  updatedAt: string;
};
