/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiPlannedPaymentsId200CategoryDescription } from './putApiPlannedPaymentsId200CategoryDescription';
import type { PutApiPlannedPaymentsId200CategoryGroupId } from './putApiPlannedPaymentsId200CategoryGroupId';
import type { PutApiPlannedPaymentsId200CategoryDeletedAt } from './putApiPlannedPaymentsId200CategoryDeletedAt';

export type PutApiPlannedPaymentsId200Category = {
  id?: string;
  name?: string;
  color?: string;
  icon?: string;
  description?: PutApiPlannedPaymentsId200CategoryDescription;
  groupId?: PutApiPlannedPaymentsId200CategoryGroupId;
  createdAt?: string;
  updatedAt?: string;
  deletedAt?: PutApiPlannedPaymentsId200CategoryDeletedAt;
};
