/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiV2MovementsIdBodyEventId } from './putApiV2MovementsIdBodyEventId';
import type { PutApiV2MovementsIdBodyInvestmentId } from './putApiV2MovementsIdBodyInvestmentId';

export type PutApiV2MovementsIdBody = {
  description?: string;
  amount?: number;
  type?: string;
  datePurchase?: string;
  categoryId?: string;
  accountId?: string;
  eventId?: PutApiV2MovementsIdBodyEventId;
  investmentId?: PutApiV2MovementsIdBodyInvestmentId;
  addWithdrawal?: boolean;
};
