/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiMovementsId200Account } from './putApiMovementsId200Account';
import type { PutApiMovementsId200Category } from './putApiMovementsId200Category';
import type { PutApiMovementsId200Event } from './putApiMovementsId200Event';
import type { PutApiMovementsId200Investment } from './putApiMovementsId200Investment';

export type PutApiMovementsId200 = {
  id: string;
  description: string;
  amount: number;
  datePurchase: string;
  category: PutApiMovementsId200Category;
  account: PutApiMovementsId200Account;
  event: PutApiMovementsId200Event;
  addWithdrawal: boolean;
  investment: PutApiMovementsId200Investment;
  userId: string;
  createdAt: string;
  updatedAt: string;
};
