/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiV2PlannedPaymentsId200EndDate } from './putApiV2PlannedPaymentsId200EndDate';
import type { PutApiV2PlannedPaymentsId200Description } from './putApiV2PlannedPaymentsId200Description';
import type { PutApiV2PlannedPaymentsId200Account } from './putApiV2PlannedPaymentsId200Account';
import type { PutApiV2PlannedPaymentsId200Category } from './putApiV2PlannedPaymentsId200Category';

export type PutApiV2PlannedPaymentsId200 = {
  id: string;
  amount: number;
  startDate: string;
  endDate?: PutApiV2PlannedPaymentsId200EndDate;
  description?: PutApiV2PlannedPaymentsId200Description;
  specificDay: number;
  account: PutApiV2PlannedPaymentsId200Account;
  category: PutApiV2PlannedPaymentsId200Category;
  userId: string;
  createdAt: string;
  updatedAt: string;
};
