/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiHeritagesId200Badge } from './putApiHeritagesId200Badge';

export type PutApiHeritagesId200 = {
  id: string;
  name: string;
  comercialAmount: number;
  legalAmount: number;
  badge: PutApiHeritagesId200Badge;
  year: number;
  createdAt: string;
  updatedAt: string;
};
