/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import type { PutApiV2HeritagesId200Badge } from './putApiV2HeritagesId200Badge';

export type PutApiV2HeritagesId200 = {
  id: string;
  name: string;
  comercialAmount: number;
  legalAmount: number;
  badge: PutApiV2HeritagesId200Badge;
  year: number;
  userId: string;
  createdAt: string;
  updatedAt: string;
};
