/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiV2GroupCategoriesId200,
  DeleteApiV2GroupCategoriesId400,
  DeleteApiV2GroupCategoriesId401,
  DeleteApiV2GroupCategoriesId500,
  GetApiV2GroupCategories200,
  GetApiV2GroupCategories400,
  GetApiV2GroupCategories401,
  GetApiV2GroupCategories500,
  GetApiV2GroupCategoriesId200,
  GetApiV2GroupCategoriesId400,
  GetApiV2GroupCategoriesId401,
  GetApiV2GroupCategoriesId500,
  PostApiV2GroupCategories200,
  PostApiV2GroupCategories400,
  PostApiV2GroupCategories401,
  PostApiV2GroupCategories500,
  PostApiV2GroupCategoriesBody,
  PutApiV2GroupCategoriesId200,
  PutApiV2GroupCategoriesId400,
  PutApiV2GroupCategoriesId401,
  PutApiV2GroupCategoriesId500,
  PutApiV2GroupCategoriesIdBody
} from '../../domain/models';

import { apiClient } from '../../../lib/api-client/api-client';
import type { ErrorType , BodyType } from '../../../lib/api-client/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Listar todos los grupos de categorías con paginación
 */
export const getApiV2GroupCategories = (
    
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<GetApiV2GroupCategories200>(
      {url: `/api/v2/groupCategories/`, method: 'GET', signal
    },
      options);
    }
  

export const getGetApiV2GroupCategoriesQueryKey = () => {
    return [`/api/v2/groupCategories/`] as const;
    }

    
export const getGetApiV2GroupCategoriesQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError = ErrorType<GetApiV2GroupCategories400 | GetApiV2GroupCategories401 | GetApiV2GroupCategories500>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2GroupCategoriesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2GroupCategories>>> = ({ signal }) => getApiV2GroupCategories(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2GroupCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2GroupCategories>>>
export type GetApiV2GroupCategoriesQueryError = ErrorType<GetApiV2GroupCategories400 | GetApiV2GroupCategories401 | GetApiV2GroupCategories500>


export function useGetApiV2GroupCategories<TData = Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError = ErrorType<GetApiV2GroupCategories400 | GetApiV2GroupCategories401 | GetApiV2GroupCategories500>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2GroupCategories>>,
          TError,
          Awaited<ReturnType<typeof getApiV2GroupCategories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2GroupCategories<TData = Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError = ErrorType<GetApiV2GroupCategories400 | GetApiV2GroupCategories401 | GetApiV2GroupCategories500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2GroupCategories>>,
          TError,
          Awaited<ReturnType<typeof getApiV2GroupCategories>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2GroupCategories<TData = Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError = ErrorType<GetApiV2GroupCategories400 | GetApiV2GroupCategories401 | GetApiV2GroupCategories500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2GroupCategories<TData = Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError = ErrorType<GetApiV2GroupCategories400 | GetApiV2GroupCategories401 | GetApiV2GroupCategories500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2GroupCategoriesQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetApiV2GroupCategoriesSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError = ErrorType<GetApiV2GroupCategories400 | GetApiV2GroupCategories401 | GetApiV2GroupCategories500>>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2GroupCategoriesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2GroupCategories>>> = ({ signal }) => getApiV2GroupCategories(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2GroupCategoriesSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2GroupCategories>>>
export type GetApiV2GroupCategoriesSuspenseQueryError = ErrorType<GetApiV2GroupCategories400 | GetApiV2GroupCategories401 | GetApiV2GroupCategories500>


export function useGetApiV2GroupCategoriesSuspense<TData = Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError = ErrorType<GetApiV2GroupCategories400 | GetApiV2GroupCategories401 | GetApiV2GroupCategories500>>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2GroupCategoriesSuspense<TData = Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError = ErrorType<GetApiV2GroupCategories400 | GetApiV2GroupCategories401 | GetApiV2GroupCategories500>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2GroupCategoriesSuspense<TData = Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError = ErrorType<GetApiV2GroupCategories400 | GetApiV2GroupCategories401 | GetApiV2GroupCategories500>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2GroupCategoriesSuspense<TData = Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError = ErrorType<GetApiV2GroupCategories400 | GetApiV2GroupCategories401 | GetApiV2GroupCategories500>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategories>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2GroupCategoriesSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions , queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Crear un nuevo grupo de categorías
 */
export const postApiV2GroupCategories = (
    postApiV2GroupCategoriesBody: BodyType<PostApiV2GroupCategoriesBody>,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<PostApiV2GroupCategories200>(
      {url: `/api/v2/groupCategories/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV2GroupCategoriesBody, signal
    },
      options);
    }
  


export const getPostApiV2GroupCategoriesMutationOptions = <TError = ErrorType<PostApiV2GroupCategories400 | PostApiV2GroupCategories401 | PostApiV2GroupCategories500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2GroupCategories>>, TError,{data: BodyType<PostApiV2GroupCategoriesBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV2GroupCategories>>, TError,{data: BodyType<PostApiV2GroupCategoriesBody>}, TContext> => {

const mutationKey = ['postApiV2GroupCategories'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV2GroupCategories>>, {data: BodyType<PostApiV2GroupCategoriesBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV2GroupCategories(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV2GroupCategoriesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV2GroupCategories>>>
    export type PostApiV2GroupCategoriesMutationBody = BodyType<PostApiV2GroupCategoriesBody>
    export type PostApiV2GroupCategoriesMutationError = ErrorType<PostApiV2GroupCategories400 | PostApiV2GroupCategories401 | PostApiV2GroupCategories500>

    export const usePostApiV2GroupCategories = <TError = ErrorType<PostApiV2GroupCategories400 | PostApiV2GroupCategories401 | PostApiV2GroupCategories500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2GroupCategories>>, TError,{data: BodyType<PostApiV2GroupCategoriesBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV2GroupCategories>>,
        TError,
        {data: BodyType<PostApiV2GroupCategoriesBody>},
        TContext
      > => {

      const mutationOptions = getPostApiV2GroupCategoriesMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Obtener detalles de un grupo de categorías por ID
 */
export const getApiV2GroupCategoriesId = (
    id: string,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<GetApiV2GroupCategoriesId200>(
      {url: `/api/v2/groupCategories/${id}`, method: 'GET', signal
    },
      options);
    }
  

export const getGetApiV2GroupCategoriesIdQueryKey = (id?: string,) => {
    return [`/api/v2/groupCategories/${id}`] as const;
    }

    
export const getGetApiV2GroupCategoriesIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError = ErrorType<GetApiV2GroupCategoriesId400 | GetApiV2GroupCategoriesId401 | GetApiV2GroupCategoriesId500>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2GroupCategoriesIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>> = ({ signal }) => getApiV2GroupCategoriesId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2GroupCategoriesIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>>
export type GetApiV2GroupCategoriesIdQueryError = ErrorType<GetApiV2GroupCategoriesId400 | GetApiV2GroupCategoriesId401 | GetApiV2GroupCategoriesId500>


export function useGetApiV2GroupCategoriesId<TData = Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError = ErrorType<GetApiV2GroupCategoriesId400 | GetApiV2GroupCategoriesId401 | GetApiV2GroupCategoriesId500>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>,
          TError,
          Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2GroupCategoriesId<TData = Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError = ErrorType<GetApiV2GroupCategoriesId400 | GetApiV2GroupCategoriesId401 | GetApiV2GroupCategoriesId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>,
          TError,
          Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2GroupCategoriesId<TData = Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError = ErrorType<GetApiV2GroupCategoriesId400 | GetApiV2GroupCategoriesId401 | GetApiV2GroupCategoriesId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2GroupCategoriesId<TData = Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError = ErrorType<GetApiV2GroupCategoriesId400 | GetApiV2GroupCategoriesId401 | GetApiV2GroupCategoriesId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2GroupCategoriesIdQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetApiV2GroupCategoriesIdSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError = ErrorType<GetApiV2GroupCategoriesId400 | GetApiV2GroupCategoriesId401 | GetApiV2GroupCategoriesId500>>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2GroupCategoriesIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>> = ({ signal }) => getApiV2GroupCategoriesId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2GroupCategoriesIdSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>>
export type GetApiV2GroupCategoriesIdSuspenseQueryError = ErrorType<GetApiV2GroupCategoriesId400 | GetApiV2GroupCategoriesId401 | GetApiV2GroupCategoriesId500>


export function useGetApiV2GroupCategoriesIdSuspense<TData = Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError = ErrorType<GetApiV2GroupCategoriesId400 | GetApiV2GroupCategoriesId401 | GetApiV2GroupCategoriesId500>>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2GroupCategoriesIdSuspense<TData = Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError = ErrorType<GetApiV2GroupCategoriesId400 | GetApiV2GroupCategoriesId401 | GetApiV2GroupCategoriesId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2GroupCategoriesIdSuspense<TData = Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError = ErrorType<GetApiV2GroupCategoriesId400 | GetApiV2GroupCategoriesId401 | GetApiV2GroupCategoriesId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2GroupCategoriesIdSuspense<TData = Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError = ErrorType<GetApiV2GroupCategoriesId400 | GetApiV2GroupCategoriesId401 | GetApiV2GroupCategoriesId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2GroupCategoriesId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2GroupCategoriesIdSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions , queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Actualizar un grupo de categorías existente por ID
 */
export const putApiV2GroupCategoriesId = (
    id: string,
    putApiV2GroupCategoriesIdBody: BodyType<PutApiV2GroupCategoriesIdBody>,
 options?: SecondParameter<typeof apiClient>,) => {
      
      
      return apiClient<PutApiV2GroupCategoriesId200>(
      {url: `/api/v2/groupCategories/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putApiV2GroupCategoriesIdBody
    },
      options);
    }
  


export const getPutApiV2GroupCategoriesIdMutationOptions = <TError = ErrorType<PutApiV2GroupCategoriesId400 | PutApiV2GroupCategoriesId401 | PutApiV2GroupCategoriesId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV2GroupCategoriesId>>, TError,{id: string;data: BodyType<PutApiV2GroupCategoriesIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV2GroupCategoriesId>>, TError,{id: string;data: BodyType<PutApiV2GroupCategoriesIdBody>}, TContext> => {

const mutationKey = ['putApiV2GroupCategoriesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV2GroupCategoriesId>>, {id: string;data: BodyType<PutApiV2GroupCategoriesIdBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV2GroupCategoriesId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV2GroupCategoriesIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV2GroupCategoriesId>>>
    export type PutApiV2GroupCategoriesIdMutationBody = BodyType<PutApiV2GroupCategoriesIdBody>
    export type PutApiV2GroupCategoriesIdMutationError = ErrorType<PutApiV2GroupCategoriesId400 | PutApiV2GroupCategoriesId401 | PutApiV2GroupCategoriesId500>

    export const usePutApiV2GroupCategoriesId = <TError = ErrorType<PutApiV2GroupCategoriesId400 | PutApiV2GroupCategoriesId401 | PutApiV2GroupCategoriesId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV2GroupCategoriesId>>, TError,{id: string;data: BodyType<PutApiV2GroupCategoriesIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV2GroupCategoriesId>>,
        TError,
        {id: string;data: BodyType<PutApiV2GroupCategoriesIdBody>},
        TContext
      > => {

      const mutationOptions = getPutApiV2GroupCategoriesIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Eliminar un grupo de categorías por ID
 */
export const deleteApiV2GroupCategoriesId = (
    id: string,
 options?: SecondParameter<typeof apiClient>,) => {
      
      
      return apiClient<DeleteApiV2GroupCategoriesId200>(
      {url: `/api/v2/groupCategories/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV2GroupCategoriesIdMutationOptions = <TError = ErrorType<DeleteApiV2GroupCategoriesId400 | DeleteApiV2GroupCategoriesId401 | DeleteApiV2GroupCategoriesId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV2GroupCategoriesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV2GroupCategoriesId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV2GroupCategoriesId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV2GroupCategoriesId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV2GroupCategoriesId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV2GroupCategoriesIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV2GroupCategoriesId>>>
    
    export type DeleteApiV2GroupCategoriesIdMutationError = ErrorType<DeleteApiV2GroupCategoriesId400 | DeleteApiV2GroupCategoriesId401 | DeleteApiV2GroupCategoriesId500>

    export const useDeleteApiV2GroupCategoriesId = <TError = ErrorType<DeleteApiV2GroupCategoriesId400 | DeleteApiV2GroupCategoriesId401 | DeleteApiV2GroupCategoriesId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV2GroupCategoriesId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV2GroupCategoriesId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV2GroupCategoriesIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    