/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiPlannedPaymentsId200,
  DeleteApiPlannedPaymentsId400,
  DeleteApiPlannedPaymentsId401,
  DeleteApiPlannedPaymentsId500,
  GetApiPlannedPayments200,
  GetApiPlannedPayments400,
  GetApiPlannedPayments401,
  GetApiPlannedPayments500,
  GetApiPlannedPaymentsId200,
  GetApiPlannedPaymentsId400,
  GetApiPlannedPaymentsId401,
  GetApiPlannedPaymentsId500,
  GetApiPlannedPaymentsParams,
  PostApiPlannedPayments200,
  PostApiPlannedPayments400,
  PostApiPlannedPayments401,
  PostApiPlannedPayments500,
  PostApiPlannedPaymentsBody,
  PutApiPlannedPaymentsId200,
  PutApiPlannedPaymentsId400,
  PutApiPlannedPaymentsId401,
  PutApiPlannedPaymentsId500,
  PutApiPlannedPaymentsIdBody
} from '../../domain/models';

import { apiClient } from '../../../lib/api-client/api-client';
import type { ErrorType , BodyType } from '../../../lib/api-client/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Listar todos los pagos planificados con paginación
 */
export type getApiPlannedPaymentsResponse200 = {
  data: GetApiPlannedPayments200
  status: 200
}

export type getApiPlannedPaymentsResponse400 = {
  data: GetApiPlannedPayments400
  status: 400
}

export type getApiPlannedPaymentsResponse401 = {
  data: GetApiPlannedPayments401
  status: 401
}

export type getApiPlannedPaymentsResponse500 = {
  data: GetApiPlannedPayments500
  status: 500
}

export type getApiPlannedPaymentsResponseSuccess = (getApiPlannedPaymentsResponse200) & {
  headers: Headers;
};
export type getApiPlannedPaymentsResponseError = (getApiPlannedPaymentsResponse400 | getApiPlannedPaymentsResponse401 | getApiPlannedPaymentsResponse500) & {
  headers: Headers;
};

export type getApiPlannedPaymentsResponse = (getApiPlannedPaymentsResponseSuccess | getApiPlannedPaymentsResponseError)

export const getGetApiPlannedPaymentsUrl = (params?: GetApiPlannedPaymentsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/plannedPayments/?${stringifiedParams}` : `/api/plannedPayments/`
}

export const getApiPlannedPayments = async (params?: GetApiPlannedPaymentsParams, options?: RequestInit): Promise<getApiPlannedPaymentsResponse> => {

  return apiClient<getApiPlannedPaymentsResponse>(getGetApiPlannedPaymentsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiPlannedPaymentsQueryKey = (params?: GetApiPlannedPaymentsParams,) => {
    return [
    `/api/plannedPayments/`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiPlannedPaymentsQueryOptions = <TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>(params?: GetApiPlannedPaymentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPlannedPaymentsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPlannedPayments>>> = ({ signal }) => getApiPlannedPayments(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPlannedPaymentsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPlannedPayments>>>
export type GetApiPlannedPaymentsQueryError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>


export function useGetApiPlannedPayments<TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>(
 params: undefined |  GetApiPlannedPaymentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPlannedPayments>>,
          TError,
          Awaited<ReturnType<typeof getApiPlannedPayments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPlannedPayments<TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>(
 params?: GetApiPlannedPaymentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPlannedPayments>>,
          TError,
          Awaited<ReturnType<typeof getApiPlannedPayments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPlannedPayments<TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>(
 params?: GetApiPlannedPaymentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPlannedPayments<TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>(
 params?: GetApiPlannedPaymentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPlannedPaymentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetApiPlannedPaymentsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>(params?: GetApiPlannedPaymentsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPlannedPaymentsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPlannedPayments>>> = ({ signal }) => getApiPlannedPayments(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPlannedPaymentsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPlannedPayments>>>
export type GetApiPlannedPaymentsSuspenseQueryError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>


export function useGetApiPlannedPaymentsSuspense<TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>(
 params: undefined |  GetApiPlannedPaymentsParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPlannedPaymentsSuspense<TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>(
 params?: GetApiPlannedPaymentsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPlannedPaymentsSuspense<TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>(
 params?: GetApiPlannedPaymentsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPlannedPaymentsSuspense<TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>(
 params?: GetApiPlannedPaymentsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPlannedPaymentsSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Crear un nuevo pago planificado
 */
export type postApiPlannedPaymentsResponse200 = {
  data: PostApiPlannedPayments200
  status: 200
}

export type postApiPlannedPaymentsResponse400 = {
  data: PostApiPlannedPayments400
  status: 400
}

export type postApiPlannedPaymentsResponse401 = {
  data: PostApiPlannedPayments401
  status: 401
}

export type postApiPlannedPaymentsResponse500 = {
  data: PostApiPlannedPayments500
  status: 500
}

export type postApiPlannedPaymentsResponseSuccess = (postApiPlannedPaymentsResponse200) & {
  headers: Headers;
};
export type postApiPlannedPaymentsResponseError = (postApiPlannedPaymentsResponse400 | postApiPlannedPaymentsResponse401 | postApiPlannedPaymentsResponse500) & {
  headers: Headers;
};

export type postApiPlannedPaymentsResponse = (postApiPlannedPaymentsResponseSuccess | postApiPlannedPaymentsResponseError)

export const getPostApiPlannedPaymentsUrl = () => {




  return `/api/plannedPayments/`
}

export const postApiPlannedPayments = async (postApiPlannedPaymentsBody: PostApiPlannedPaymentsBody, options?: RequestInit): Promise<postApiPlannedPaymentsResponse> => {

  return apiClient<postApiPlannedPaymentsResponse>(getPostApiPlannedPaymentsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiPlannedPaymentsBody,)
  }
);}




export const getPostApiPlannedPaymentsMutationOptions = <TError = ErrorType<PostApiPlannedPayments400 | PostApiPlannedPayments401 | PostApiPlannedPayments500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPlannedPayments>>, TError,{data: BodyType<PostApiPlannedPaymentsBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiPlannedPayments>>, TError,{data: BodyType<PostApiPlannedPaymentsBody>}, TContext> => {

const mutationKey = ['postApiPlannedPayments'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiPlannedPayments>>, {data: BodyType<PostApiPlannedPaymentsBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiPlannedPayments(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiPlannedPaymentsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiPlannedPayments>>>
    export type PostApiPlannedPaymentsMutationBody = BodyType<PostApiPlannedPaymentsBody>
    export type PostApiPlannedPaymentsMutationError = ErrorType<PostApiPlannedPayments400 | PostApiPlannedPayments401 | PostApiPlannedPayments500>

    export const usePostApiPlannedPayments = <TError = ErrorType<PostApiPlannedPayments400 | PostApiPlannedPayments401 | PostApiPlannedPayments500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPlannedPayments>>, TError,{data: BodyType<PostApiPlannedPaymentsBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiPlannedPayments>>,
        TError,
        {data: BodyType<PostApiPlannedPaymentsBody>},
        TContext
      > => {
      return useMutation(getPostApiPlannedPaymentsMutationOptions(options), queryClient);
    }
    /**
 * Obtener detalles de un pago planificado por ID
 */
export type getApiPlannedPaymentsIdResponse200 = {
  data: GetApiPlannedPaymentsId200
  status: 200
}

export type getApiPlannedPaymentsIdResponse400 = {
  data: GetApiPlannedPaymentsId400
  status: 400
}

export type getApiPlannedPaymentsIdResponse401 = {
  data: GetApiPlannedPaymentsId401
  status: 401
}

export type getApiPlannedPaymentsIdResponse500 = {
  data: GetApiPlannedPaymentsId500
  status: 500
}

export type getApiPlannedPaymentsIdResponseSuccess = (getApiPlannedPaymentsIdResponse200) & {
  headers: Headers;
};
export type getApiPlannedPaymentsIdResponseError = (getApiPlannedPaymentsIdResponse400 | getApiPlannedPaymentsIdResponse401 | getApiPlannedPaymentsIdResponse500) & {
  headers: Headers;
};

export type getApiPlannedPaymentsIdResponse = (getApiPlannedPaymentsIdResponseSuccess | getApiPlannedPaymentsIdResponseError)

export const getGetApiPlannedPaymentsIdUrl = (id: string,) => {




  return `/api/plannedPayments/${id}`
}

export const getApiPlannedPaymentsId = async (id: string, options?: RequestInit): Promise<getApiPlannedPaymentsIdResponse> => {

  return apiClient<getApiPlannedPaymentsIdResponse>(getGetApiPlannedPaymentsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiPlannedPaymentsIdQueryKey = (id: string,) => {
    return [
    `/api/plannedPayments/${id}`
    ] as const;
    }


export const getGetApiPlannedPaymentsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPlannedPaymentsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>> = ({ signal }) => getApiPlannedPaymentsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPlannedPaymentsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>>
export type GetApiPlannedPaymentsIdQueryError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>


export function useGetApiPlannedPaymentsId<TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPlannedPaymentsId>>,
          TError,
          Awaited<ReturnType<typeof getApiPlannedPaymentsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPlannedPaymentsId<TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPlannedPaymentsId>>,
          TError,
          Awaited<ReturnType<typeof getApiPlannedPaymentsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPlannedPaymentsId<TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPlannedPaymentsId<TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPlannedPaymentsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetApiPlannedPaymentsIdSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPlannedPaymentsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>> = ({ signal }) => getApiPlannedPaymentsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPlannedPaymentsIdSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>>
export type GetApiPlannedPaymentsIdSuspenseQueryError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>


export function useGetApiPlannedPaymentsIdSuspense<TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPlannedPaymentsIdSuspense<TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPlannedPaymentsIdSuspense<TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPlannedPaymentsIdSuspense<TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPlannedPaymentsIdSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Actualizar un pago planificado existente por ID
 */
export type putApiPlannedPaymentsIdResponse200 = {
  data: PutApiPlannedPaymentsId200
  status: 200
}

export type putApiPlannedPaymentsIdResponse400 = {
  data: PutApiPlannedPaymentsId400
  status: 400
}

export type putApiPlannedPaymentsIdResponse401 = {
  data: PutApiPlannedPaymentsId401
  status: 401
}

export type putApiPlannedPaymentsIdResponse500 = {
  data: PutApiPlannedPaymentsId500
  status: 500
}

export type putApiPlannedPaymentsIdResponseSuccess = (putApiPlannedPaymentsIdResponse200) & {
  headers: Headers;
};
export type putApiPlannedPaymentsIdResponseError = (putApiPlannedPaymentsIdResponse400 | putApiPlannedPaymentsIdResponse401 | putApiPlannedPaymentsIdResponse500) & {
  headers: Headers;
};

export type putApiPlannedPaymentsIdResponse = (putApiPlannedPaymentsIdResponseSuccess | putApiPlannedPaymentsIdResponseError)

export const getPutApiPlannedPaymentsIdUrl = (id: string,) => {




  return `/api/plannedPayments/${id}`
}

export const putApiPlannedPaymentsId = async (id: string,
    putApiPlannedPaymentsIdBody: PutApiPlannedPaymentsIdBody, options?: RequestInit): Promise<putApiPlannedPaymentsIdResponse> => {

  return apiClient<putApiPlannedPaymentsIdResponse>(getPutApiPlannedPaymentsIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putApiPlannedPaymentsIdBody,)
  }
);}




export const getPutApiPlannedPaymentsIdMutationOptions = <TError = ErrorType<PutApiPlannedPaymentsId400 | PutApiPlannedPaymentsId401 | PutApiPlannedPaymentsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiPlannedPaymentsId>>, TError,{id: string;data: BodyType<PutApiPlannedPaymentsIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiPlannedPaymentsId>>, TError,{id: string;data: BodyType<PutApiPlannedPaymentsIdBody>}, TContext> => {

const mutationKey = ['putApiPlannedPaymentsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiPlannedPaymentsId>>, {id: string;data: BodyType<PutApiPlannedPaymentsIdBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiPlannedPaymentsId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiPlannedPaymentsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiPlannedPaymentsId>>>
    export type PutApiPlannedPaymentsIdMutationBody = BodyType<PutApiPlannedPaymentsIdBody>
    export type PutApiPlannedPaymentsIdMutationError = ErrorType<PutApiPlannedPaymentsId400 | PutApiPlannedPaymentsId401 | PutApiPlannedPaymentsId500>

    export const usePutApiPlannedPaymentsId = <TError = ErrorType<PutApiPlannedPaymentsId400 | PutApiPlannedPaymentsId401 | PutApiPlannedPaymentsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiPlannedPaymentsId>>, TError,{id: string;data: BodyType<PutApiPlannedPaymentsIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiPlannedPaymentsId>>,
        TError,
        {id: string;data: BodyType<PutApiPlannedPaymentsIdBody>},
        TContext
      > => {
      return useMutation(getPutApiPlannedPaymentsIdMutationOptions(options), queryClient);
    }
    /**
 * Eliminar un pago planificado por ID
 */
export type deleteApiPlannedPaymentsIdResponse200 = {
  data: DeleteApiPlannedPaymentsId200
  status: 200
}

export type deleteApiPlannedPaymentsIdResponse400 = {
  data: DeleteApiPlannedPaymentsId400
  status: 400
}

export type deleteApiPlannedPaymentsIdResponse401 = {
  data: DeleteApiPlannedPaymentsId401
  status: 401
}

export type deleteApiPlannedPaymentsIdResponse500 = {
  data: DeleteApiPlannedPaymentsId500
  status: 500
}

export type deleteApiPlannedPaymentsIdResponseSuccess = (deleteApiPlannedPaymentsIdResponse200) & {
  headers: Headers;
};
export type deleteApiPlannedPaymentsIdResponseError = (deleteApiPlannedPaymentsIdResponse400 | deleteApiPlannedPaymentsIdResponse401 | deleteApiPlannedPaymentsIdResponse500) & {
  headers: Headers;
};

export type deleteApiPlannedPaymentsIdResponse = (deleteApiPlannedPaymentsIdResponseSuccess | deleteApiPlannedPaymentsIdResponseError)

export const getDeleteApiPlannedPaymentsIdUrl = (id: string,) => {




  return `/api/plannedPayments/${id}`
}

export const deleteApiPlannedPaymentsId = async (id: string, options?: RequestInit): Promise<deleteApiPlannedPaymentsIdResponse> => {

  return apiClient<deleteApiPlannedPaymentsIdResponse>(getDeleteApiPlannedPaymentsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteApiPlannedPaymentsIdMutationOptions = <TError = ErrorType<DeleteApiPlannedPaymentsId400 | DeleteApiPlannedPaymentsId401 | DeleteApiPlannedPaymentsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiPlannedPaymentsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiPlannedPaymentsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiPlannedPaymentsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiPlannedPaymentsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiPlannedPaymentsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiPlannedPaymentsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiPlannedPaymentsId>>>

    export type DeleteApiPlannedPaymentsIdMutationError = ErrorType<DeleteApiPlannedPaymentsId400 | DeleteApiPlannedPaymentsId401 | DeleteApiPlannedPaymentsId500>

    export const useDeleteApiPlannedPaymentsId = <TError = ErrorType<DeleteApiPlannedPaymentsId400 | DeleteApiPlannedPaymentsId401 | DeleteApiPlannedPaymentsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiPlannedPaymentsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiPlannedPaymentsId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiPlannedPaymentsIdMutationOptions(options), queryClient);
    }
