/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiV2PlannedPaymentsId200,
  DeleteApiV2PlannedPaymentsId400,
  DeleteApiV2PlannedPaymentsId401,
  DeleteApiV2PlannedPaymentsId500,
  GetApiV2PlannedPayments200,
  GetApiV2PlannedPayments400,
  GetApiV2PlannedPayments401,
  GetApiV2PlannedPayments500,
  GetApiV2PlannedPaymentsId200,
  GetApiV2PlannedPaymentsId400,
  GetApiV2PlannedPaymentsId401,
  GetApiV2PlannedPaymentsId500,
  PostApiV2PlannedPayments200,
  PostApiV2PlannedPayments400,
  PostApiV2PlannedPayments401,
  PostApiV2PlannedPayments500,
  PostApiV2PlannedPaymentsBody,
  PutApiV2PlannedPaymentsId200,
  PutApiV2PlannedPaymentsId400,
  PutApiV2PlannedPaymentsId401,
  PutApiV2PlannedPaymentsId500,
  PutApiV2PlannedPaymentsIdBody
} from '../../domain/models';

import { apiClient } from '../../../lib/api-client/api-client';
import type { ErrorType , BodyType } from '../../../lib/api-client/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Listar todos los pagos planificados con paginación
 */
export const getApiV2PlannedPayments = (
    
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<GetApiV2PlannedPayments200>(
      {url: `/api/v2/plannedPayments/`, method: 'GET', signal
    },
      options);
    }
  

export const getGetApiV2PlannedPaymentsQueryKey = () => {
    return [`/api/v2/plannedPayments/`] as const;
    }

    
export const getGetApiV2PlannedPaymentsQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError = ErrorType<GetApiV2PlannedPayments400 | GetApiV2PlannedPayments401 | GetApiV2PlannedPayments500>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2PlannedPaymentsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2PlannedPayments>>> = ({ signal }) => getApiV2PlannedPayments(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2PlannedPaymentsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2PlannedPayments>>>
export type GetApiV2PlannedPaymentsQueryError = ErrorType<GetApiV2PlannedPayments400 | GetApiV2PlannedPayments401 | GetApiV2PlannedPayments500>


export function useGetApiV2PlannedPayments<TData = Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError = ErrorType<GetApiV2PlannedPayments400 | GetApiV2PlannedPayments401 | GetApiV2PlannedPayments500>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2PlannedPayments>>,
          TError,
          Awaited<ReturnType<typeof getApiV2PlannedPayments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2PlannedPayments<TData = Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError = ErrorType<GetApiV2PlannedPayments400 | GetApiV2PlannedPayments401 | GetApiV2PlannedPayments500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2PlannedPayments>>,
          TError,
          Awaited<ReturnType<typeof getApiV2PlannedPayments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2PlannedPayments<TData = Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError = ErrorType<GetApiV2PlannedPayments400 | GetApiV2PlannedPayments401 | GetApiV2PlannedPayments500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2PlannedPayments<TData = Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError = ErrorType<GetApiV2PlannedPayments400 | GetApiV2PlannedPayments401 | GetApiV2PlannedPayments500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2PlannedPaymentsQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetApiV2PlannedPaymentsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError = ErrorType<GetApiV2PlannedPayments400 | GetApiV2PlannedPayments401 | GetApiV2PlannedPayments500>>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2PlannedPaymentsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2PlannedPayments>>> = ({ signal }) => getApiV2PlannedPayments(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2PlannedPaymentsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2PlannedPayments>>>
export type GetApiV2PlannedPaymentsSuspenseQueryError = ErrorType<GetApiV2PlannedPayments400 | GetApiV2PlannedPayments401 | GetApiV2PlannedPayments500>


export function useGetApiV2PlannedPaymentsSuspense<TData = Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError = ErrorType<GetApiV2PlannedPayments400 | GetApiV2PlannedPayments401 | GetApiV2PlannedPayments500>>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2PlannedPaymentsSuspense<TData = Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError = ErrorType<GetApiV2PlannedPayments400 | GetApiV2PlannedPayments401 | GetApiV2PlannedPayments500>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2PlannedPaymentsSuspense<TData = Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError = ErrorType<GetApiV2PlannedPayments400 | GetApiV2PlannedPayments401 | GetApiV2PlannedPayments500>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2PlannedPaymentsSuspense<TData = Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError = ErrorType<GetApiV2PlannedPayments400 | GetApiV2PlannedPayments401 | GetApiV2PlannedPayments500>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2PlannedPaymentsSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions , queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Crear un nuevo pago planificado
 */
export const postApiV2PlannedPayments = (
    postApiV2PlannedPaymentsBody: BodyType<PostApiV2PlannedPaymentsBody>,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<PostApiV2PlannedPayments200>(
      {url: `/api/v2/plannedPayments/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiV2PlannedPaymentsBody, signal
    },
      options);
    }
  


export const getPostApiV2PlannedPaymentsMutationOptions = <TError = ErrorType<PostApiV2PlannedPayments400 | PostApiV2PlannedPayments401 | PostApiV2PlannedPayments500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2PlannedPayments>>, TError,{data: BodyType<PostApiV2PlannedPaymentsBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiV2PlannedPayments>>, TError,{data: BodyType<PostApiV2PlannedPaymentsBody>}, TContext> => {

const mutationKey = ['postApiV2PlannedPayments'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiV2PlannedPayments>>, {data: BodyType<PostApiV2PlannedPaymentsBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiV2PlannedPayments(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiV2PlannedPaymentsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiV2PlannedPayments>>>
    export type PostApiV2PlannedPaymentsMutationBody = BodyType<PostApiV2PlannedPaymentsBody>
    export type PostApiV2PlannedPaymentsMutationError = ErrorType<PostApiV2PlannedPayments400 | PostApiV2PlannedPayments401 | PostApiV2PlannedPayments500>

    export const usePostApiV2PlannedPayments = <TError = ErrorType<PostApiV2PlannedPayments400 | PostApiV2PlannedPayments401 | PostApiV2PlannedPayments500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiV2PlannedPayments>>, TError,{data: BodyType<PostApiV2PlannedPaymentsBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiV2PlannedPayments>>,
        TError,
        {data: BodyType<PostApiV2PlannedPaymentsBody>},
        TContext
      > => {

      const mutationOptions = getPostApiV2PlannedPaymentsMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Obtener detalles de un pago planificado por ID
 */
export const getApiV2PlannedPaymentsId = (
    id: string,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<GetApiV2PlannedPaymentsId200>(
      {url: `/api/v2/plannedPayments/${id}`, method: 'GET', signal
    },
      options);
    }
  

export const getGetApiV2PlannedPaymentsIdQueryKey = (id?: string,) => {
    return [`/api/v2/plannedPayments/${id}`] as const;
    }

    
export const getGetApiV2PlannedPaymentsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError = ErrorType<GetApiV2PlannedPaymentsId400 | GetApiV2PlannedPaymentsId401 | GetApiV2PlannedPaymentsId500>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2PlannedPaymentsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>> = ({ signal }) => getApiV2PlannedPaymentsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2PlannedPaymentsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>>
export type GetApiV2PlannedPaymentsIdQueryError = ErrorType<GetApiV2PlannedPaymentsId400 | GetApiV2PlannedPaymentsId401 | GetApiV2PlannedPaymentsId500>


export function useGetApiV2PlannedPaymentsId<TData = Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError = ErrorType<GetApiV2PlannedPaymentsId400 | GetApiV2PlannedPaymentsId401 | GetApiV2PlannedPaymentsId500>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2PlannedPaymentsId<TData = Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError = ErrorType<GetApiV2PlannedPaymentsId400 | GetApiV2PlannedPaymentsId401 | GetApiV2PlannedPaymentsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>,
          TError,
          Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2PlannedPaymentsId<TData = Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError = ErrorType<GetApiV2PlannedPaymentsId400 | GetApiV2PlannedPaymentsId401 | GetApiV2PlannedPaymentsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2PlannedPaymentsId<TData = Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError = ErrorType<GetApiV2PlannedPaymentsId400 | GetApiV2PlannedPaymentsId401 | GetApiV2PlannedPaymentsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2PlannedPaymentsIdQueryOptions(id,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetApiV2PlannedPaymentsIdSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError = ErrorType<GetApiV2PlannedPaymentsId400 | GetApiV2PlannedPaymentsId401 | GetApiV2PlannedPaymentsId500>>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiV2PlannedPaymentsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>> = ({ signal }) => getApiV2PlannedPaymentsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiV2PlannedPaymentsIdSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>>
export type GetApiV2PlannedPaymentsIdSuspenseQueryError = ErrorType<GetApiV2PlannedPaymentsId400 | GetApiV2PlannedPaymentsId401 | GetApiV2PlannedPaymentsId500>


export function useGetApiV2PlannedPaymentsIdSuspense<TData = Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError = ErrorType<GetApiV2PlannedPaymentsId400 | GetApiV2PlannedPaymentsId401 | GetApiV2PlannedPaymentsId500>>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2PlannedPaymentsIdSuspense<TData = Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError = ErrorType<GetApiV2PlannedPaymentsId400 | GetApiV2PlannedPaymentsId401 | GetApiV2PlannedPaymentsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiV2PlannedPaymentsIdSuspense<TData = Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError = ErrorType<GetApiV2PlannedPaymentsId400 | GetApiV2PlannedPaymentsId401 | GetApiV2PlannedPaymentsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiV2PlannedPaymentsIdSuspense<TData = Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError = ErrorType<GetApiV2PlannedPaymentsId400 | GetApiV2PlannedPaymentsId401 | GetApiV2PlannedPaymentsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiV2PlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiV2PlannedPaymentsIdSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions , queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Actualizar un pago planificado existente por ID
 */
export const putApiV2PlannedPaymentsId = (
    id: string,
    putApiV2PlannedPaymentsIdBody: BodyType<PutApiV2PlannedPaymentsIdBody>,
 options?: SecondParameter<typeof apiClient>,) => {
      
      
      return apiClient<PutApiV2PlannedPaymentsId200>(
      {url: `/api/v2/plannedPayments/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putApiV2PlannedPaymentsIdBody
    },
      options);
    }
  


export const getPutApiV2PlannedPaymentsIdMutationOptions = <TError = ErrorType<PutApiV2PlannedPaymentsId400 | PutApiV2PlannedPaymentsId401 | PutApiV2PlannedPaymentsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV2PlannedPaymentsId>>, TError,{id: string;data: BodyType<PutApiV2PlannedPaymentsIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiV2PlannedPaymentsId>>, TError,{id: string;data: BodyType<PutApiV2PlannedPaymentsIdBody>}, TContext> => {

const mutationKey = ['putApiV2PlannedPaymentsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiV2PlannedPaymentsId>>, {id: string;data: BodyType<PutApiV2PlannedPaymentsIdBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiV2PlannedPaymentsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiV2PlannedPaymentsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiV2PlannedPaymentsId>>>
    export type PutApiV2PlannedPaymentsIdMutationBody = BodyType<PutApiV2PlannedPaymentsIdBody>
    export type PutApiV2PlannedPaymentsIdMutationError = ErrorType<PutApiV2PlannedPaymentsId400 | PutApiV2PlannedPaymentsId401 | PutApiV2PlannedPaymentsId500>

    export const usePutApiV2PlannedPaymentsId = <TError = ErrorType<PutApiV2PlannedPaymentsId400 | PutApiV2PlannedPaymentsId401 | PutApiV2PlannedPaymentsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiV2PlannedPaymentsId>>, TError,{id: string;data: BodyType<PutApiV2PlannedPaymentsIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiV2PlannedPaymentsId>>,
        TError,
        {id: string;data: BodyType<PutApiV2PlannedPaymentsIdBody>},
        TContext
      > => {

      const mutationOptions = getPutApiV2PlannedPaymentsIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * Eliminar un pago planificado por ID
 */
export const deleteApiV2PlannedPaymentsId = (
    id: string,
 options?: SecondParameter<typeof apiClient>,) => {
      
      
      return apiClient<DeleteApiV2PlannedPaymentsId200>(
      {url: `/api/v2/plannedPayments/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiV2PlannedPaymentsIdMutationOptions = <TError = ErrorType<DeleteApiV2PlannedPaymentsId400 | DeleteApiV2PlannedPaymentsId401 | DeleteApiV2PlannedPaymentsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV2PlannedPaymentsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiV2PlannedPaymentsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiV2PlannedPaymentsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiV2PlannedPaymentsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiV2PlannedPaymentsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiV2PlannedPaymentsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiV2PlannedPaymentsId>>>
    
    export type DeleteApiV2PlannedPaymentsIdMutationError = ErrorType<DeleteApiV2PlannedPaymentsId400 | DeleteApiV2PlannedPaymentsId401 | DeleteApiV2PlannedPaymentsId500>

    export const useDeleteApiV2PlannedPaymentsId = <TError = ErrorType<DeleteApiV2PlannedPaymentsId400 | DeleteApiV2PlannedPaymentsId401 | DeleteApiV2PlannedPaymentsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiV2PlannedPaymentsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiV2PlannedPaymentsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiV2PlannedPaymentsIdMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    