/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiPlannedPaymentsId200,
  DeleteApiPlannedPaymentsId400,
  DeleteApiPlannedPaymentsId401,
  DeleteApiPlannedPaymentsId500,
  GetApiPlannedPayments200,
  GetApiPlannedPayments400,
  GetApiPlannedPayments401,
  GetApiPlannedPayments500,
  GetApiPlannedPaymentsId200,
  GetApiPlannedPaymentsId400,
  GetApiPlannedPaymentsId401,
  GetApiPlannedPaymentsId500,
  PostApiPlannedPayments200,
  PostApiPlannedPayments400,
  PostApiPlannedPayments401,
  PostApiPlannedPayments500,
  PostApiPlannedPaymentsBody,
  PutApiPlannedPaymentsId200,
  PutApiPlannedPaymentsId400,
  PutApiPlannedPaymentsId401,
  PutApiPlannedPaymentsId500,
  PutApiPlannedPaymentsIdBody
} from '../../domain/models';

import { apiClient } from '../../../lib/api-client/api-client';
import type { ErrorType , BodyType } from '../../../lib/api-client/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Listar todos los pagos planificados con paginación
 */
export const getApiPlannedPayments = (
    
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<GetApiPlannedPayments200>(
      {url: `/api/plannedPayments/`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiPlannedPaymentsQueryKey = () => {
    return [
    `/api/plannedPayments/`
    ] as const;
    }

    
export const getGetApiPlannedPaymentsQueryOptions = <TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPlannedPaymentsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPlannedPayments>>> = ({ signal }) => getApiPlannedPayments(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPlannedPaymentsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPlannedPayments>>>
export type GetApiPlannedPaymentsQueryError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>


export function useGetApiPlannedPayments<TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPlannedPayments>>,
          TError,
          Awaited<ReturnType<typeof getApiPlannedPayments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPlannedPayments<TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPlannedPayments>>,
          TError,
          Awaited<ReturnType<typeof getApiPlannedPayments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPlannedPayments<TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPlannedPayments<TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPlannedPaymentsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetApiPlannedPaymentsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPlannedPaymentsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPlannedPayments>>> = ({ signal }) => getApiPlannedPayments(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPlannedPaymentsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPlannedPayments>>>
export type GetApiPlannedPaymentsSuspenseQueryError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>


export function useGetApiPlannedPaymentsSuspense<TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPlannedPaymentsSuspense<TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPlannedPaymentsSuspense<TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPlannedPaymentsSuspense<TData = Awaited<ReturnType<typeof getApiPlannedPayments>>, TError = ErrorType<GetApiPlannedPayments400 | GetApiPlannedPayments401 | GetApiPlannedPayments500>>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPayments>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPlannedPaymentsSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Crear un nuevo pago planificado
 */
export const postApiPlannedPayments = (
    postApiPlannedPaymentsBody: BodyType<PostApiPlannedPaymentsBody>,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<PostApiPlannedPayments200>(
      {url: `/api/plannedPayments/`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postApiPlannedPaymentsBody, signal
    },
      options);
    }
  


export const getPostApiPlannedPaymentsMutationOptions = <TError = ErrorType<PostApiPlannedPayments400 | PostApiPlannedPayments401 | PostApiPlannedPayments500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPlannedPayments>>, TError,{data: BodyType<PostApiPlannedPaymentsBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiPlannedPayments>>, TError,{data: BodyType<PostApiPlannedPaymentsBody>}, TContext> => {

const mutationKey = ['postApiPlannedPayments'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiPlannedPayments>>, {data: BodyType<PostApiPlannedPaymentsBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiPlannedPayments(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostApiPlannedPaymentsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiPlannedPayments>>>
    export type PostApiPlannedPaymentsMutationBody = BodyType<PostApiPlannedPaymentsBody>
    export type PostApiPlannedPaymentsMutationError = ErrorType<PostApiPlannedPayments400 | PostApiPlannedPayments401 | PostApiPlannedPayments500>

    export const usePostApiPlannedPayments = <TError = ErrorType<PostApiPlannedPayments400 | PostApiPlannedPayments401 | PostApiPlannedPayments500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPlannedPayments>>, TError,{data: BodyType<PostApiPlannedPaymentsBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiPlannedPayments>>,
        TError,
        {data: BodyType<PostApiPlannedPaymentsBody>},
        TContext
      > => {

      const mutationOptions = getPostApiPlannedPaymentsMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Obtener detalles de un pago planificado por ID
 */
export const getApiPlannedPaymentsId = (
    id: string,
 options?: SecondParameter<typeof apiClient>,signal?: AbortSignal
) => {
      
      
      return apiClient<GetApiPlannedPaymentsId200>(
      {url: `/api/plannedPayments/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getGetApiPlannedPaymentsIdQueryKey = (id?: string,) => {
    return [
    `/api/plannedPayments/${id}`
    ] as const;
    }

    
export const getGetApiPlannedPaymentsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPlannedPaymentsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>> = ({ signal }) => getApiPlannedPaymentsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPlannedPaymentsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>>
export type GetApiPlannedPaymentsIdQueryError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>


export function useGetApiPlannedPaymentsId<TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPlannedPaymentsId>>,
          TError,
          Awaited<ReturnType<typeof getApiPlannedPaymentsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPlannedPaymentsId<TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPlannedPaymentsId>>,
          TError,
          Awaited<ReturnType<typeof getApiPlannedPaymentsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPlannedPaymentsId<TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPlannedPaymentsId<TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPlannedPaymentsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getGetApiPlannedPaymentsIdSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiPlannedPaymentsIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>> = ({ signal }) => getApiPlannedPaymentsId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiPlannedPaymentsIdSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>>
export type GetApiPlannedPaymentsIdSuspenseQueryError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>


export function useGetApiPlannedPaymentsIdSuspense<TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPlannedPaymentsIdSuspense<TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiPlannedPaymentsIdSuspense<TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiPlannedPaymentsIdSuspense<TData = Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError = ErrorType<GetApiPlannedPaymentsId400 | GetApiPlannedPaymentsId401 | GetApiPlannedPaymentsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiPlannedPaymentsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient 
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiPlannedPaymentsIdSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Actualizar un pago planificado existente por ID
 */
export const putApiPlannedPaymentsId = (
    id: string,
    putApiPlannedPaymentsIdBody: BodyType<PutApiPlannedPaymentsIdBody>,
 options?: SecondParameter<typeof apiClient>,) => {
      
      
      return apiClient<PutApiPlannedPaymentsId200>(
      {url: `/api/plannedPayments/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: putApiPlannedPaymentsIdBody
    },
      options);
    }
  


export const getPutApiPlannedPaymentsIdMutationOptions = <TError = ErrorType<PutApiPlannedPaymentsId400 | PutApiPlannedPaymentsId401 | PutApiPlannedPaymentsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiPlannedPaymentsId>>, TError,{id: string;data: BodyType<PutApiPlannedPaymentsIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiPlannedPaymentsId>>, TError,{id: string;data: BodyType<PutApiPlannedPaymentsIdBody>}, TContext> => {

const mutationKey = ['putApiPlannedPaymentsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiPlannedPaymentsId>>, {id: string;data: BodyType<PutApiPlannedPaymentsIdBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiPlannedPaymentsId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutApiPlannedPaymentsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiPlannedPaymentsId>>>
    export type PutApiPlannedPaymentsIdMutationBody = BodyType<PutApiPlannedPaymentsIdBody>
    export type PutApiPlannedPaymentsIdMutationError = ErrorType<PutApiPlannedPaymentsId400 | PutApiPlannedPaymentsId401 | PutApiPlannedPaymentsId500>

    export const usePutApiPlannedPaymentsId = <TError = ErrorType<PutApiPlannedPaymentsId400 | PutApiPlannedPaymentsId401 | PutApiPlannedPaymentsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiPlannedPaymentsId>>, TError,{id: string;data: BodyType<PutApiPlannedPaymentsIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiPlannedPaymentsId>>,
        TError,
        {id: string;data: BodyType<PutApiPlannedPaymentsIdBody>},
        TContext
      > => {

      const mutationOptions = getPutApiPlannedPaymentsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Eliminar un pago planificado por ID
 */
export const deleteApiPlannedPaymentsId = (
    id: string,
 options?: SecondParameter<typeof apiClient>,) => {
      
      
      return apiClient<DeleteApiPlannedPaymentsId200>(
      {url: `/api/plannedPayments/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteApiPlannedPaymentsIdMutationOptions = <TError = ErrorType<DeleteApiPlannedPaymentsId400 | DeleteApiPlannedPaymentsId401 | DeleteApiPlannedPaymentsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiPlannedPaymentsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiPlannedPaymentsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiPlannedPaymentsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiPlannedPaymentsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiPlannedPaymentsId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiPlannedPaymentsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiPlannedPaymentsId>>>
    
    export type DeleteApiPlannedPaymentsIdMutationError = ErrorType<DeleteApiPlannedPaymentsId400 | DeleteApiPlannedPaymentsId401 | DeleteApiPlannedPaymentsId500>

    export const useDeleteApiPlannedPaymentsId = <TError = ErrorType<DeleteApiPlannedPaymentsId400 | DeleteApiPlannedPaymentsId401 | DeleteApiPlannedPaymentsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiPlannedPaymentsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiPlannedPaymentsId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteApiPlannedPaymentsIdMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    