/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiEventsId200,
  DeleteApiEventsId400,
  DeleteApiEventsId401,
  DeleteApiEventsId500,
  GetApiEvents200,
  GetApiEvents400,
  GetApiEvents401,
  GetApiEvents500,
  GetApiEventsId200,
  GetApiEventsId400,
  GetApiEventsId401,
  GetApiEventsId500,
  GetApiEventsParams,
  PostApiEvents200,
  PostApiEvents400,
  PostApiEvents401,
  PostApiEvents500,
  PostApiEventsBody,
  PutApiEventsId200,
  PutApiEventsId400,
  PutApiEventsId401,
  PutApiEventsId500,
  PutApiEventsIdBody
} from '../../domain/models';

import { apiClient } from '../../../lib/api-client/api-client';
import type { ErrorType , BodyType } from '../../../lib/api-client/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Listar todos los eventos con paginación
 */
export type getApiEventsResponse200 = {
  data: GetApiEvents200
  status: 200
}

export type getApiEventsResponse400 = {
  data: GetApiEvents400
  status: 400
}

export type getApiEventsResponse401 = {
  data: GetApiEvents401
  status: 401
}

export type getApiEventsResponse500 = {
  data: GetApiEvents500
  status: 500
}

export type getApiEventsResponseSuccess = (getApiEventsResponse200) & {
  headers: Headers;
};
export type getApiEventsResponseError = (getApiEventsResponse400 | getApiEventsResponse401 | getApiEventsResponse500) & {
  headers: Headers;
};

export type getApiEventsResponse = (getApiEventsResponseSuccess | getApiEventsResponseError)

export const getGetApiEventsUrl = (params?: GetApiEventsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/events/?${stringifiedParams}` : `/api/events/`
}

export const getApiEvents = async (params?: GetApiEventsParams, options?: RequestInit): Promise<getApiEventsResponse> => {

  return apiClient<getApiEventsResponse>(getGetApiEventsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiEventsQueryKey = (params?: GetApiEventsParams,) => {
    return [
    `/api/events/`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiEventsQueryOptions = <TData = Awaited<ReturnType<typeof getApiEvents>>, TError = ErrorType<GetApiEvents400 | GetApiEvents401 | GetApiEvents500>>(params?: GetApiEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEvents>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiEventsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiEvents>>> = ({ signal }) => getApiEvents(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiEventsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiEvents>>>
export type GetApiEventsQueryError = ErrorType<GetApiEvents400 | GetApiEvents401 | GetApiEvents500>


export function useGetApiEvents<TData = Awaited<ReturnType<typeof getApiEvents>>, TError = ErrorType<GetApiEvents400 | GetApiEvents401 | GetApiEvents500>>(
 params: undefined |  GetApiEventsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiEvents>>,
          TError,
          Awaited<ReturnType<typeof getApiEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEvents<TData = Awaited<ReturnType<typeof getApiEvents>>, TError = ErrorType<GetApiEvents400 | GetApiEvents401 | GetApiEvents500>>(
 params?: GetApiEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiEvents>>,
          TError,
          Awaited<ReturnType<typeof getApiEvents>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEvents<TData = Awaited<ReturnType<typeof getApiEvents>>, TError = ErrorType<GetApiEvents400 | GetApiEvents401 | GetApiEvents500>>(
 params?: GetApiEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEvents>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiEvents<TData = Awaited<ReturnType<typeof getApiEvents>>, TError = ErrorType<GetApiEvents400 | GetApiEvents401 | GetApiEvents500>>(
 params?: GetApiEventsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEvents>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiEventsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetApiEventsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiEvents>>, TError = ErrorType<GetApiEvents400 | GetApiEvents401 | GetApiEvents500>>(params?: GetApiEventsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiEvents>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiEventsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiEvents>>> = ({ signal }) => getApiEvents(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiEventsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiEvents>>>
export type GetApiEventsSuspenseQueryError = ErrorType<GetApiEvents400 | GetApiEvents401 | GetApiEvents500>


export function useGetApiEventsSuspense<TData = Awaited<ReturnType<typeof getApiEvents>>, TError = ErrorType<GetApiEvents400 | GetApiEvents401 | GetApiEvents500>>(
 params: undefined |  GetApiEventsParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiEvents>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEventsSuspense<TData = Awaited<ReturnType<typeof getApiEvents>>, TError = ErrorType<GetApiEvents400 | GetApiEvents401 | GetApiEvents500>>(
 params?: GetApiEventsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiEvents>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEventsSuspense<TData = Awaited<ReturnType<typeof getApiEvents>>, TError = ErrorType<GetApiEvents400 | GetApiEvents401 | GetApiEvents500>>(
 params?: GetApiEventsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiEvents>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiEventsSuspense<TData = Awaited<ReturnType<typeof getApiEvents>>, TError = ErrorType<GetApiEvents400 | GetApiEvents401 | GetApiEvents500>>(
 params?: GetApiEventsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiEvents>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiEventsSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Crear un nuevo evento
 */
export type postApiEventsResponse200 = {
  data: PostApiEvents200
  status: 200
}

export type postApiEventsResponse400 = {
  data: PostApiEvents400
  status: 400
}

export type postApiEventsResponse401 = {
  data: PostApiEvents401
  status: 401
}

export type postApiEventsResponse500 = {
  data: PostApiEvents500
  status: 500
}

export type postApiEventsResponseSuccess = (postApiEventsResponse200) & {
  headers: Headers;
};
export type postApiEventsResponseError = (postApiEventsResponse400 | postApiEventsResponse401 | postApiEventsResponse500) & {
  headers: Headers;
};

export type postApiEventsResponse = (postApiEventsResponseSuccess | postApiEventsResponseError)

export const getPostApiEventsUrl = () => {




  return `/api/events/`
}

export const postApiEvents = async (postApiEventsBody: PostApiEventsBody, options?: RequestInit): Promise<postApiEventsResponse> => {

  return apiClient<postApiEventsResponse>(getPostApiEventsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiEventsBody,)
  }
);}




export const getPostApiEventsMutationOptions = <TError = ErrorType<PostApiEvents400 | PostApiEvents401 | PostApiEvents500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiEvents>>, TError,{data: BodyType<PostApiEventsBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiEvents>>, TError,{data: BodyType<PostApiEventsBody>}, TContext> => {

const mutationKey = ['postApiEvents'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiEvents>>, {data: BodyType<PostApiEventsBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiEvents(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiEventsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiEvents>>>
    export type PostApiEventsMutationBody = BodyType<PostApiEventsBody>
    export type PostApiEventsMutationError = ErrorType<PostApiEvents400 | PostApiEvents401 | PostApiEvents500>

    export const usePostApiEvents = <TError = ErrorType<PostApiEvents400 | PostApiEvents401 | PostApiEvents500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiEvents>>, TError,{data: BodyType<PostApiEventsBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiEvents>>,
        TError,
        {data: BodyType<PostApiEventsBody>},
        TContext
      > => {
      return useMutation(getPostApiEventsMutationOptions(options), queryClient);
    }
    /**
 * Obtener detalles de un evento por ID
 */
export type getApiEventsIdResponse200 = {
  data: GetApiEventsId200
  status: 200
}

export type getApiEventsIdResponse400 = {
  data: GetApiEventsId400
  status: 400
}

export type getApiEventsIdResponse401 = {
  data: GetApiEventsId401
  status: 401
}

export type getApiEventsIdResponse500 = {
  data: GetApiEventsId500
  status: 500
}

export type getApiEventsIdResponseSuccess = (getApiEventsIdResponse200) & {
  headers: Headers;
};
export type getApiEventsIdResponseError = (getApiEventsIdResponse400 | getApiEventsIdResponse401 | getApiEventsIdResponse500) & {
  headers: Headers;
};

export type getApiEventsIdResponse = (getApiEventsIdResponseSuccess | getApiEventsIdResponseError)

export const getGetApiEventsIdUrl = (id: string,) => {




  return `/api/events/${id}`
}

export const getApiEventsId = async (id: string, options?: RequestInit): Promise<getApiEventsIdResponse> => {

  return apiClient<getApiEventsIdResponse>(getGetApiEventsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiEventsIdQueryKey = (id: string,) => {
    return [
    `/api/events/${id}`
    ] as const;
    }


export const getGetApiEventsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiEventsId>>, TError = ErrorType<GetApiEventsId400 | GetApiEventsId401 | GetApiEventsId500>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEventsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiEventsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiEventsId>>> = ({ signal }) => getApiEventsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiEventsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiEventsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiEventsId>>>
export type GetApiEventsIdQueryError = ErrorType<GetApiEventsId400 | GetApiEventsId401 | GetApiEventsId500>


export function useGetApiEventsId<TData = Awaited<ReturnType<typeof getApiEventsId>>, TError = ErrorType<GetApiEventsId400 | GetApiEventsId401 | GetApiEventsId500>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEventsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiEventsId>>,
          TError,
          Awaited<ReturnType<typeof getApiEventsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEventsId<TData = Awaited<ReturnType<typeof getApiEventsId>>, TError = ErrorType<GetApiEventsId400 | GetApiEventsId401 | GetApiEventsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEventsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiEventsId>>,
          TError,
          Awaited<ReturnType<typeof getApiEventsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEventsId<TData = Awaited<ReturnType<typeof getApiEventsId>>, TError = ErrorType<GetApiEventsId400 | GetApiEventsId401 | GetApiEventsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEventsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiEventsId<TData = Awaited<ReturnType<typeof getApiEventsId>>, TError = ErrorType<GetApiEventsId400 | GetApiEventsId401 | GetApiEventsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiEventsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiEventsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetApiEventsIdSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiEventsId>>, TError = ErrorType<GetApiEventsId400 | GetApiEventsId401 | GetApiEventsId500>>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiEventsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiEventsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiEventsId>>> = ({ signal }) => getApiEventsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiEventsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiEventsIdSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiEventsId>>>
export type GetApiEventsIdSuspenseQueryError = ErrorType<GetApiEventsId400 | GetApiEventsId401 | GetApiEventsId500>


export function useGetApiEventsIdSuspense<TData = Awaited<ReturnType<typeof getApiEventsId>>, TError = ErrorType<GetApiEventsId400 | GetApiEventsId401 | GetApiEventsId500>>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiEventsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEventsIdSuspense<TData = Awaited<ReturnType<typeof getApiEventsId>>, TError = ErrorType<GetApiEventsId400 | GetApiEventsId401 | GetApiEventsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiEventsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiEventsIdSuspense<TData = Awaited<ReturnType<typeof getApiEventsId>>, TError = ErrorType<GetApiEventsId400 | GetApiEventsId401 | GetApiEventsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiEventsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiEventsIdSuspense<TData = Awaited<ReturnType<typeof getApiEventsId>>, TError = ErrorType<GetApiEventsId400 | GetApiEventsId401 | GetApiEventsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiEventsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiEventsIdSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Actualizar un evento existente por ID
 */
export type putApiEventsIdResponse200 = {
  data: PutApiEventsId200
  status: 200
}

export type putApiEventsIdResponse400 = {
  data: PutApiEventsId400
  status: 400
}

export type putApiEventsIdResponse401 = {
  data: PutApiEventsId401
  status: 401
}

export type putApiEventsIdResponse500 = {
  data: PutApiEventsId500
  status: 500
}

export type putApiEventsIdResponseSuccess = (putApiEventsIdResponse200) & {
  headers: Headers;
};
export type putApiEventsIdResponseError = (putApiEventsIdResponse400 | putApiEventsIdResponse401 | putApiEventsIdResponse500) & {
  headers: Headers;
};

export type putApiEventsIdResponse = (putApiEventsIdResponseSuccess | putApiEventsIdResponseError)

export const getPutApiEventsIdUrl = (id: string,) => {




  return `/api/events/${id}`
}

export const putApiEventsId = async (id: string,
    putApiEventsIdBody: PutApiEventsIdBody, options?: RequestInit): Promise<putApiEventsIdResponse> => {

  return apiClient<putApiEventsIdResponse>(getPutApiEventsIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putApiEventsIdBody,)
  }
);}




export const getPutApiEventsIdMutationOptions = <TError = ErrorType<PutApiEventsId400 | PutApiEventsId401 | PutApiEventsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiEventsId>>, TError,{id: string;data: BodyType<PutApiEventsIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiEventsId>>, TError,{id: string;data: BodyType<PutApiEventsIdBody>}, TContext> => {

const mutationKey = ['putApiEventsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiEventsId>>, {id: string;data: BodyType<PutApiEventsIdBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiEventsId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiEventsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiEventsId>>>
    export type PutApiEventsIdMutationBody = BodyType<PutApiEventsIdBody>
    export type PutApiEventsIdMutationError = ErrorType<PutApiEventsId400 | PutApiEventsId401 | PutApiEventsId500>

    export const usePutApiEventsId = <TError = ErrorType<PutApiEventsId400 | PutApiEventsId401 | PutApiEventsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiEventsId>>, TError,{id: string;data: BodyType<PutApiEventsIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiEventsId>>,
        TError,
        {id: string;data: BodyType<PutApiEventsIdBody>},
        TContext
      > => {
      return useMutation(getPutApiEventsIdMutationOptions(options), queryClient);
    }
    /**
 * Eliminar un evento por ID
 */
export type deleteApiEventsIdResponse200 = {
  data: DeleteApiEventsId200
  status: 200
}

export type deleteApiEventsIdResponse400 = {
  data: DeleteApiEventsId400
  status: 400
}

export type deleteApiEventsIdResponse401 = {
  data: DeleteApiEventsId401
  status: 401
}

export type deleteApiEventsIdResponse500 = {
  data: DeleteApiEventsId500
  status: 500
}

export type deleteApiEventsIdResponseSuccess = (deleteApiEventsIdResponse200) & {
  headers: Headers;
};
export type deleteApiEventsIdResponseError = (deleteApiEventsIdResponse400 | deleteApiEventsIdResponse401 | deleteApiEventsIdResponse500) & {
  headers: Headers;
};

export type deleteApiEventsIdResponse = (deleteApiEventsIdResponseSuccess | deleteApiEventsIdResponseError)

export const getDeleteApiEventsIdUrl = (id: string,) => {




  return `/api/events/${id}`
}

export const deleteApiEventsId = async (id: string, options?: RequestInit): Promise<deleteApiEventsIdResponse> => {

  return apiClient<deleteApiEventsIdResponse>(getDeleteApiEventsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteApiEventsIdMutationOptions = <TError = ErrorType<DeleteApiEventsId400 | DeleteApiEventsId401 | DeleteApiEventsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiEventsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiEventsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiEventsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiEventsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiEventsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiEventsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiEventsId>>>

    export type DeleteApiEventsIdMutationError = ErrorType<DeleteApiEventsId400 | DeleteApiEventsId401 | DeleteApiEventsId500>

    export const useDeleteApiEventsId = <TError = ErrorType<DeleteApiEventsId400 | DeleteApiEventsId401 | DeleteApiEventsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiEventsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiEventsId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiEventsIdMutationOptions(options), queryClient);
    }
