/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import type {
  DeleteApiBudgetsId200,
  DeleteApiBudgetsId400,
  DeleteApiBudgetsId401,
  DeleteApiBudgetsId500,
  GetApiBudgets200Item,
  GetApiBudgets400,
  GetApiBudgets401,
  GetApiBudgets500,
  GetApiBudgetsId200,
  GetApiBudgetsId400,
  GetApiBudgetsId401,
  GetApiBudgetsId500,
  GetApiBudgetsListYear200Item,
  GetApiBudgetsListYear400,
  GetApiBudgetsListYear401,
  GetApiBudgetsListYear500,
  GetApiBudgetsListYearParams,
  GetApiBudgetsParams,
  PostApiBudgets200,
  PostApiBudgets400,
  PostApiBudgets401,
  PostApiBudgets500,
  PostApiBudgetsBody,
  PutApiBudgetsId200,
  PutApiBudgetsId400,
  PutApiBudgetsId401,
  PutApiBudgetsId500,
  PutApiBudgetsIdBody
} from '../../domain/models';

import { apiClient } from '../../../lib/api-client/api-client';
import type { ErrorType , BodyType } from '../../../lib/api-client/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * Listar todos los presupuestos con paginación
 */
export type getApiBudgetsResponse200 = {
  data: GetApiBudgets200Item[]
  status: 200
}

export type getApiBudgetsResponse400 = {
  data: GetApiBudgets400
  status: 400
}

export type getApiBudgetsResponse401 = {
  data: GetApiBudgets401
  status: 401
}

export type getApiBudgetsResponse500 = {
  data: GetApiBudgets500
  status: 500
}

export type getApiBudgetsResponseSuccess = (getApiBudgetsResponse200) & {
  headers: Headers;
};
export type getApiBudgetsResponseError = (getApiBudgetsResponse400 | getApiBudgetsResponse401 | getApiBudgetsResponse500) & {
  headers: Headers;
};

export type getApiBudgetsResponse = (getApiBudgetsResponseSuccess | getApiBudgetsResponseError)

export const getGetApiBudgetsUrl = (params?: GetApiBudgetsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/budgets/?${stringifiedParams}` : `/api/budgets/`
}

export const getApiBudgets = async (params?: GetApiBudgetsParams, options?: RequestInit): Promise<getApiBudgetsResponse> => {

  return apiClient<getApiBudgetsResponse>(getGetApiBudgetsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiBudgetsQueryKey = (params?: GetApiBudgetsParams,) => {
    return [
    `/api/budgets/`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiBudgetsQueryOptions = <TData = Awaited<ReturnType<typeof getApiBudgets>>, TError = ErrorType<GetApiBudgets400 | GetApiBudgets401 | GetApiBudgets500>>(params?: GetApiBudgetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBudgets>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBudgetsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBudgets>>> = ({ signal }) => getApiBudgets(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBudgets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiBudgetsQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBudgets>>>
export type GetApiBudgetsQueryError = ErrorType<GetApiBudgets400 | GetApiBudgets401 | GetApiBudgets500>


export function useGetApiBudgets<TData = Awaited<ReturnType<typeof getApiBudgets>>, TError = ErrorType<GetApiBudgets400 | GetApiBudgets401 | GetApiBudgets500>>(
 params: undefined |  GetApiBudgetsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBudgets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBudgets>>,
          TError,
          Awaited<ReturnType<typeof getApiBudgets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBudgets<TData = Awaited<ReturnType<typeof getApiBudgets>>, TError = ErrorType<GetApiBudgets400 | GetApiBudgets401 | GetApiBudgets500>>(
 params?: GetApiBudgetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBudgets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBudgets>>,
          TError,
          Awaited<ReturnType<typeof getApiBudgets>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBudgets<TData = Awaited<ReturnType<typeof getApiBudgets>>, TError = ErrorType<GetApiBudgets400 | GetApiBudgets401 | GetApiBudgets500>>(
 params?: GetApiBudgetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBudgets>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiBudgets<TData = Awaited<ReturnType<typeof getApiBudgets>>, TError = ErrorType<GetApiBudgets400 | GetApiBudgets401 | GetApiBudgets500>>(
 params?: GetApiBudgetsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBudgets>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiBudgetsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetApiBudgetsSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiBudgets>>, TError = ErrorType<GetApiBudgets400 | GetApiBudgets401 | GetApiBudgets500>>(params?: GetApiBudgetsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiBudgets>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBudgetsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBudgets>>> = ({ signal }) => getApiBudgets(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiBudgets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiBudgetsSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBudgets>>>
export type GetApiBudgetsSuspenseQueryError = ErrorType<GetApiBudgets400 | GetApiBudgets401 | GetApiBudgets500>


export function useGetApiBudgetsSuspense<TData = Awaited<ReturnType<typeof getApiBudgets>>, TError = ErrorType<GetApiBudgets400 | GetApiBudgets401 | GetApiBudgets500>>(
 params: undefined |  GetApiBudgetsParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiBudgets>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBudgetsSuspense<TData = Awaited<ReturnType<typeof getApiBudgets>>, TError = ErrorType<GetApiBudgets400 | GetApiBudgets401 | GetApiBudgets500>>(
 params?: GetApiBudgetsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiBudgets>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBudgetsSuspense<TData = Awaited<ReturnType<typeof getApiBudgets>>, TError = ErrorType<GetApiBudgets400 | GetApiBudgets401 | GetApiBudgets500>>(
 params?: GetApiBudgetsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiBudgets>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiBudgetsSuspense<TData = Awaited<ReturnType<typeof getApiBudgets>>, TError = ErrorType<GetApiBudgets400 | GetApiBudgets401 | GetApiBudgets500>>(
 params?: GetApiBudgetsParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiBudgets>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiBudgetsSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Crear un nuevo presupuesto
 */
export type postApiBudgetsResponse200 = {
  data: PostApiBudgets200
  status: 200
}

export type postApiBudgetsResponse400 = {
  data: PostApiBudgets400
  status: 400
}

export type postApiBudgetsResponse401 = {
  data: PostApiBudgets401
  status: 401
}

export type postApiBudgetsResponse500 = {
  data: PostApiBudgets500
  status: 500
}

export type postApiBudgetsResponseSuccess = (postApiBudgetsResponse200) & {
  headers: Headers;
};
export type postApiBudgetsResponseError = (postApiBudgetsResponse400 | postApiBudgetsResponse401 | postApiBudgetsResponse500) & {
  headers: Headers;
};

export type postApiBudgetsResponse = (postApiBudgetsResponseSuccess | postApiBudgetsResponseError)

export const getPostApiBudgetsUrl = () => {




  return `/api/budgets/`
}

export const postApiBudgets = async (postApiBudgetsBody: PostApiBudgetsBody, options?: RequestInit): Promise<postApiBudgetsResponse> => {

  return apiClient<postApiBudgetsResponse>(getPostApiBudgetsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      postApiBudgetsBody,)
  }
);}




export const getPostApiBudgetsMutationOptions = <TError = ErrorType<PostApiBudgets400 | PostApiBudgets401 | PostApiBudgets500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBudgets>>, TError,{data: BodyType<PostApiBudgetsBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiBudgets>>, TError,{data: BodyType<PostApiBudgetsBody>}, TContext> => {

const mutationKey = ['postApiBudgets'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiBudgets>>, {data: BodyType<PostApiBudgetsBody>}> = (props) => {
          const {data} = props ?? {};

          return  postApiBudgets(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiBudgetsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiBudgets>>>
    export type PostApiBudgetsMutationBody = BodyType<PostApiBudgetsBody>
    export type PostApiBudgetsMutationError = ErrorType<PostApiBudgets400 | PostApiBudgets401 | PostApiBudgets500>

    export const usePostApiBudgets = <TError = ErrorType<PostApiBudgets400 | PostApiBudgets401 | PostApiBudgets500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBudgets>>, TError,{data: BodyType<PostApiBudgetsBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiBudgets>>,
        TError,
        {data: BodyType<PostApiBudgetsBody>},
        TContext
      > => {
      return useMutation(getPostApiBudgetsMutationOptions(options), queryClient);
    }
    /**
 * Obtener detalles de un presupuesto por ID
 */
export type getApiBudgetsIdResponse200 = {
  data: GetApiBudgetsId200
  status: 200
}

export type getApiBudgetsIdResponse400 = {
  data: GetApiBudgetsId400
  status: 400
}

export type getApiBudgetsIdResponse401 = {
  data: GetApiBudgetsId401
  status: 401
}

export type getApiBudgetsIdResponse500 = {
  data: GetApiBudgetsId500
  status: 500
}

export type getApiBudgetsIdResponseSuccess = (getApiBudgetsIdResponse200) & {
  headers: Headers;
};
export type getApiBudgetsIdResponseError = (getApiBudgetsIdResponse400 | getApiBudgetsIdResponse401 | getApiBudgetsIdResponse500) & {
  headers: Headers;
};

export type getApiBudgetsIdResponse = (getApiBudgetsIdResponseSuccess | getApiBudgetsIdResponseError)

export const getGetApiBudgetsIdUrl = (id: string,) => {




  return `/api/budgets/${id}`
}

export const getApiBudgetsId = async (id: string, options?: RequestInit): Promise<getApiBudgetsIdResponse> => {

  return apiClient<getApiBudgetsIdResponse>(getGetApiBudgetsIdUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiBudgetsIdQueryKey = (id: string,) => {
    return [
    `/api/budgets/${id}`
    ] as const;
    }


export const getGetApiBudgetsIdQueryOptions = <TData = Awaited<ReturnType<typeof getApiBudgetsId>>, TError = ErrorType<GetApiBudgetsId400 | GetApiBudgetsId401 | GetApiBudgetsId500>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBudgetsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBudgetsId>>> = ({ signal }) => getApiBudgetsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiBudgetsIdQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBudgetsId>>>
export type GetApiBudgetsIdQueryError = ErrorType<GetApiBudgetsId400 | GetApiBudgetsId401 | GetApiBudgetsId500>


export function useGetApiBudgetsId<TData = Awaited<ReturnType<typeof getApiBudgetsId>>, TError = ErrorType<GetApiBudgetsId400 | GetApiBudgetsId401 | GetApiBudgetsId500>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBudgetsId>>,
          TError,
          Awaited<ReturnType<typeof getApiBudgetsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBudgetsId<TData = Awaited<ReturnType<typeof getApiBudgetsId>>, TError = ErrorType<GetApiBudgetsId400 | GetApiBudgetsId401 | GetApiBudgetsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBudgetsId>>,
          TError,
          Awaited<ReturnType<typeof getApiBudgetsId>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBudgetsId<TData = Awaited<ReturnType<typeof getApiBudgetsId>>, TError = ErrorType<GetApiBudgetsId400 | GetApiBudgetsId401 | GetApiBudgetsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiBudgetsId<TData = Awaited<ReturnType<typeof getApiBudgetsId>>, TError = ErrorType<GetApiBudgetsId400 | GetApiBudgetsId401 | GetApiBudgetsId500>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiBudgetsIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetApiBudgetsIdSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiBudgetsId>>, TError = ErrorType<GetApiBudgetsId400 | GetApiBudgetsId401 | GetApiBudgetsId500>>(id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBudgetsIdQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBudgetsId>>> = ({ signal }) => getApiBudgetsId(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiBudgetsIdSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBudgetsId>>>
export type GetApiBudgetsIdSuspenseQueryError = ErrorType<GetApiBudgetsId400 | GetApiBudgetsId401 | GetApiBudgetsId500>


export function useGetApiBudgetsIdSuspense<TData = Awaited<ReturnType<typeof getApiBudgetsId>>, TError = ErrorType<GetApiBudgetsId400 | GetApiBudgetsId401 | GetApiBudgetsId500>>(
 id: string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBudgetsIdSuspense<TData = Awaited<ReturnType<typeof getApiBudgetsId>>, TError = ErrorType<GetApiBudgetsId400 | GetApiBudgetsId401 | GetApiBudgetsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBudgetsIdSuspense<TData = Awaited<ReturnType<typeof getApiBudgetsId>>, TError = ErrorType<GetApiBudgetsId400 | GetApiBudgetsId401 | GetApiBudgetsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiBudgetsIdSuspense<TData = Awaited<ReturnType<typeof getApiBudgetsId>>, TError = ErrorType<GetApiBudgetsId400 | GetApiBudgetsId401 | GetApiBudgetsId500>>(
 id: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsId>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiBudgetsIdSuspenseQueryOptions(id,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






/**
 * Actualizar un presupuesto existente por ID
 */
export type putApiBudgetsIdResponse200 = {
  data: PutApiBudgetsId200
  status: 200
}

export type putApiBudgetsIdResponse400 = {
  data: PutApiBudgetsId400
  status: 400
}

export type putApiBudgetsIdResponse401 = {
  data: PutApiBudgetsId401
  status: 401
}

export type putApiBudgetsIdResponse500 = {
  data: PutApiBudgetsId500
  status: 500
}

export type putApiBudgetsIdResponseSuccess = (putApiBudgetsIdResponse200) & {
  headers: Headers;
};
export type putApiBudgetsIdResponseError = (putApiBudgetsIdResponse400 | putApiBudgetsIdResponse401 | putApiBudgetsIdResponse500) & {
  headers: Headers;
};

export type putApiBudgetsIdResponse = (putApiBudgetsIdResponseSuccess | putApiBudgetsIdResponseError)

export const getPutApiBudgetsIdUrl = (id: string,) => {




  return `/api/budgets/${id}`
}

export const putApiBudgetsId = async (id: string,
    putApiBudgetsIdBody: PutApiBudgetsIdBody, options?: RequestInit): Promise<putApiBudgetsIdResponse> => {

  return apiClient<putApiBudgetsIdResponse>(getPutApiBudgetsIdUrl(id),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      putApiBudgetsIdBody,)
  }
);}




export const getPutApiBudgetsIdMutationOptions = <TError = ErrorType<PutApiBudgetsId400 | PutApiBudgetsId401 | PutApiBudgetsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiBudgetsId>>, TError,{id: string;data: BodyType<PutApiBudgetsIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiBudgetsId>>, TError,{id: string;data: BodyType<PutApiBudgetsIdBody>}, TContext> => {

const mutationKey = ['putApiBudgetsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiBudgetsId>>, {id: string;data: BodyType<PutApiBudgetsIdBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  putApiBudgetsId(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiBudgetsIdMutationResult = NonNullable<Awaited<ReturnType<typeof putApiBudgetsId>>>
    export type PutApiBudgetsIdMutationBody = BodyType<PutApiBudgetsIdBody>
    export type PutApiBudgetsIdMutationError = ErrorType<PutApiBudgetsId400 | PutApiBudgetsId401 | PutApiBudgetsId500>

    export const usePutApiBudgetsId = <TError = ErrorType<PutApiBudgetsId400 | PutApiBudgetsId401 | PutApiBudgetsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiBudgetsId>>, TError,{id: string;data: BodyType<PutApiBudgetsIdBody>}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiBudgetsId>>,
        TError,
        {id: string;data: BodyType<PutApiBudgetsIdBody>},
        TContext
      > => {
      return useMutation(getPutApiBudgetsIdMutationOptions(options), queryClient);
    }
    /**
 * Eliminar un presupuesto por ID
 */
export type deleteApiBudgetsIdResponse200 = {
  data: DeleteApiBudgetsId200
  status: 200
}

export type deleteApiBudgetsIdResponse400 = {
  data: DeleteApiBudgetsId400
  status: 400
}

export type deleteApiBudgetsIdResponse401 = {
  data: DeleteApiBudgetsId401
  status: 401
}

export type deleteApiBudgetsIdResponse500 = {
  data: DeleteApiBudgetsId500
  status: 500
}

export type deleteApiBudgetsIdResponseSuccess = (deleteApiBudgetsIdResponse200) & {
  headers: Headers;
};
export type deleteApiBudgetsIdResponseError = (deleteApiBudgetsIdResponse400 | deleteApiBudgetsIdResponse401 | deleteApiBudgetsIdResponse500) & {
  headers: Headers;
};

export type deleteApiBudgetsIdResponse = (deleteApiBudgetsIdResponseSuccess | deleteApiBudgetsIdResponseError)

export const getDeleteApiBudgetsIdUrl = (id: string,) => {




  return `/api/budgets/${id}`
}

export const deleteApiBudgetsId = async (id: string, options?: RequestInit): Promise<deleteApiBudgetsIdResponse> => {

  return apiClient<deleteApiBudgetsIdResponse>(getDeleteApiBudgetsIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteApiBudgetsIdMutationOptions = <TError = ErrorType<DeleteApiBudgetsId400 | DeleteApiBudgetsId401 | DeleteApiBudgetsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiBudgetsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiBudgetsId>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteApiBudgetsId'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiBudgetsId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiBudgetsId(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiBudgetsIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiBudgetsId>>>

    export type DeleteApiBudgetsIdMutationError = ErrorType<DeleteApiBudgetsId400 | DeleteApiBudgetsId401 | DeleteApiBudgetsId500>

    export const useDeleteApiBudgetsId = <TError = ErrorType<DeleteApiBudgetsId400 | DeleteApiBudgetsId401 | DeleteApiBudgetsId500>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiBudgetsId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiBudgetsId>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteApiBudgetsIdMutationOptions(options), queryClient);
    }
    /**
 * Obtener el listado por años de los presupuestos
 */
export type getApiBudgetsListYearResponse200 = {
  data: GetApiBudgetsListYear200Item[]
  status: 200
}

export type getApiBudgetsListYearResponse400 = {
  data: GetApiBudgetsListYear400
  status: 400
}

export type getApiBudgetsListYearResponse401 = {
  data: GetApiBudgetsListYear401
  status: 401
}

export type getApiBudgetsListYearResponse500 = {
  data: GetApiBudgetsListYear500
  status: 500
}

export type getApiBudgetsListYearResponseSuccess = (getApiBudgetsListYearResponse200) & {
  headers: Headers;
};
export type getApiBudgetsListYearResponseError = (getApiBudgetsListYearResponse400 | getApiBudgetsListYearResponse401 | getApiBudgetsListYearResponse500) & {
  headers: Headers;
};

export type getApiBudgetsListYearResponse = (getApiBudgetsListYearResponseSuccess | getApiBudgetsListYearResponseError)

export const getGetApiBudgetsListYearUrl = (params?: GetApiBudgetsListYearParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/budgets/list-year?${stringifiedParams}` : `/api/budgets/list-year`
}

export const getApiBudgetsListYear = async (params?: GetApiBudgetsListYearParams, options?: RequestInit): Promise<getApiBudgetsListYearResponse> => {

  return apiClient<getApiBudgetsListYearResponse>(getGetApiBudgetsListYearUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiBudgetsListYearQueryKey = (params?: GetApiBudgetsListYearParams,) => {
    return [
    `/api/budgets/list-year`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiBudgetsListYearQueryOptions = <TData = Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError = ErrorType<GetApiBudgetsListYear400 | GetApiBudgetsListYear401 | GetApiBudgetsListYear500>>(params?: GetApiBudgetsListYearParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBudgetsListYearQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBudgetsListYear>>> = ({ signal }) => getApiBudgetsListYear(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiBudgetsListYearQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBudgetsListYear>>>
export type GetApiBudgetsListYearQueryError = ErrorType<GetApiBudgetsListYear400 | GetApiBudgetsListYear401 | GetApiBudgetsListYear500>


export function useGetApiBudgetsListYear<TData = Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError = ErrorType<GetApiBudgetsListYear400 | GetApiBudgetsListYear401 | GetApiBudgetsListYear500>>(
 params: undefined |  GetApiBudgetsListYearParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBudgetsListYear>>,
          TError,
          Awaited<ReturnType<typeof getApiBudgetsListYear>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBudgetsListYear<TData = Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError = ErrorType<GetApiBudgetsListYear400 | GetApiBudgetsListYear401 | GetApiBudgetsListYear500>>(
 params?: GetApiBudgetsListYearParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiBudgetsListYear>>,
          TError,
          Awaited<ReturnType<typeof getApiBudgetsListYear>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBudgetsListYear<TData = Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError = ErrorType<GetApiBudgetsListYear400 | GetApiBudgetsListYear401 | GetApiBudgetsListYear500>>(
 params?: GetApiBudgetsListYearParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiBudgetsListYear<TData = Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError = ErrorType<GetApiBudgetsListYear400 | GetApiBudgetsListYear401 | GetApiBudgetsListYear500>>(
 params?: GetApiBudgetsListYearParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiBudgetsListYearQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetApiBudgetsListYearSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError = ErrorType<GetApiBudgetsListYear400 | GetApiBudgetsListYear401 | GetApiBudgetsListYear500>>(params?: GetApiBudgetsListYearParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiBudgetsListYearQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiBudgetsListYear>>> = ({ signal }) => getApiBudgetsListYear(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiBudgetsListYearSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiBudgetsListYear>>>
export type GetApiBudgetsListYearSuspenseQueryError = ErrorType<GetApiBudgetsListYear400 | GetApiBudgetsListYear401 | GetApiBudgetsListYear500>


export function useGetApiBudgetsListYearSuspense<TData = Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError = ErrorType<GetApiBudgetsListYear400 | GetApiBudgetsListYear401 | GetApiBudgetsListYear500>>(
 params: undefined |  GetApiBudgetsListYearParams, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBudgetsListYearSuspense<TData = Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError = ErrorType<GetApiBudgetsListYear400 | GetApiBudgetsListYear401 | GetApiBudgetsListYear500>>(
 params?: GetApiBudgetsListYearParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiBudgetsListYearSuspense<TData = Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError = ErrorType<GetApiBudgetsListYear400 | GetApiBudgetsListYear401 | GetApiBudgetsListYear500>>(
 params?: GetApiBudgetsListYearParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiBudgetsListYearSuspense<TData = Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError = ErrorType<GetApiBudgetsListYear400 | GetApiBudgetsListYear401 | GetApiBudgetsListYear500>>(
 params?: GetApiBudgetsListYearParams, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiBudgetsListYear>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiBudgetsListYearSuspenseQueryOptions(params,options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






