/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Emma API
 * Documentation in swagger API to EMMA
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query';

import { apiClient } from '../../../lib/api-client/api-client';
import type { ErrorType } from '../../../lib/api-client/api-client';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type postApiAccountsImportAccountsResponse200 = {
  data: void
  status: 200
}

export type postApiAccountsImportAccountsResponseSuccess = (postApiAccountsImportAccountsResponse200) & {
  headers: Headers;
};
;

export type postApiAccountsImportAccountsResponse = (postApiAccountsImportAccountsResponseSuccess)

export const getPostApiAccountsImportAccountsUrl = () => {




  return `/api/accounts/import-accounts`
}

export const postApiAccountsImportAccounts = async ( options?: RequestInit): Promise<postApiAccountsImportAccountsResponse> => {

  return apiClient<postApiAccountsImportAccountsResponse>(getPostApiAccountsImportAccountsUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiAccountsImportAccountsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountsImportAccounts>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAccountsImportAccounts>>, TError,void, TContext> => {

const mutationKey = ['postApiAccountsImportAccounts'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAccountsImportAccounts>>, void> = () => {


          return  postApiAccountsImportAccounts(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAccountsImportAccountsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAccountsImportAccounts>>>

    export type PostApiAccountsImportAccountsMutationError = ErrorType<unknown>

    export const usePostApiAccountsImportAccounts = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAccountsImportAccounts>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAccountsImportAccounts>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiAccountsImportAccountsMutationOptions(options), queryClient);
    }
    export type getApiAuthResponse200 = {
  data: void
  status: 200
}

export type getApiAuthResponseSuccess = (getApiAuthResponse200) & {
  headers: Headers;
};
;

export type getApiAuthResponse = (getApiAuthResponseSuccess)

export const getGetApiAuthUrl = (: string,) => {




  return `/api/auth/${}`
}

export const getApiAuth = async (: string, options?: RequestInit): Promise<getApiAuthResponse> => {

  return apiClient<getApiAuthResponse>(getGetApiAuthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetApiAuthQueryKey = (: string,) => {
    return [
    `/api/auth/${}`
    ] as const;
    }


export const getGetApiAuthQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuth>>, TError = ErrorType<unknown>>(: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuth>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAuthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuth>>> = ({ signal }) => getApiAuth({ signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiAuth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAuthQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuth>>>
export type GetApiAuthQueryError = ErrorType<unknown>


export function useGetApiAuth<TData = Awaited<ReturnType<typeof getApiAuth>>, TError = ErrorType<unknown>>(
 : string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuth>>,
          TError,
          Awaited<ReturnType<typeof getApiAuth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuth<TData = Awaited<ReturnType<typeof getApiAuth>>, TError = ErrorType<unknown>>(
 : string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiAuth>>,
          TError,
          Awaited<ReturnType<typeof getApiAuth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuth<TData = Awaited<ReturnType<typeof getApiAuth>>, TError = ErrorType<unknown>>(
 : string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuth>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAuth<TData = Awaited<ReturnType<typeof getApiAuth>>, TError = ErrorType<unknown>>(
 : string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiAuth>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAuthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetApiAuthSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof getApiAuth>>, TError = ErrorType<unknown>>(: string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAuth>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiAuthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiAuth>>> = ({ signal }) => getApiAuth({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAuth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiAuthSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof getApiAuth>>>
export type GetApiAuthSuspenseQueryError = ErrorType<unknown>


export function useGetApiAuthSuspense<TData = Awaited<ReturnType<typeof getApiAuth>>, TError = ErrorType<unknown>>(
 : string, options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAuth>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthSuspense<TData = Awaited<ReturnType<typeof getApiAuth>>, TError = ErrorType<unknown>>(
 : string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAuth>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiAuthSuspense<TData = Awaited<ReturnType<typeof getApiAuth>>, TError = ErrorType<unknown>>(
 : string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAuth>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiAuthSuspense<TData = Awaited<ReturnType<typeof getApiAuth>>, TError = ErrorType<unknown>>(
 : string, options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiAuth>>, TError, TData>>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient
 ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiAuthSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions, queryClient) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type headApiAuthResponse200 = {
  data: void
  status: 200
}

export type headApiAuthResponseSuccess = (headApiAuthResponse200) & {
  headers: Headers;
};
;

export type headApiAuthResponse = (headApiAuthResponseSuccess)

export const getHeadApiAuthUrl = (: string,) => {




  return `/api/auth/${}`
}

export const headApiAuth = async (: string, options?: RequestInit): Promise<headApiAuthResponse> => {

  return apiClient<headApiAuthResponse>(getHeadApiAuthUrl(),
  {
    ...options,
    method: 'HEAD'


  }
);}




export const getHeadApiAuthMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof headApiAuth>>, TError,{: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof headApiAuth>>, TError,{: string}, TContext> => {

const mutationKey = ['headApiAuth'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof headApiAuth>>, {: string}> = () => {


          return  headApiAuth(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type HeadApiAuthMutationResult = NonNullable<Awaited<ReturnType<typeof headApiAuth>>>

    export type HeadApiAuthMutationError = ErrorType<unknown>

    export const useHeadApiAuth = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof headApiAuth>>, TError,{: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof headApiAuth>>,
        TError,
        {: string},
        TContext
      > => {
      return useMutation(getHeadApiAuthMutationOptions(options), queryClient);
    }
    export type deleteApiAuthResponse200 = {
  data: void
  status: 200
}

export type deleteApiAuthResponseSuccess = (deleteApiAuthResponse200) & {
  headers: Headers;
};
;

export type deleteApiAuthResponse = (deleteApiAuthResponseSuccess)

export const getDeleteApiAuthUrl = (: string,) => {




  return `/api/auth/${}`
}

export const deleteApiAuth = async (: string, options?: RequestInit): Promise<deleteApiAuthResponse> => {

  return apiClient<deleteApiAuthResponse>(getDeleteApiAuthUrl(),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteApiAuthMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAuth>>, TError,{: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiAuth>>, TError,{: string}, TContext> => {

const mutationKey = ['deleteApiAuth'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiAuth>>, {: string}> = () => {


          return  deleteApiAuth(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiAuthMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiAuth>>>

    export type DeleteApiAuthMutationError = ErrorType<unknown>

    export const useDeleteApiAuth = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiAuth>>, TError,{: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiAuth>>,
        TError,
        {: string},
        TContext
      > => {
      return useMutation(getDeleteApiAuthMutationOptions(options), queryClient);
    }
    export type patchApiAuthResponse200 = {
  data: void
  status: 200
}

export type patchApiAuthResponseSuccess = (patchApiAuthResponse200) & {
  headers: Headers;
};
;

export type patchApiAuthResponse = (patchApiAuthResponseSuccess)

export const getPatchApiAuthUrl = (: string,) => {




  return `/api/auth/${}`
}

export const patchApiAuth = async (: string, options?: RequestInit): Promise<patchApiAuthResponse> => {

  return apiClient<patchApiAuthResponse>(getPatchApiAuthUrl(),
  {
    ...options,
    method: 'PATCH'


  }
);}




export const getPatchApiAuthMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiAuth>>, TError,{: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiAuth>>, TError,{: string}, TContext> => {

const mutationKey = ['patchApiAuth'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiAuth>>, {: string}> = () => {


          return  patchApiAuth(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiAuthMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiAuth>>>

    export type PatchApiAuthMutationError = ErrorType<unknown>

    export const usePatchApiAuth = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiAuth>>, TError,{: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiAuth>>,
        TError,
        {: string},
        TContext
      > => {
      return useMutation(getPatchApiAuthMutationOptions(options), queryClient);
    }
    export type putApiAuthResponse200 = {
  data: void
  status: 200
}

export type putApiAuthResponseSuccess = (putApiAuthResponse200) & {
  headers: Headers;
};
;

export type putApiAuthResponse = (putApiAuthResponseSuccess)

export const getPutApiAuthUrl = (: string,) => {




  return `/api/auth/${}`
}

export const putApiAuth = async (: string, options?: RequestInit): Promise<putApiAuthResponse> => {

  return apiClient<putApiAuthResponse>(getPutApiAuthUrl(),
  {
    ...options,
    method: 'PUT'


  }
);}




export const getPutApiAuthMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAuth>>, TError,{: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof putApiAuth>>, TError,{: string}, TContext> => {

const mutationKey = ['putApiAuth'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putApiAuth>>, {: string}> = () => {


          return  putApiAuth(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutApiAuthMutationResult = NonNullable<Awaited<ReturnType<typeof putApiAuth>>>

    export type PutApiAuthMutationError = ErrorType<unknown>

    export const usePutApiAuth = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putApiAuth>>, TError,{: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putApiAuth>>,
        TError,
        {: string},
        TContext
      > => {
      return useMutation(getPutApiAuthMutationOptions(options), queryClient);
    }
    export type postApiAuthResponse200 = {
  data: void
  status: 200
}

export type postApiAuthResponseSuccess = (postApiAuthResponse200) & {
  headers: Headers;
};
;

export type postApiAuthResponse = (postApiAuthResponseSuccess)

export const getPostApiAuthUrl = (: string,) => {




  return `/api/auth/${}`
}

export const postApiAuth = async (: string, options?: RequestInit): Promise<postApiAuthResponse> => {

  return apiClient<postApiAuthResponse>(getPostApiAuthUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiAuthMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuth>>, TError,{: string}, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiAuth>>, TError,{: string}, TContext> => {

const mutationKey = ['postApiAuth'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiAuth>>, {: string}> = () => {


          return  postApiAuth(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiAuthMutationResult = NonNullable<Awaited<ReturnType<typeof postApiAuth>>>

    export type PostApiAuthMutationError = ErrorType<unknown>

    export const usePostApiAuth = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiAuth>>, TError,{: string}, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiAuth>>,
        TError,
        {: string},
        TContext
      > => {
      return useMutation(getPostApiAuthMutationOptions(options), queryClient);
    }
    export type postApiBadgesImportResponse200 = {
  data: void
  status: 200
}

export type postApiBadgesImportResponseSuccess = (postApiBadgesImportResponse200) & {
  headers: Headers;
};
;

export type postApiBadgesImportResponse = (postApiBadgesImportResponseSuccess)

export const getPostApiBadgesImportUrl = () => {




  return `/api/badges/import`
}

export const postApiBadgesImport = async ( options?: RequestInit): Promise<postApiBadgesImportResponse> => {

  return apiClient<postApiBadgesImportResponse>(getPostApiBadgesImportUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiBadgesImportMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBadgesImport>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiBadgesImport>>, TError,void, TContext> => {

const mutationKey = ['postApiBadgesImport'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiBadgesImport>>, void> = () => {


          return  postApiBadgesImport(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiBadgesImportMutationResult = NonNullable<Awaited<ReturnType<typeof postApiBadgesImport>>>

    export type PostApiBadgesImportMutationError = ErrorType<unknown>

    export const usePostApiBadgesImport = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBadgesImport>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiBadgesImport>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiBadgesImportMutationOptions(options), queryClient);
    }
    export type postApiBudgetsImportBudgetsResponse200 = {
  data: void
  status: 200
}

export type postApiBudgetsImportBudgetsResponseSuccess = (postApiBudgetsImportBudgetsResponse200) & {
  headers: Headers;
};
;

export type postApiBudgetsImportBudgetsResponse = (postApiBudgetsImportBudgetsResponseSuccess)

export const getPostApiBudgetsImportBudgetsUrl = () => {




  return `/api/budgets/import-budgets`
}

export const postApiBudgetsImportBudgets = async ( options?: RequestInit): Promise<postApiBudgetsImportBudgetsResponse> => {

  return apiClient<postApiBudgetsImportBudgetsResponse>(getPostApiBudgetsImportBudgetsUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiBudgetsImportBudgetsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBudgetsImportBudgets>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiBudgetsImportBudgets>>, TError,void, TContext> => {

const mutationKey = ['postApiBudgetsImportBudgets'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiBudgetsImportBudgets>>, void> = () => {


          return  postApiBudgetsImportBudgets(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiBudgetsImportBudgetsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiBudgetsImportBudgets>>>

    export type PostApiBudgetsImportBudgetsMutationError = ErrorType<unknown>

    export const usePostApiBudgetsImportBudgets = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiBudgetsImportBudgets>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiBudgetsImportBudgets>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiBudgetsImportBudgetsMutationOptions(options), queryClient);
    }
    export type postApiCategoriesImportCategoriesResponse200 = {
  data: void
  status: 200
}

export type postApiCategoriesImportCategoriesResponseSuccess = (postApiCategoriesImportCategoriesResponse200) & {
  headers: Headers;
};
;

export type postApiCategoriesImportCategoriesResponse = (postApiCategoriesImportCategoriesResponseSuccess)

export const getPostApiCategoriesImportCategoriesUrl = () => {




  return `/api/categories/import-categories`
}

export const postApiCategoriesImportCategories = async ( options?: RequestInit): Promise<postApiCategoriesImportCategoriesResponse> => {

  return apiClient<postApiCategoriesImportCategoriesResponse>(getPostApiCategoriesImportCategoriesUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiCategoriesImportCategoriesMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCategoriesImportCategories>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiCategoriesImportCategories>>, TError,void, TContext> => {

const mutationKey = ['postApiCategoriesImportCategories'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiCategoriesImportCategories>>, void> = () => {


          return  postApiCategoriesImportCategories(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiCategoriesImportCategoriesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiCategoriesImportCategories>>>

    export type PostApiCategoriesImportCategoriesMutationError = ErrorType<unknown>

    export const usePostApiCategoriesImportCategories = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiCategoriesImportCategories>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiCategoriesImportCategories>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiCategoriesImportCategoriesMutationOptions(options), queryClient);
    }
    export type postApiEventsImportEventsResponse200 = {
  data: void
  status: 200
}

export type postApiEventsImportEventsResponseSuccess = (postApiEventsImportEventsResponse200) & {
  headers: Headers;
};
;

export type postApiEventsImportEventsResponse = (postApiEventsImportEventsResponseSuccess)

export const getPostApiEventsImportEventsUrl = () => {




  return `/api/events/import-events`
}

export const postApiEventsImportEvents = async ( options?: RequestInit): Promise<postApiEventsImportEventsResponse> => {

  return apiClient<postApiEventsImportEventsResponse>(getPostApiEventsImportEventsUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiEventsImportEventsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiEventsImportEvents>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiEventsImportEvents>>, TError,void, TContext> => {

const mutationKey = ['postApiEventsImportEvents'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiEventsImportEvents>>, void> = () => {


          return  postApiEventsImportEvents(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiEventsImportEventsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiEventsImportEvents>>>

    export type PostApiEventsImportEventsMutationError = ErrorType<unknown>

    export const usePostApiEventsImportEvents = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiEventsImportEvents>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiEventsImportEvents>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiEventsImportEventsMutationOptions(options), queryClient);
    }
    export type postApiHeritagesImportHeritagesResponse200 = {
  data: void
  status: 200
}

export type postApiHeritagesImportHeritagesResponseSuccess = (postApiHeritagesImportHeritagesResponse200) & {
  headers: Headers;
};
;

export type postApiHeritagesImportHeritagesResponse = (postApiHeritagesImportHeritagesResponseSuccess)

export const getPostApiHeritagesImportHeritagesUrl = () => {




  return `/api/heritages/import-heritages`
}

export const postApiHeritagesImportHeritages = async ( options?: RequestInit): Promise<postApiHeritagesImportHeritagesResponse> => {

  return apiClient<postApiHeritagesImportHeritagesResponse>(getPostApiHeritagesImportHeritagesUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiHeritagesImportHeritagesMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiHeritagesImportHeritages>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiHeritagesImportHeritages>>, TError,void, TContext> => {

const mutationKey = ['postApiHeritagesImportHeritages'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiHeritagesImportHeritages>>, void> = () => {


          return  postApiHeritagesImportHeritages(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiHeritagesImportHeritagesMutationResult = NonNullable<Awaited<ReturnType<typeof postApiHeritagesImportHeritages>>>

    export type PostApiHeritagesImportHeritagesMutationError = ErrorType<unknown>

    export const usePostApiHeritagesImportHeritages = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiHeritagesImportHeritages>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiHeritagesImportHeritages>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiHeritagesImportHeritagesMutationOptions(options), queryClient);
    }
    export type postApiInvestmentsImportInvestmentsResponse200 = {
  data: void
  status: 200
}

export type postApiInvestmentsImportInvestmentsResponseSuccess = (postApiInvestmentsImportInvestmentsResponse200) & {
  headers: Headers;
};
;

export type postApiInvestmentsImportInvestmentsResponse = (postApiInvestmentsImportInvestmentsResponseSuccess)

export const getPostApiInvestmentsImportInvestmentsUrl = () => {




  return `/api/investments/import-investments`
}

export const postApiInvestmentsImportInvestments = async ( options?: RequestInit): Promise<postApiInvestmentsImportInvestmentsResponse> => {

  return apiClient<postApiInvestmentsImportInvestmentsResponse>(getPostApiInvestmentsImportInvestmentsUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiInvestmentsImportInvestmentsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiInvestmentsImportInvestments>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiInvestmentsImportInvestments>>, TError,void, TContext> => {

const mutationKey = ['postApiInvestmentsImportInvestments'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiInvestmentsImportInvestments>>, void> = () => {


          return  postApiInvestmentsImportInvestments(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiInvestmentsImportInvestmentsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiInvestmentsImportInvestments>>>

    export type PostApiInvestmentsImportInvestmentsMutationError = ErrorType<unknown>

    export const usePostApiInvestmentsImportInvestments = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiInvestmentsImportInvestments>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiInvestmentsImportInvestments>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiInvestmentsImportInvestmentsMutationOptions(options), queryClient);
    }
    export type postApiInvestmentsImportAppreciationsResponse200 = {
  data: void
  status: 200
}

export type postApiInvestmentsImportAppreciationsResponseSuccess = (postApiInvestmentsImportAppreciationsResponse200) & {
  headers: Headers;
};
;

export type postApiInvestmentsImportAppreciationsResponse = (postApiInvestmentsImportAppreciationsResponseSuccess)

export const getPostApiInvestmentsImportAppreciationsUrl = () => {




  return `/api/investments/import-appreciations`
}

export const postApiInvestmentsImportAppreciations = async ( options?: RequestInit): Promise<postApiInvestmentsImportAppreciationsResponse> => {

  return apiClient<postApiInvestmentsImportAppreciationsResponse>(getPostApiInvestmentsImportAppreciationsUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiInvestmentsImportAppreciationsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiInvestmentsImportAppreciations>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiInvestmentsImportAppreciations>>, TError,void, TContext> => {

const mutationKey = ['postApiInvestmentsImportAppreciations'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiInvestmentsImportAppreciations>>, void> = () => {


          return  postApiInvestmentsImportAppreciations(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiInvestmentsImportAppreciationsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiInvestmentsImportAppreciations>>>

    export type PostApiInvestmentsImportAppreciationsMutationError = ErrorType<unknown>

    export const usePostApiInvestmentsImportAppreciations = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiInvestmentsImportAppreciations>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiInvestmentsImportAppreciations>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiInvestmentsImportAppreciationsMutationOptions(options), queryClient);
    }
    export type postApiMovementsImportMovementsResponse200 = {
  data: void
  status: 200
}

export type postApiMovementsImportMovementsResponseSuccess = (postApiMovementsImportMovementsResponse200) & {
  headers: Headers;
};
;

export type postApiMovementsImportMovementsResponse = (postApiMovementsImportMovementsResponseSuccess)

export const getPostApiMovementsImportMovementsUrl = () => {




  return `/api/movements/import-movements`
}

export const postApiMovementsImportMovements = async ( options?: RequestInit): Promise<postApiMovementsImportMovementsResponse> => {

  return apiClient<postApiMovementsImportMovementsResponse>(getPostApiMovementsImportMovementsUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiMovementsImportMovementsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMovementsImportMovements>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiMovementsImportMovements>>, TError,void, TContext> => {

const mutationKey = ['postApiMovementsImportMovements'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiMovementsImportMovements>>, void> = () => {


          return  postApiMovementsImportMovements(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiMovementsImportMovementsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiMovementsImportMovements>>>

    export type PostApiMovementsImportMovementsMutationError = ErrorType<unknown>

    export const usePostApiMovementsImportMovements = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiMovementsImportMovements>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiMovementsImportMovements>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiMovementsImportMovementsMutationOptions(options), queryClient);
    }
    export type postApiPlannedPaymentsImportPlaymentsResponse200 = {
  data: void
  status: 200
}

export type postApiPlannedPaymentsImportPlaymentsResponseSuccess = (postApiPlannedPaymentsImportPlaymentsResponse200) & {
  headers: Headers;
};
;

export type postApiPlannedPaymentsImportPlaymentsResponse = (postApiPlannedPaymentsImportPlaymentsResponseSuccess)

export const getPostApiPlannedPaymentsImportPlaymentsUrl = () => {




  return `/api/plannedPayments/import-playments`
}

export const postApiPlannedPaymentsImportPlayments = async ( options?: RequestInit): Promise<postApiPlannedPaymentsImportPlaymentsResponse> => {

  return apiClient<postApiPlannedPaymentsImportPlaymentsResponse>(getPostApiPlannedPaymentsImportPlaymentsUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getPostApiPlannedPaymentsImportPlaymentsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPlannedPaymentsImportPlayments>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
): UseMutationOptions<Awaited<ReturnType<typeof postApiPlannedPaymentsImportPlayments>>, TError,void, TContext> => {

const mutationKey = ['postApiPlannedPaymentsImportPlayments'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postApiPlannedPaymentsImportPlayments>>, void> = () => {


          return  postApiPlannedPaymentsImportPlayments(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostApiPlannedPaymentsImportPlaymentsMutationResult = NonNullable<Awaited<ReturnType<typeof postApiPlannedPaymentsImportPlayments>>>

    export type PostApiPlannedPaymentsImportPlaymentsMutationError = ErrorType<unknown>

    export const usePostApiPlannedPaymentsImportPlayments = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postApiPlannedPaymentsImportPlayments>>, TError,void, TContext>, request?: SecondParameter<typeof apiClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postApiPlannedPaymentsImportPlayments>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostApiPlannedPaymentsImportPlaymentsMutationOptions(options), queryClient);
    }
